hashicorp/terraform-provider-tfe

tfe/resource_tfe_workspace.go, website/docs/r/workspace.html.markdown
=> Export the Terraform Enterprise workspace ID

tfe/provider.go, tfe/provider_test.go, tfe/resource_tfe_oauth_client.go, tfe/resource_tfe_oauth_client_test.go, website/docs/r/oauth_client.html.markdown, website/docs/r/policy_set.html.markdown, website/docs/r/sentinel_policy.html.markdown, website/docs/r/ssh_key.html.markdown, website/docs/r/variable.html.markdown, website/docs/r/workspace.html.markdown, website/tfe.erb
=> Add support for managing OAuth Clients

tfe/provider.go
Depends on https://github.com/hashicorp/terraform/pull/20131
----
This will allow anyone to debug any potential provider issues more easily.
The exact same mechanism is already in use in number of other providers (e.g. GCP, GitHub or Fastly).
Here's an example from log (when compiled with this patch):
```
2019-01-26T18:26:05.345Z [DEBUG] plugin.terraform-provider-tfe: ---[ REQUEST ]---------------------------------------
2019-01-26T18:26:05.345Z [DEBUG] plugin.terraform-provider-tfe: GET / HTTP/1.1
2019-01-26T18:26:05.345Z [DEBUG] plugin.terraform-provider-tfe: Host: app.terraform.io
2019-01-26T18:26:05.345Z [DEBUG] plugin.terraform-provider-tfe: User-Agent: go-tfe
2019-01-26T18:26:05.345Z [DEBUG] plugin.terraform-provider-tfe: Accept-Encoding: gzip
2019-01-26T18:26:05.345Z [DEBUG] …
```
=> provider: Enable request/response logging

tfe/provider.go, tfe/provider_test.go, version/version.go
This PR fixes #17 and improves the UX by returning more detailed error messages. This code is duplicated from the remote backend to make sure the behavior and returned errors are consistent.
=> Report detailed version constraints info

website/docs/r/policy_set.html.markdown
Tidies up some of the docs for Policy Sets.
Resolves #84
=> Fix some Policy Sets documentation

website/docs/r/team_organization_member.html.markdown
=> Fix missing quote

tfe/resource_tfe_policy_set_test.go
This test was added in the wrong place, so I'm just moving it to where it goes. 
This is just a change to the tests so, just make sure all the test still pass.
=> Move r/tfe_policy_set invalid name test to the correct place

tfe/resource_tfe_run_trigger.go, tfe/resource_tfe_run_trigger_test.go
_Delete this section if your change is not introducing a breaking change to the provider or a breaking change from the TFE API_
- [Related PR](https://github.com/terraform-providers/terraform-provider-tfe/pull/xxxx)
_Please run the full suite of acceptance tests locally and include the output here._
```
$ …
```
=> Ko run triggers retry

tfe/resource_tfe_registry_module.go
When creating a new module in the registry, we need to check if the
registry has finished importing it before returning. If we don't and the
Read() function is called before the process is over then we end up with
an invalid terraform state.
_Please run the full suite of acceptance tests locally and include the output here._
```
❯ TESTARGS='-run TestAccTFERegistryModule_vcs' make testacc
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v -run TestAccTFERegistryModule_vcs -timeout 15m
?       github.com/terraform-providers/terraform-provider-tfe   [no test files]
=== RUN   TestAccTFERegistryModule_vcs
--- PASS: TestAccTFERegistryModule_vcs (34.29s)
PASS
ok      github.com/terraform-providers/terraform-provider-tfe/tfe …
```
=> Check if module has been imported

.circleci/config.yml, .github/pull_request_template.md, .gitignore, CHANGELOG.md, README.md, go.mod, main.go, tfe/data_source_workspace_ids.go, tfe/provider.go, tfe/provider_test.go, tfe/resource_tfe_notification_configuration.go, tfe/resource_tfe_policy_set.go, tfe/resource_tfe_run_trigger.go
```for file in $(git grep -rl terraform-providers/terraform-provider-tfe|sort -u); do sed -i '' 's/terraform-providers\/terraform-provider-tfe/hashicorp\/terraform-provider-tfe/g' $file ; done```
=> update references to terraform-providers

README.md, TESTS.md
Revamps the README a bit, bringing some things up-to-date, reorganizing everything a bit more sensibly, and relentlessly cutting out some quickly-out-of-date details that are canonically written elsewhere and directing people to those sources.
=> README overhaul

go.mod, go.sum, tfe/data_source_workspace.go, tfe/data_source_workspace_test.go, tfe/resource_tfe_workspace.go, tfe/resource_tfe_workspace_test.go, vendor/github.com/hashicorp/go-tfe/README.md, vendor/github.com/hashicorp/go-tfe/TESTS.md, vendor/github.com/hashicorp/go-tfe/agent_pool.go, vendor/github.com/hashicorp/go-tfe/state_version.go, vendor/github.com/hashicorp/go-tfe/state_version_output.go, vendor/github.com/hashicorp/go-tfe/tfe.go, vendor/github.com/hashicorp/go-tfe/workspace.go, vendor/modules.txt, website/docs/d/workspace.html.markdown, website/docs/r/workspace.html.markdown
Add `tfe_workspace.allow_destroy_plan` from the [Workspaces API](https://www.terraform.io/docs/cloud/api/workspaces.html)
- [Requires go-tfe#154](https://github.com/hashicorp/go-tfe/pull/154)
=> Add tfe_workspace.allow_destroy_plan

website/docs/r/workspace.html.markdown
Adds some clarification on the initial state of provisioned workspaces and the presence or lack of VCS options.
Closes #248
=> Clarify provisioning of API/CLI driven workspaces

tfe/provider.go
Update the error message to inform the user on what to do to fix their missing token problem. 
Do not include token, and ensure the error message appears.
=> Provider token missing: improve error message

README.md
Add a few extra references for new contributors.
=> Add more resources for contributing to README

website/docs/r/workspace.html.markdown
=> Fix documentation example

go.mod, go.sum, tfe/client_mock.go, tfe/data_source_workspace.go, tfe/data_source_workspace_ids.go, tfe/data_source_workspace_ids_test.go, tfe/data_source_workspace_test.go, tfe/resource_tfe_workspace.go, tfe/resource_tfe_workspace_test.go, website/docs/d/workspace.html.markdown, website/docs/d/workspace_ids.html.markdown, website/docs/r/workspace.html.markdown
```hcl
// adding tags
resource "tfe_workspace" "test" {
name         = "my-workspace-name"
organization = "my-organization"
tag_names    = ["prod", "database", "app"]
}
// linking resources by tags
data "tfe_workspace_ids" "prod-apps" {
tag_names    = ["prod", "app", "aws"]
organization = "my-org-name"
}
// now you can attach resources via tag
resource "tfe_policy_set" "test" {
name          = "my-policy-set"
description   = "A brand new policy set"
organization  = "my-org-name"
workspace_ids = values(data.tfe_workspace_ids.prod-apps.ids)
}
// resources available via `workspace_ids` or looped `workspace_id`:
// - tfe_policy_set
// - tfe_variable
// - tfe_notification_configuration
// - tfe_team_access
// - tfe_run_trigger
```
1.  check the docs
docs and go-tfe coming soon
_Please run …
=> Add Workspace Tags

website/docs/r/oauth_client.html.markdown
provide more explaination for oauth_token.
_If you are an external contributor, your …
=> provide more explaination for oauth_token

tfe/data_source_workspace_ids_test.go
Fixes the flaky test associated with data source workspace ids
1. CI Only
=> flaky test fix

website/docs/r/policy_set.html.markdown
=> Fix doc bug in policy-set resource example

tfe/data_source_workspace.go, tfe/data_source_workspace_ids_test.go, tfe/data_source_workspace_test.go, tfe/resource_tfe_workspace_test.go
=> backport: don't populate data.remote_state_consumer_ids if global

CHANGELOG.md
Changelog for `0.28.0` release. This PR also includes the changelog for `0.27.1`
=> 0.28.0 (Unreleased)

website/docs/r/team.html.markdown
Extends the examples to cover adding org access
=> Add example for Organization Access

CHANGELOG.md
=> Changelog for v0.29.0 (unreleased)

README.md, website/docs/index.html.markdown
Update the README and website docs to denote the latest version: 0.29.0
=> Update version examples to v0.29.0

CHANGELOG.md
=> Update changelog to v0.30

website/docs/r/variable.html.markdown, website/docs/r/variable_set.html.markdown
Fixed incorrect workspace resource reference, should be `name` not `id`. And added docs to show how to import variable sets and variables that are part of a variable set.
=> Update Variable & Variable Sets Documentation

website/docs/r/workspace.html.markdown
Updated docs to reflect that workspace tags can contain hyphens
_Remember to:_
- [Related …
=> updated docs to reflect that workspace tags can contain hyphens

CHANGELOG.md, README.md, website/docs/index.html.markdown
* Update changelog for release.
* Bump version in README and usage example in docs
N/A
N/A
=> Bump for 0.33.0 release

.github/CODEOWNERS
Update the codeowners file to a team name that exists.
=> Update team name to one that exists

CHANGELOG.md, README.md, website/docs/index.html.markdown
* Update changelog for release.
* Bump version in README and usage example in docs
N/A
N/A
=> bump for 0.34.0 release

README.md, website/docs/index.html.markdown
* Bump version in README and usage example in docs
N/A
N/A
=> bump 0.35.0 version

tflocal/main.tf, tflocal/outputs.tf, tflocal/providers.tf, tflocal/terraform.tf, tflocal/variables.tf
The initial configuration that provisions a `tflocal` instance that our CI pipeline will consume.
=> Initial tflocal configuration

.github/pull_request_template.md
Update links in pull request template as a follow-up of https://github.com/hashicorp/terraform-provider-tfe/pull/574.
=> docs: Update links in pull request template

tfe/resource_tfe_workspace_policy_set_test.go
=> fix failing tests on main

tfe/resource_tfe_team_access.go
When I run `make` locally, this file isn't in the correct format. Let's fix it!
_Remember to:_
If you pull this branch and run `make` there shouldn't be any complaints suggesting that you run `make fmt`.
```
...
```
=> Run make fmt on file

CHANGELOG.md, README.md, website/docs/index.html.markdown
Update the changelog and docs for release 0.37.0.
_Remember to:_
N/A
N/A
```
...
```
=> Update changelog and docs for release

README.md
Small style update to list in README to apply bold consistently.
N/A
N/A
N/A
=> 📝 Add consistent bolding in list

tfe/resource_tfe_team_organization_members.go, tfe/resource_tfe_team_organization_members_test.go
This is a bug I found in an unreleased resource so there is no need to change the release notes. These membership IDs could have been deleted by another resource in the same plan, such as tfe_organization_member (see testing plan)
1. Here is a sample config you can use:
```
...
}
resource "tfe_team" "test" {
name         = "happy-team"
organization = "hashicorp"
}
resource "tfe_organization_membership" "example1" {
organization = "hashicorp"
email = "example1@hashicorp.com"
}
resource "tfe_organization_membership" "example2" {
organization = "hashicorp"
email = "example2@hashicorp.com"
}
resource "tfe_organization_membership" "example3" {
organization = "hashicorp"
email = "example3@hashicorp.com"
}
resource "tfe_team_organization_members" "test" {
team_id = …
```
=> fix: don't delete nonexisting team memberships

tflocal/main.tf, tflocal/variables.tf
Required artifactory and DD variables added to module that I missed in our last PR. I should probably enable spec plans...
=> Add missing artifactory, datadog vars

docs/changelog-process.md
Update changelog with @nfagerlund and @Uk1288
=> Add more context about what we like to see in the changelog

CHANGELOG.md, tfe/resource_tfe_notification_configuration.go, website/docs/r/notification_configuration.html.markdown
=> Assessment triggers

CHANGELOG.md
This PR updates the CHANGELOG.md to align with release v0.39.0
=> Update CHANGELOG for v0.39.0

website/docs/r/workspace_run_task.html.markdown
I got this error:
```
│ Error: expected stage to be one of [pre_plan post_plan pre_apply], got pre-apply
│
│   with tfe_workspace_run_task.example3,
│   on main.tf line 53, in resource "tfe_workspace_run_task" "example3":
│   53:   stage = "pre-apply"
│
```
=> Update tfe_workspace_run_task stage documentation

README.md, website/docs/index.html.markdown
Update version referenced in docs to the latest.
_Remember to:_
=> Bump version in docs to latest

CHANGELOG.md
Full change log: https://github.com/hashicorp/terraform-provider-tfe/compare/v0.40.0...main?expand=1
=> Prep for v0.41.0 release

CHANGELOG.md, tfe/resource_tfe_workspace.go
https://github.com/hashicorp/terraform-provider-tfe/pull/675#discussion_r1065176811
=> fix: treat workspace deletion api errors as errors

.github/scripts/build_instance/main.go
* Build the instance in the tfe provider workspace.
* Fix a few error strings
1. Merge and see if we get a build!
=> Build the instance in the tfe provider workspace

tfe/provider_test.go
Add a comment about where the github environment variables are set when the tests are run.
=> Add comment about the test setup and env vars

CHANGELOG.md, README.md, website/docs/index.html.markdown
Update changelog and install/usage examples for the new version.
n/a
n/a
n/a
=> Prep for 0.43.0 release

CHANGELOG.md, tfe/resource_tfe_workspace.go
=> Optional vcs params to null

CHANGELOG.md
=> Update changelog for v0.44.0

README.md, website/docs/index.html.markdown
I often forget to do this while I'm tweaking the changelog.
=> Update version numbers in examples

website/docs/r/no_code_module.html.markdown, website/docs/r/registry_module.html.markdown
This updates the documentation for no-code
- Using the appropriate field `registry_module`
=> update no-code documentation for GA

go.mod, go.sum
Small PR to get the latest go-tfe release.
_Remember to:_
- [Related …
=> bump to go-tfe v1.23.0

website/docs/d/agent_pool.html.markdown, website/docs/r/agent_pool.html.markdown, website/docs/r/agent_token.html.markdown
So we don't need these "Cloud only" notes anymore.
Reference: https://developer.hashicorp.com/terraform/enterprise/admin/agents-on-tfe
This is a docs-only PR.
=> Docs: Agents are now also available in Terraform Enterprise

CHANGELOG.md, README.md, website/docs/index.html.markdown
Update changelog and update version in samples for next release
_Remember to:_
- [API documentation](https://developer.hashicorp.com/terraform/cloud-docs/xxxx …
=> Update changelog and update version in samples

website/docs/r/policy.html.markdown, website/docs/r/sentinel_policy.html.markdown
Managed policies are not deprecated in TFC, therefore this commit removes this note.
N/A
=> Removed managed policy note

.github/workflows/ci.yml
This PR adds automation to cancel concurrent runs, so the last push to a branch will be the only job running the test suite.
_Remember to:_
- [API …
=> add automation to cancel concurrent runs

CHANGELOG.md
This adds a changelog for github app fix in #935 
- [Related PR](https://github.com/hashicorp/terraform-provider-tfe/pull/935)
=> add changelog for github app fix

CHANGELOG.md, tfe/data_source_saml_settings.go, tfe/data_source_saml_settings_test.go, tfe/provider_next.go, website/docs/d/saml_settings.html.markdown
Copy of this PR: https://github.com/hashicorp/terraform-provider-tfe/pull/952. This PR should get closed once the other is merged.
_Remember to:_
- [API …
=> Adding saml seetings

CHANGELOG.md, tfe/data_source_saml_settings.go, website/docs/d/saml_settings.html.markdown
Prep v0.47.0 release. Contains a bug fix and documentation improvements for `data_source_saml_settings`.
=> Prep v0.47.0 release

.github/workflows/ci.yml, .github/workflows/create-release-pr.yml, .github/workflows/jira-issue-sync.yml, .github/workflows/jira-pr-transition.yml, .github/workflows/nightly-tfe-test.yml, go.mod, go.sum
This is a combination of #966 #964 #963 #962 #961 #960 #959 #951 #955 #957 #956
=> dependency bump omnibus

CHANGELOG.md, tfe/resource_tfe_workspace.go
=> Fix workspace interface conv panic

CHANGELOG.md, tfe/data_source_teams.go, tfe/data_source_teams_test.go, tfe/provider.go, website/docs/d/teams.html.markdown
=> Add tfe organization teams data source

website/docs/r/workspace_variable_set.html.markdown
=> Fixed incorrect argument desc

internal/client/config.go
Solves for this issue: https://github.com/hashicorp/terraform-provider-tfe/issues/998
_Remember to:_
_Please run applicable acceptance tests locally and include the output here. See [testing.md](https://github.com/hashicorp/terraform-provider-tfe/blob/main/docs/t …
=> update warning logs for credential files

.github/workflows/call-jira-issue-sync.yml, .github/workflows/jira-issue-sync.yml
* Add repo label
* Add conditional logic to set the correct epic
* Strip EOL whitespace
=> Update Create Jira Ticket workflow

.github/workflows/call-jira-issue-sync.yml
Trying a different nesting technique
=> Another try at updating the GH action

.github/workflows/call-jira-issue-sync.yml
_Remember to:_
_Please run applicable acceptance tests locally and include the output here. See [testing.md](https://github.com/hashicorp/terraform-provider-tfe/blob/main/docs/testing.md) to learn how to run acceptance …
=> Jira field wants an array

.github/actions/test-provider-tfe/action.yml, internal/provider/resource_tfe_workspace.go, internal/provider/resource_tfe_workspace_test.go, website/docs/r/workspace.html.markdown
This PR fixes a test failure, removes unused code, alphabetizes our arg reference list for the workspace resource.
_Remember to:_ …
=> [TF-9505] fix TestAccTFEWorkspace_updateRemoveVCSRepoWithTagsRegex

internal/provider/resource_tfe_policy_test.go
The prior attempt at updating the test passed when it shouldn't have, because changing the query _at the same time as other attributes_ has always worked; the problematic case was changing the query _without changing the description or enforce mode._ So add a test step (and config, and check func, and and and) to validate that.
1.  Behold: [on this dummy PR where I reverted the fix](https://github.com/hashicorp/terraform-provider-tfe/pull/1155) from #1154, the [test fails](https://github.com/hashicorp/terraform-provider-tfe/actions/runs/7012581665/job/19077351207?pr=1155) because it doesn't properly update query when updating query by itself. 
2. But lo! on this PR, the tests pass, because that bug is fixed.
=> tfe_policy test: Actually test the problematic case

website/docs/r/agent_pool_allowed_workspaces.html.markdown
This example was inadequate because it didn't reference workspace_settings which can now break the dependency cycle between these resource. I've also highlighted how to ensure that execution mode is assigned after (and destroyed before) allowed workspace permissions on the agent pool
_Remember to:_
=> Improve tfe_agent_pool_allowed_workspaces docs

go.mod, go.sum
=> Combines #1177 and #1179

.github/workflows/ci.yml, .github/workflows/create-release-pr.yml
bump up node to v20
_Remember to:_
_If you are an …
=> bump up node to v20

.github/actions/test-provider-tfe/action.yml, .github/workflows/ci.yml, .github/workflows/nightly-tfe-test.yml
We are disabling parallelism as we investigate ongoing run concurrency issues on our test instance. 
_Remember to:_
_Please run applicable acceptance tests locally and include the output here. See [testing.md](https://github.com/hashicorp/terraform-provider-tfe/b …
=> Temporarily disable parallelism for CI

website/docs/r/oauth_client.html.markdown
Fixing a small typo.
_Remember to:_
_If you are an …
=> Typo fix on oauth_client.html.markdown

CHANGELOG.md, README.md, website/docs/cdktf/csharp/index.html.markdown, website/docs/cdktf/go/index.html.markdown, website/docs/cdktf/java/index.html.markdown, website/docs/cdktf/python/index.html.markdown, website/docs/cdktf/typescript/index.html.markdown, website/docs/index.html.markdown
release prep for version v0.57.0
_Remember to:_ …
=> release prep for version v0.57.0

.github/workflows/release.yml
upgrade ghaction-terraform-provider-release from v3 to v5
_Remember to:_
_Please run applicable acceptance tests locally and include the output here. See [testing.md](https://github.com/hashicorp/terraform-provider-tfe/blob/main/docs/testing.md) to learn how to …
=> upgrade ghaction-terraform-provider-release from v3 to v5

CHANGELOG.md, README.md, website/docs/index.html.markdown
v0.60.0 changelog release
_Remember to:_
_If you …
=> v0.60.0 changelog

CHANGELOG.md, README.md, website/docs/index.html.markdown
=> Prepare for release v0.60.1

.github/workflows/call-jira-issue-sync.yml, META.d/_summary.yaml, docs/new-resources.md
https://hashicorp.atlassian.net/browse/TF-21760
=> Update team name

.github/actions/test-provider-tfe/action.yml, CHANGELOG.md
This PR moves a changelog entry to better reflect the state of the releases, and fixes the nightly CI test runs.
* [JIRA](https://github.com/hashicorp/terraform-provider-tfe/pull/1533)
=> chore: updating changelog

CHANGELOG.md, README.md, website/docs/index.html.markdown
Updates to prep for 0.61.0 release
=> v0.61.0 CHANGELOG

CHANGELOG.md, README.md, website/docs/index.html.markdown
Changelog and doc updates for v0.62.0
_Remember to:_
_Please run applicable acceptance tests locally and include the output here. See [testing.md](https://github.com/hashicorp/terraform-provider-tfe/blob/main/docs/testing.md) to learn how to run acceptance …
=> v0.62.0 changelog 

CHANGELOG.md, README.md, website/docs/index.html.markdown
=> Prep release for v0.64.0

internal/provider/provider.go, internal/provider/provider_next.go, internal/provider/resource_tfe_policy_set_parameter.go, internal/provider/resource_tfe_policy_set_parameter_test.go
This PR upgrades the `tfe_policy_set_parameter` resource to the provider framework.
1. Acc tests
2. Use the resource in config and verify that it works as expected.
=> feat: upgrade tfe_policy_set_parameter resource to the provider framework

CHANGELOG.md, internal/provider/resource_tfe_workspace.go, website/docs/r/workspace.html.markdown
Closes: #1670 
_Remember to:_
_If you are an …
=> fix rm ForceNew workspace source values

CHANGELOG.md
This PR updates the changelog for the v0.65.2 release.
=> docs(changelog): update changelog for v0.65.2 release

.release/terraform-provider-tfe-artifacts.hcl
This PR fixes the build artifact names in the manifest.
=> fix(crt): fix artifact names

.github/pull_request_template.md
Updates PR template to be PCI compliant
JIRA: https://hashicorp.atlassian.net/browse/TF-26123?atlOrigin=eyJpIjoiNTU5Yjk3ZDNkNDgyNGYxNmE3NTlmZjc1NDE4MjJkMWUiLCJwIjoiaiJ9
=> Update PR Template to be PCI compliant

README.md, website/docs/index.html.markdown
Prep README for next release
_Remember to:_
=> Prep README for release

.github/workflows/build.yml, .github/workflows/mkdocs.yml
This PR fixes the syntax of a couple GHA workflows that were broken by #1815.
=> chore: fix broken GHA workflows
