hashicorp/terraform-provider-tfe

- tfe/provider.go
- tfe/resource_tfe_organization.go
- tfe/resource_tfe_organization_test.go
- website/docs/r/organization.html.markdown
Rename `session_timeout` to `session_timeout_minutes` and `session_remember` to `session_remember_minutes`.
Additionally we also added the config file path to all related error messages.
This addresses the additional comments on PR #3 from @paddycarver
> Rename the session arguments to include the unit

- website/docs/index.html.markdown
TFE automatically writes a .terraformrc file with a credentials block when it
does Terraform runs, so theoretically the provider could authenticate
automatically. However, the automatically provided token is a temporary "run"
token with extremely limited privileges, and in practice it cannot manage any of
this provider's resources.
This PR also adjusts some confusing wording that implied the provider might not work with the SaaS.
(Screenshot, bc callout-within-a-list-item markdown is a lil squirrelly so I tested it to be sure:)
> website: Explain how to authenticate when managing TFE w/ TFE

- website/docs/r/team.html.markdown
It turned out that the documented import example was incorrect.
> Update the import statement docs for teams

- tfe/resource_tfe_workspace.go
This error isn't self explanatory. This PR adds clarity for a user to resolve the issue, inline with the error.
> Clarify ID format for imports

- tfe/resource_tfe_sentinel_policy.go
- tfe/resource_tfe_team.go
- tfe/resource_tfe_team_access.go
- tfe/resource_tfe_team_member.go
- tfe/resource_tfe_variable.go
- tfe/resource_tfe_workspace.go
- website/docs/r/organization.html.markdown
- website/docs/r/organization_token.html.markdown
- website/docs/r/sentinel_policy.html.markdown
- website/docs/r/team.html.markdown
- website/docs/r/team_access.html.markdown
- website/docs/r/team_member.html.markdown
- website/docs/r/team_members.html.markdown
- website/docs/r/team_token.html.markdown
- website/docs/r/variable.html.markdown
- website/docs/r/workspace.html.markdown
This PR updates the error messages to tell you what they were expecting. (I used the wrong ID format when I was testing Sentinel policies, and ended up going on a minor wild goose chase because I thought I had a different problem.)
Also, there was one inaccurate spot in the docs (`team`).
> Tidy up docs and error messages for compound import IDs

- tfe/provider.go
- tfe/resource_tfe_policy_set.go
- tfe/resource_tfe_policy_set_test.go
- tfe/resource_tfe_sentinel_policy.go
- tfe/resource_tfe_sentinel_policy_test.go
- vendor/github.com/hashicorp/go-tfe/README.md
- vendor/github.com/hashicorp/go-tfe/apply.go
- vendor/github.com/hashicorp/go-tfe/logreader.go
- vendor/github.com/hashicorp/go-tfe/organization.go
- vendor/github.com/hashicorp/go-tfe/plan.go
- vendor/github.com/hashicorp/go-tfe/policy.go
- vendor/github.com/hashicorp/go-tfe/policy_check.go
- vendor/github.com/hashicorp/go-tfe/policy_set.go
- vendor/github.com/hashicorp/go-tfe/run.go
- vendor/github.com/hashicorp/go-tfe/tfe.go
- vendor/github.com/hashicorp/go-tfe/workspace.go
- vendor/vendor.json
- website/docs/r/policy_set.html.markdown
- website/docs/r/sentinel_policy.html.markdown
- website/tfe.erb
Now that policy sets have been enabled, we can add support for it to the Terraform provider for TFE. We might want to wait until we've finalized the feature in TFE before this is merged, but we can at least get the feedback loop started!
> Add support for Sentinel policy sets

- tfe/resource_tfe_policy_set.go
- tfe/resource_tfe_policy_set_test.go
- tfe/resource_tfe_sentinel_policy.go
- vendor/github.com/hashicorp/go-tfe/go.mod
- vendor/github.com/hashicorp/go-tfe/go.sum
- vendor/github.com/hashicorp/go-tfe/logreader.go
- vendor/github.com/hashicorp/go-tfe/policy_set.go
- vendor/github.com/hashicorp/go-tfe/tfe.go
- vendor/vendor.json
There is no need to explicitly remove the attached workspaces when setting `global = true`.
> Make switching global on/off a bit cleaner

- tfe/resource_tfe_workspace.go
- tfe/resource_tfe_workspace_test.go
When a workspace name is changed out side of TF, we should still be able
to find it using it's external ID. So we first try that before we delete
the workspace from the state.
> Try to find a workspace by external ID before removing it

- go.mod
- go.sum
- vendor/github.com/hashicorp/go-tfe/tfe.go
- vendor/modules.txt
This is to align versions of `go-tfe` in TFE provider and Terraform's `v0.11` and make it easier to pull latest `v0.11` in.
Related: https://github.com/hashicorp/terraform/pull/20310
> vendor: github.com/hashicorp/go-tfe@v0.3.8

- CHANGELOG.md
- tfe/resource_tfe_workspace.go
In previous versions we used a set for the `vcs_repo` attribute. This was updated to a list which could cause migration issues. This is mitigated by adding an additional check.
Fixes #63
> Add a check when migrating vcs_repo from a set to a list

- go.mod
- go.sum
- tfe/resource_tfe_organization.go
- tfe/resource_tfe_organization_test.go
- vendor/github.com/hashicorp/go-tfe/organization.go
- vendor/github.com/hashicorp/go-tfe/run.go
- vendor/github.com/hashicorp/go-tfe/tfe.go
- vendor/github.com/hashicorp/go-tfe/workspace.go
- vendor/modules.txt
- website/docs/r/organization.html.markdown
Adds the `owners_team_saml_role_id` option to the organization resource.
This uses the latest version of go-tfe. Update go-tfe to 0.3.9 is in f48f22f.
API docs are here: https://www.terraform.io/docs/enterprise/api/organizations.html
API client PR is https://github.com/hashicorp/go-tfe/pull/57
>  Add owners_team_saml_role_id organization option

- README.md
- tfe/resource_tfe_workspace.go
- tfe/resource_tfe_workspace_test.go
- website/docs/r/workspace.html.markdown
- Removes `Computed: true` from ssh_key_id definition in schema
- Adds `Default: ""` to ssh_key_id definition in schema
- Adds test
- Fixes link in documentation
> Make ssh_key_id in workspace not computed

- README.md
- tfe/provider.go
- website/docs/index.html.markdown
Follow-up to @radeksimko's #65 as a separate PR from my fork because I don't have push access.
@svanharmelen, is this what you intended?
> Add support for TFE_HOSTNAME and TFE_TOKEN environment variables

- README.md
- go.mod
- go.sum
- tfe/provider_test.go
- tfe/resource_tfe_oauth_client_test.go
- tfe/resource_tfe_policy_set.go
- tfe/resource_tfe_policy_set_test.go
- tfe/resource_tfe_team_members_test.go
- vendor/github.com/hashicorp/go-tfe/README.md
- vendor/github.com/hashicorp/go-tfe/policy_set.go
- vendor/modules.txt
- website/docs/r/policy_set.html.markdown
This adds the necessary changes to allow for VCS policy sets.
VCS-backed policy sets are defined by supplying the vcs_repo - and
optionally, policies_path, arguments to the tfe_policy_set resource.
This is in lieu of policy_ids.
Changing either vcs_repo or policies_path will result in a new
resource being forced.
> [WIP] r/policy_set: add support for VCS policy sets

- tfe/resource_tfe_workspace.go
- tfe/resource_tfe_workspace_test.go
The monorepo fields were not being checked for changes, so if you ran an apply where only file triggers or trigger prefixes changed, it would not persist your data.
Includes a test which only updates "file triggers enabled"; this test fails without the code change.
> Ensure that changes are applied for monorepos

- website/docs/index.html.markdown
These docs moved as part of the Terraform Enterprise / Terraform Cloud
rename.
> website: Update several links to Terraform Cloud docs

- go.mod
- go.sum
- tfe/data_source_workspace.go
- tfe/resource_tfe_workspace.go
- tfe/resource_tfe_workspace_test.go
- vendor/github.com/hashicorp/go-tfe/cost_estimate.go
- vendor/github.com/hashicorp/go-tfe/organization.go
- vendor/github.com/hashicorp/go-tfe/run.go
- vendor/github.com/hashicorp/go-tfe/tfe.go
- vendor/github.com/hashicorp/go-tfe/workspace.go
- vendor/modules.txt
- website/docs/d/workspace.html.markdown
- website/docs/r/workspace.html.markdown
Attempting to add the ability to manage execution mode via the SDK. Looking for some feedback and also help with adding this to tests.
Requires https://github.com/hashicorp/go-tfe/pull/84 to be merged first.
> Adding support to configure execution mode

- website/docs/r/workspace.html.markdown
The `trigger_prefixes` line was embedded into the `terraform_version` line. Just cleaning that up.
> Fix terraform_version description.

- tfe/data_source_ssh_key_test.go
- tfe/data_source_team_access_test.go
- tfe/data_source_team_test.go
- tfe/data_source_workspace_ids_test.go
- tfe/data_source_workspace_test.go
- tfe/resource_tfe_notification_configuration_test.go
- tfe/resource_tfe_oauth_client_test.go
- tfe/resource_tfe_organization_test.go
- tfe/resource_tfe_organization_token_test.go
- tfe/resource_tfe_policy_set_test.go
- tfe/resource_tfe_sentinel_policy_test.go
- tfe/resource_tfe_ssh_key_test.go
- tfe/resource_tfe_team_access_test.go
- tfe/resource_tfe_team_member_test.go
- tfe/resource_tfe_team_members_test.go
- tfe/resource_tfe_team_test.go
- tfe/resource_tfe_team_token_test.go
- tfe/resource_tfe_variable_test.go
- tfe/resource_tfe_workspace_test.go
I've updated the test organization names to be consistent with the test organization names in go-tfe.
> Update test organization names to be consistent with go-tfe

- go.mod
- go.sum
- tfe/resource_tfe_oauth_client.go
- website/docs/r/oauth_client.html.markdown
This adds support for using Azure DevOps Server and Azure DevOps Services as valid OAuth client service providers. 
~Depends on [this go-tfe PR being merged first](https://github.com/hashicorp/go-tfe/pull/89).~
~Also depends on [this go-tfe PR being merged](https://github.com/hashicorp/go-tfe/pull/94)~
1. Build the provider
2. `cp $GOPATH/bin/terraform-provider-tfe ~/.terraform.d/plugins/`
3. Use this config:
```
hostname = "NGROK"
token    = "ADMIN_TOKEN"
}
resource "tfe_oauth_client" "ado_server" {
organization     = "hashicorp"
api_url          = "https://ado.hashicorp.engineering"
http_url         = "https://ado.hashicorp.engineering"
oauth_token      = "my-vcs-provider-token"
service_provider = "ado_server"
}
resource "tfe_oauth_client" "ado_server_with_private_key" …
```
> Add Azure DevOps Server and Azure DevOps Services as valid OAuth client service providers

- go.mod
- go.sum
- vendor/github.com/hashicorp/go-tfe/oauth_client.go
- vendor/modules.txt
Fixes issue with using oauth_client without private_key
This issue was fixed in upstream [go-tfe#96](https://github.com/hashicorp/go-tfe/pull/96)
https://github.com/hashicorp/go-tfe/commit/8b656f1e4c1b48738f180e9b171907f2dbc2c3c0#diff-46a4389c1970fe153de179797df5681d
> BUGFIX: Use isValidString not nil check for private_key

- .circleci/config.yml
This PR adds a CircleCI config so we can run acceptance tests in Circle.
> Move tests to CircleCI

- .circleci/config.yml
Added a Context to limit visibility of sensitive env vars. As a result, collaborator PR tests will error out in Circle and need to be run by a HashiCorp person.
> added context to yml

- README.md
- tfe/resource_tfe_variable.go
- tfe/resource_tfe_variable_test.go
- website/docs/r/variable.html.markdown
Workspace variables (`terraform` and `env`) now support descriptions. These descriptions are complete separate from descriptions defined in an ingressed config, but appear in the Terraform Cloud UI where Variables are configured.
Create a variable with a description like:
```
resource "tfe_variable" "pet_name_length" {
key = "pet_name_length"
value = "5"
description = "length of pet name in words"
category = "terraform"
workspace_id = tfe_workspace.workspace_name.id
}
```
[Local test results 02/10/2020](https://github.com/terraform-providers/terraform-provider-tfe/files/4182713/var-desc-tests-02102020.txt)
> Add description to workspace variables

- tfe/provider.go
A recent change that was merged caused issues for people that were on TFE < 2.2 (< 202001-1). This updates the provider to only support this release onward.
What was happening prior to this fix (which should stop happening)
1.  Use TFE < 2.2 and Provider v0.12.0
1.  Try to create a `tfe_variable`
1.  Get `Resource not found`
- [Related PR](https://github.com/terraform-providers/terraform-provider-tfe/pull/123)
Again getting issues with running tests locally. Will continue to try to get that working prior to merge.
```
$ make testacc
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v  -timeout 30m
?   	github.com/terraform-providers/terraform-provider-tfe	[no test files]
=== RUN   TestAccTFESSHKeyDataSource_basic
--- PASS: …
```
> Lock provider to tfe v2.2

- .github/pull_request_template.md
- README.md
As part of the efforts to increase stability of the provider, we are adding further documentation around breaking changes. This PR updates the `README.md` to not that `BREAKING CHANGE` is also an available change category. Additionally, the pull request template has been updated with an _optional_ **Breaking Change** section. It's important to note that the creation of API versions can only be done internally within HashiCorp.
> Update pull request template to add support for breaking changes

- go.mod
- go.sum
- tfe/provider.go
- tfe/resource_tfe_run_trigger.go
- tfe/resource_tfe_run_trigger_test.go
- vendor/github.com/hashicorp/go-tfe/README.md
- vendor/github.com/hashicorp/go-tfe/run_trigger.go
- vendor/github.com/hashicorp/go-tfe/tfe.go
- vendor/modules.txt
- website/docs/r/run_trigger.html.markdown
- website/tfe.erb
This PR adds support and documentation for creating, destroying, and importing run triggers. 
1. workspace_external_id - external id of the workspace that owns the run trigger. This is the workspace where runs will be triggered.
1. sourceable_id - id of the sourceable. The sourceable must be a workspace.
Updating workspace_external_id or sourceable_id will force the creation of a new run trigger resource. 
1. Build the provider by running `make build`
1. Move it to your Terraform plugins directory
```
mv $GOPATH/bin/terraform-provider-tfe ~/.terraform.d/plugins
```
1. Copy this config, replace hostname and email values, and save it as `main.tf`. You'll be modifying it in the steps below. Make sure you have a user token added to your `~/.terraformrc` file for your TFC hostname. 
``` …
```
> Add support for run triggers

- tfe/resource_tfe_workspace.go
- tfe/resource_tfe_workspace_test.go
Added support for changing working directory for existing workspaces.
If you create workspace with defined working directory and after apply you try to change it, provider will show there are no changes to be done. (working directory is computed value)
Issue reference #136 
Changes were made to test `TestAccTFEWorkspace_update`
```
$ make testacc
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v  -timeout 15m
?   	github.com/terraform-providers/terraform-provider-tfe	[no test files]
=== RUN   TestAccTFESSHKeyDataSource_basic
--- PASS: TestAccTFESSHKeyDataSource_basic (11.54s)
=== RUN   TestAccTFETeamAccessDataSource_basic
--- FAIL: TestAccTFETeamAccessDataSource_basic (9.51s)
testing.go:569: Step 0 error: errors during apply: …
```
> Workspace working directory updates

- CHANGELOG.md
- tfe/resource_tfe_workspace.go
- tfe/resource_tfe_workspace_test.go
Fixes a bug for `tfe_workspace` resource updates. Previously when creating a `tfe_workspace` resource with a `trigger_prefixes` configuration, this option remained even when the `trigger_prefixes` config option was removed during subsequent updates to this resource. `terraform plan` would continue outputting this change, but it would not take effect.
``` 
~ resource "tfe_workspace" "pleng_staging_us_west_2" {
auto_apply            = false
external_id           = "ws-6YmtKxQffbqJpVE6"
file_triggers_enabled = true
id                    = "chavo4/pleng-staging-us-west-2"
name                  = "pleng-staging-us-west-2"
operations            = true
organization          = "chavo4"
queue_all_runs        = true
terraform_version     = "0.12.12"
~ trigger_prefixes      = [
- …
```
> Reset trigger prefixes for workspace resources when removed from the config

- website/docs/r/run_trigger.html.markdown
We've moved this feature out of beta so all the docs need to be updated to reflect this. 
This is just a documentation change, no testing needed. 
- [Related PR - TF Cloud & API doc update](https://github.com/hashicorp/terraform-website/pull/1163)
Just a documentation update, so no need to run the tests.
> Remove beta flag from tfe_run_trigger resource documentation

- README.md
- website/docs/index.html.markdown
Our documentation should be more explicit about the recommendation to pin versions for production use of any provider. I've added some documentation to the README and to the website documentation as well. 
1. This is a documentation change, so just make sure the links I've added all work. 
I pulled the wording for this from existing documentation about constraining provider versions. Here are the docs I used:
- [Provider versions](https://www.terraform.io/docs/configuration/providers.html#provider-versions)
- [Specifying required provider versions](https://www.terraform.io/docs/configuration/terraform.html#specifying-required-provider-versions)
This is a documentation only change, so no need to run the acceptance tests.
> Add documentation on constraining provider versions

- website/docs/r/workspace.html.markdown
Workspaces use their random `ws-*` ID values as their ID attribute in Terraform, rather than `<org>/<name>` . This updates the docs to match.
- Original PR that modified IDs: #106
- Closes #153
> docs: update import ID for tfe_workspace

- website/docs/d/workspace_ids.html.markdown
- website/docs/index.html.markdown
- website/docs/r/workspace.html.markdown
This PR updates the docs to explain the different between `ids` and `external_ids` on the tfe_workspace_ids data source. Workspace IDs in the format `<ORG NAME>/<WORKSPACE NAME>` were deprecated in https://github.com/terraform-providers/terraform-provider-tfe/pull/106.
I also added notes in a few other places explaining that workspace IDs used to be different. 
I noticed some broken code blocks on the provider docs index page, so I went ahead and fixed those as well. 
1.  This is a documentation only change, so no test steps necessary.
- [Workspace ID Migration PR](https://github.com/terraform-providers/terraform-provider-tfe/pull/106)
This is a documentation only change, so no tests necessary.
> Update docs to reflect changes to workspace IDs + fix broken code block

- CHANGELOG.md
- tfe/resource_tfe_workspace.go
- tfe/resource_tfe_workspace_test.go
As reported in #149 the provider will panic if a workspace that is managed by Terraform is deleted from the web app. This PR pulls in the fix from from @sean-nixon in #150.
I added a failing test case to confirm the behavior before cherry picking the fix so we can be sure it was addressed.
CircleCI ran both commits to demonstrate the failing and passing results:
1. Failing `TestAccTFEWorkspace_panic` in [build 99](https://circleci.com/gh/terraform-providers/terraform-provider-tfe/99)
1. Passing in [build 104](https://circleci.com/gh/terraform-providers/terraform-provider-tfe/104)
1. Create and org and a workspace via Terraform with a build of this branch
1. Delete the org in TFC/E
1. Run apply again 🌮 
1. Checkout first commit on this branch. I am piping the test command to [panic …
> Fix workspace panic

- CHANGELOG.md
- tfe/resource_tfe_team.go
Fixes #179 
* Organization access is not always returned by the API, even for owners - if the organization is on the Free plan. These should not be attempted to be updated in state in this case, or a panic will occur.
* Organization access, when _not_ specified in the configuration (because it is optional), should be marked as computed. This updates state with the API response and avoids thrashing on the next plan, when the plan attempts to nullify those values (because they are still unspecified in the configuration).
1. Importing an owners team on a Free organization should not panic.
1. Not specifying organization access in configuration (Teams plan) should still result in values returned from the API stored in state, and no changes should occur immediately doing another plan. …
> Fix organization access panic + state thrashing

- website/docs/d/workspace.html.markdown
This is a small documentation change for the TFE/TFC Provider documentation to clarify the `operations` attribute. It is `boolean` but that's unclear from the current documentation. This updates provides that clarity and includes the default behaviour for further guidance.
https://www.terraform.io/docs/providers/tfe/d/workspace.html#attributes-reference lacked guidance on the `operations` attribute of the `tfe_workspace` resource.
> Providing guidance on tfe_workspace operations

- website/docs/r/team.html.markdown
Our renderer doesn't respect nested lists, so this doesn't actually work as originally intended and the change reflects how we document these sorts of things elsewhere.
> Docs: Fix tfe_resource_team's block argument

- CHANGELOG.md
- go.mod
- go.sum
- tfe/data_source_team_access.go
- tfe/data_source_team_access_test.go
- tfe/resource_tfe_team_access.go
- tfe/resource_tfe_team_access_test.go
- vendor/github.com/hashicorp/go-tfe/team_access.go
- vendor/github.com/hashicorp/go-tfe/type_helpers.go
- vendor/modules.txt
- website/docs/d/team_access.html.markdown
- website/docs/r/team_access.html.markdown
These changes contain:
* Added support for Custom workspace access in the [Team Access API](https://www.terraform.io/docs/cloud/api/team-access.html).
* In-place updating of Team Accesses rather than always ForceNew behavior
The new API behavior is tough to model because of a number of limitations within the provider SDK, such as:
* Schema validations are limited to the single attribute they are defined on; you cannot validate something with the additional context of another attribute's value in the resource.
* The SDK cannot discern between something defined _only_ in state, or _only_ in configuration. Some assumptions can be made (and are made in these changes) via GetChange(), but it's hacky at best.
After a few different iterations attempting to conditionally allow a user to edit …
> tfe_team_access: Add Custom workspace access support

- tfe/resource_tfe_registry_module_test.go
The Travis CI tests are breaking because they don't seem to be respecting my original check for this environment variable so I'm adding it to the functions themselves. 
Just see if the tests pass
> Fix broken Travis CI tests

- website/tfe.erb
I noticed we have a couple of links missing from the sidebar in the docs hosted at [terraform.io](https://www.terraform.io/docs/providers/tfe/index.html) - this PR makes the terraform.io sidebar nav consistent with the [registry.terraform.io sidebar nav](https://registry.terraform.io/providers/hashicorp/tfe/latest/docs).
**NOTE**: this commit will need to be cherry-picked to the `stable-website` branch after merge.
1. Pull down the [terraform-website](https://github.com/hashicorp/terraform-website) repo and follow [the directions for previewing provider changes](https://github.com/hashicorp/terraform-website#previewing-changes-from-providers-or-terraform-core).
1. Navigate to the tfe provider docs and verify that the sidebar contains the previously missing links.
- [tfe provider docs on …
> fix missing sidebar links

- tfe/resource_tfe_policy_set.go
- tfe/resource_tfe_policy_set_test.go
When using terraform, it can be frustrating to have a plan complete successfully as part of PR validation processes, only to have it fail after merged and attempting to apply.  In this case, using a `name` for `tfe_policy_set` that includes a space would pass PR validation but throw an error on apply as the name should only contain letters, numbers, dash, and underscore as specified in the UI.
```
TESTARGS="-run TestAccTFEPolicySet_invalidname" make testacc
```
Apologies for only running a targeted test here instead of a full suite, but I do not yet have a full acceptance test environment setup.
```
$ TESTARGS="-run TestAccTFEPolicySet_invalidname" make testacc
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v -run …
```
> add ValidateFunc to resourceTFEPolicySet to catch syntax errors at tf plan time

- tfe/resource_tfe_variable.go
- tfe/resource_tfe_variable_test.go
- vendor/github.com/hashicorp/terraform-plugin-sdk/helper/customdiff/compose.go
- vendor/github.com/hashicorp/terraform-plugin-sdk/helper/customdiff/computed.go
- vendor/github.com/hashicorp/terraform-plugin-sdk/helper/customdiff/condition.go
- vendor/github.com/hashicorp/terraform-plugin-sdk/helper/customdiff/doc.go
- vendor/github.com/hashicorp/terraform-plugin-sdk/helper/customdiff/force_new.go
- vendor/github.com/hashicorp/terraform-plugin-sdk/helper/customdiff/validate.go
**Scenario:** A user creates a `tfe_variable` with `sensitive = true` but sets the wrong key. They go back later to set the correct key, changing it in place in the Terraform configuration.
**Expected:** The variable is updated
**Result:** An API error that causes the resource update to fail
```
Error: Error updating variable var-cM2eQjsuDNpYHtw3: Invalid Attribute
Key cannot be updated for a sensitive variable
```
I can imagine why this limitation exists for sensitive (i.e. transit-encrypted) values. ~While it's possible to update non-sensitive values in place, split behavior seems confusing and the code involved would be a lot more complex (i.e. conditionally calling `Delete` and `Create`). There's no way to tell a user that a delete + create is happening other than `ForceNew`.~ …
> variable: use ForceNew for key changes on sensitive variables

- tfe/resource_tfe_run_trigger.go
- tfe/resource_tfe_run_trigger_test.go
This PR adds retries for run trigger creation. Concurrently creating run triggers on a workspace results in an error—now those errors are considered retryable for 1 minute.
Closes #169
1. Create many run triggers for a given workspace
2. Attach them all in a single apply
I've added a new test that is able to reproduce this condition. When the test is run without the new retries, it fails with lock errors. In my initial test, 5/10 resources failed:
```
make testacc TESTARGS='-run TestAccTFERunTrigger_many'
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v -run TestAccTFERunTrigger_many -timeout 15m
?   	github.com/terraform-providers/terraform-provider-tfe	[no test files]
=== RUN   TestAccTFERunTrigger_many …
```
> run_trigger: retry when a "locked" error is returned

- website/docs/r/registry_module.html.markdown
The documentation currently has the name of at the top of the page as `tfe_registry_modules`, however, the resource name is `tfe_registry_module`. Removing the errant 's'.
> [tfe_registry_module] Docs: Remove errant 's' from resource name

- CHANGELOG.md
- tfe/data_source_oauth_client.go
- tfe/data_source_oauth_client_test.go
- tfe/provider.go
- website/docs/d/oauth_client.html.markdown
- website/tfe.erb
This is a new datasource that allows users to extract information from
existing oauth clients.
```
❯ TESTARGS='-run TestAccTFEOAuthClientDataSource_basic' make testacc
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v -run TestAccTFEOAuthClientDataSource_basic -timeout 15m
?       github.com/terraform-providers/terraform-provider-tfe   [no test files]
=== RUN   TestAccTFEOAuthClientDataSource_basic
--- PASS: TestAccTFEOAuthClientDataSource_basic (29.90s)
PASS
ok      github.com/terraform-providers/terraform-provider-tfe/tfe       30.846s
?       github.com/terraform-providers/terraform-provider-tfe/version   [no test files]
```
> New datasource: tfe_oauth_client

- go.mod
- go.sum
- tfe/data_source_workspace.go
- tfe/data_source_workspace_test.go
- tfe/resource_tfe_workspace.go
- tfe/resource_tfe_workspace_test.go
- vendor/github.com/hashicorp/go-tfe/README.md
- vendor/github.com/hashicorp/go-tfe/tfe.go
- vendor/github.com/hashicorp/go-tfe/workspace.go
- vendor/modules.txt
- website/docs/d/workspace.html.markdown
- website/docs/r/workspace.html.markdown
This change adds support for the `speculative_enabled` argument to `tfe_workspace`.
Fixes #211
The tests have been updated to test this in the same way that `file_triggers_enabled` is tested.
`file_triggers_enabled` also defaults to `true` during workspace creation and is thus quite comparable.
- [API documentation](https://www.terraform.io/docs/cloud/api/workspaces.html)
```
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v -run TestAccTFEWorkspace -timeout 15m
?   	github.com/terraform-providers/terraform-provider-tfe	[no test files]
=== RUN   TestAccTFEWorkspaceIDsDataSource_basic
--- PASS: TestAccTFEWorkspaceIDsDataSource_basic (10.96s)
=== RUN …
```
> Add speculative_enabled argument to tfe_workspace

- tfe/resource_tfe_workspace.go
While iterating over a trigger prefix list sometimes items can be nil.
We are now checking if conversion is possible instead of "blindly"
converting them and potentially causing a crash.
> Fix type conversion bug

- tfe/resource_tfe_workspace.go
- tfe/resource_tfe_workspace_test.go
Importing a workspace with a non-default branch fails to import the branch.
_Please run the full suite of acceptance tests locally and include the output here._
```
PASS tfe.TestAccTFEWorkspace_importVCSBranch (4.10s)
...
```
> Import branch

- tfe/resource_tfe_workspace.go
Hello.
This request fixes the one that can't get the branch name when importing the workspace.
As I wrote in Issue #216 , I have confirmed the phenomenon by the following method.
----
executed API...
```
$ curl \
>   --header "Authorization: Bearer $TOKEN" \
>   --header "Content-Type: application/vnd.api+json" \
>   https://app.terraform.io/api/v2/organizations/kuroseets/workspaces | jq
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100  2422    0  2422    0     0   3035      0 --:--:-- --:--:-- --:--:--  3031
{
"data": [
{
"id": "WORKSPACE_ID",
"type": "workspaces",
"attributes": {
"name": "terraform-provider-tfe-dev",
"auto-apply": false,
"created-at": "2020-08-22T02:01:02.485Z",
"environment": "default", …
```
> Fixed not being able to get VCS branch name when importing workspace

- tfe/resource_tfe_variable.go
Addresses https://github.com/terraform-providers/terraform-provider-tfe/issues/195
Configuration containing a TFE variable will fail if the workspace is destroyed in the UI. This change destroys the variable resource in state if the workspace it belongs to no longer exists.
_Delete this section if your change is not introducing a breaking change to the provider or a breaking change from the TFE API_
- [API …
> Set variable id to null if workspace id doesnt exist

- tfe/provider.go
- website/docs/index.html.markdown
This should solve #82, but as I don't have a pTFE install to test against it would be great if this can be tested by someone from support before merging this one.
> Add an option to skip certificate verifications

- GNUmakefile
- tfe/provider.go
- tfe/tfe_sweeper_test.go
Sweepers are used to cleanup after failed tests.
Because of the way data are modeled in the TF platform everything
depends on the organization. This means that in order to cleanup we
just need to delete the test organization and the rest of the
resources will be deleted automatically.
> Add test sweepers

- tfe/resource_tfe_team_access.go
I noticed this on a failed import:
```
Error: error retrieving workspace <org name> from organization <workspace name>: Error reading configuration of workspace <org name>/<workspace name>: resource not found
```
This log message is in the opposite order of the resource ID.  This PR inverts the refs in the log message to fix it.
I'm having a bit of trouble running the acceptance tests; not sure what's wrong, but I figured that this is small enough it might not matter.
> Invert org and workspace names

- tfe/resource_tfe_team_members_test.go
When Organization memberships were added, it placed the requirement on team memberships to first have a valid membership to the organization. The tests here were not updated at the time to do that, and the limitation remains. Instead of ignoring a failing acceptance test suite, let's actually skip these tests until that can be corrected.
> Skip TeamMembers tests

- tfe/data_source_oauth_client_test.go
- tfe/data_source_organization_membership_test.go
- tfe/data_source_ssh_key_test.go
- tfe/data_source_team_test.go
- tfe/data_source_workspace_ids_test.go
- tfe/data_source_workspace_test.go
- tfe/resource_tfe_notification_configuration_test.go
- tfe/resource_tfe_oauth_client_test.go
- tfe/resource_tfe_organization_membership_test.go
- tfe/resource_tfe_organization_test.go
- tfe/resource_tfe_organization_token_test.go
- tfe/resource_tfe_policy_set_parameter_test.go
- tfe/resource_tfe_policy_set_test.go
- tfe/resource_tfe_registry_module_test.go
- tfe/resource_tfe_run_trigger_test.go
- tfe/resource_tfe_sentinel_policy_test.go
- tfe/resource_tfe_ssh_key_test.go
- tfe/resource_tfe_team_access_test.go
- tfe/resource_tfe_team_member_test.go
- tfe/resource_tfe_team_members_test.go
- tfe/resource_tfe_team_organization_member_test.go
- tfe/resource_tfe_team_test.go
- tfe/resource_tfe_team_token_test.go
- tfe/resource_tfe_variable_test.go
- tfe/resource_tfe_workspace_test.go
We are adding a suffix to the org name for each test. That way we can
have multiple people running the acceptance tests on the same instance.
Also a potential panic mid-test does not require an immediate cleanup
since the next run will create a different org.
> Randomize org name

- tfe/resource_tfe_organization.go
- tfe/resource_tfe_organization_test.go
- website/docs/r/organization.html.markdown
The `tfe_organization` resource is missing an option to set cost estimation settings for its workspaces. 
The TFE API already supports setting this attribute: https://www.terraform.io/docs/cloud/api/organizations.html#request-body
1. Create a TFE organization without setting `cost_estimation_enabled`.
a. From my observations, TFE sets the default value to `true` if Cost Estimation is globally enabled through [TFE Admin Settings](https://www.terraform.io/docs/enterprise/admin/integration.html#cost-estimation-integration), and sets default to `false` if Cost Estimation is not globally enabled. This complicates checking the `cost_estimation_enabled` default value, so I did not include that in the tests.
2. Explicitly set `cost_estimation_enabled` to `true`, verify the change is made.
3. …
> Add `cost_estimation_enabled` to `tfe_organization` resource

- tfe/data_source_agent_pool.go
- tfe/data_source_agent_pool_test.go
- tfe/provider.go
- tfe/resource_tfe_agent_pool.go
- tfe/resource_tfe_agent_pool_test.go
- tfe/resource_tfe_workspace.go
- tfe/resource_tfe_workspace_test.go
- website/docs/d/agent_pool.html.markdown
- website/docs/r/agent_pool.html.markdown
- website/docs/r/workspace.html.markdown
- website/tfe.erb
This adds support for [Terraform Cloud Agents](https://www.terraform.io/docs/cloud/agents/index.html), now that [agent pools have a full resource lifecycle](https://www.terraform.io/docs/cloud/agents/index.html#managing-agent-pools) and can be managed via Terraform. Specifically this adds a `tfe_agent_pool` resource and datasource (https://www.terraform.io/docs/cloud/api/agents.html) and allows configuring them for use in a Terraform Cloud workspace with the new `execution-mode` attribute.
Closes #204 
* Agent pool management should behave as you expect (it's a simple resource)
* Workspace configuration with `execution_mode` and `agent_pool_id` should behave smoothly, allowing for continued use of the deprecated `operations` argument or a seamless switch to `execution_mode`. Their use …
> Add support for Terraform Cloud Agents

- CHANGELOG.md
Normally the release bot does this but it didn't this time, for whatever reason. The unreleased version is normally necessary for new releases to work properly so I'm fixing it. 
It is possible this isn't necessary anymore but either way, it is also helpful to have the next version so we can update the changelog in PRs as we go.
No need to test, just a changelog update
No need to run acceptance tests, just a changelog update.
> Update CHANGELOG.md with next unreleased version

- CHANGELOG.md
- tfe/data_source_workspace.go
- tfe/data_source_workspace_ids.go
- tfe/data_source_workspace_ids_test.go
- tfe/resource_tfe_notification_configuration.go
- tfe/resource_tfe_notification_configuration_test.go
- tfe/resource_tfe_policy_set.go
- tfe/resource_tfe_policy_set_test.go
- tfe/resource_tfe_run_trigger.go
- tfe/resource_tfe_run_trigger_test.go
- tfe/resource_tfe_team_access.go
- tfe/resource_tfe_variable.go
- tfe/resource_tfe_workspace.go
- website/docs/d/workspace_ids.html.markdown
- website/docs/r/notification_configuration.html.markdown
- website/docs/r/policy_set.html.markdown
- website/docs/r/run_trigger.html.markdown
This PR removes the deprecated `workspace_external_id` attributes from resources `tfe_notification_configuration` & `tfe_run_trigger`, and `workspace_external_ids` attribute from resource `tfe_policy_set`. 
**This is a breaking change. Please change your config to use `workspace_id`/`workspace_ids` before upgrading.** 
This PR also adds deprecation warnings to the `external_id` attribute for resource `tfe_workspace`, the `external_id` attribute for data source `tfe_workspace`, and the `external_ids` attribute for data source `tfe_workspace_ids`. 
It also adds a little bit of extra context to the `DeprecationMessage` on `d/tfe_workspace` and `d/tfe_workspace_ids` [because that context has gone missing in V2 of the SDK](https://github.com/hashicorp/terraform-plugin-sdk/issues/660). 
* …
> Remove deprecated workspace_external_id/workspace_external_ids attributes and deprecate external_id attribute

- CHANGELOG.md
- go.mod
- go.sum
- tfe/provider.go
- tfe/resource_tfe_agent_token.go
- tfe/resource_tfe_agent_token_test.go
- website/docs/r/agent_token.html.markdown
- website/tfe.erb
This PR adds a new tfe_agent_token resource that can be used to create agent tokens using the [Agent Tokens API](https://www.terraform.io/docs/cloud/api/agent-tokens.html) endpoint.
This PR depends on PR https://github.com/hashicorp/go-tfe/pull/169 in the hashicorp/go-tfe repository, which added the files agent_token.go and associated agent_token_test.go to interact with the above API endpoint.
Closes #250.
The new tfe_agent_token resource can be tested with this command after following the setup instructions in TESTS.md:
```
TESTARGS="-run TestAccTFEAgentToken" make testacc
```
However, testing prior to the merging of https://github.com/hashicorp/go-tfe/pull/169 and issuing a new release of go-tfe would require you to build go-tfe locally from …
> Add new resource tfe_agent_token

- .travis.yml
- GNUmakefile
This make target from the website project was dropped in https://github.com/hashicorp/terraform-website/commit/6d41be434cf85392bc9de773d8a5a8d571a195ad and is causing a failing Travis job.
> Drop website-test make target

- CHANGELOG.md
- tfe/data_source_ip_ranges.go
- tfe/data_source_ip_ranges_test.go
- tfe/provider.go
- website/docs/d/ip_ranges.html.markdown
- website/tfe.erb
Adds a new `tfe_ip_ranges` datasource to fetch a list of Terraform Cloud and Enterprise's IP ranges from the [IP Ranges API](https://www.terraform.io/docs/cloud/api/ip-ranges.html).
```
» TF_ACC=1 go test -v ./tfe -timeout=30m -run TestAccTFEIPRanges
=== RUN   TestAccTFEIPRangesDataSource_basic
--- PASS: TestAccTFEIPRangesDataSource_basic (4.73s)
PASS
ok      github.com/hashicorp/terraform-provider-tfe/tfe (cached)
```
> Add IP Ranges datasource

- website/docs/d/workspace.html.markdown
- website/docs/r/workspace.html.markdown
Just some additional clarification on this setting and why the default here in the provider is the opposite of the API default.
> [DOCS] Some addition clarification on 'queue_all_runs'

- go.sum
- tfe/data_source_workspace.go
- tfe/data_source_workspace_test.go
- tfe/resource_tfe_workspace.go
- tfe/resource_tfe_workspace_test.go
* Requires go-tfe update
Adds description to workspace 
- https://github.com/hashicorp/go-tfe/issues/170
https://www.terraform.io/docs/cloud/api/workspaces.html#request-body
data.attributes.description | string | (nothing) | A description for the workspace.
-- | -- | -- | --
Required in create and read
> Adds description parameter to TFE Workspace

- go.mod
- go.sum
- tfe/client_mock.go
Lots of changes and a few regressions fixed throughout v0.13.x as we updated the underlying
`jsonapi` package that the client depends on.
Client changelog:
```
ENHANCEMENTS
* Add support for the new remote state consumers API to restrict inter-workspace data sharing within
* an organization (#201, #205)
* Add Manage Policy Overrides permission (#198)
* Add support for fetching a plan's JSON output (#187)
BUG FIXES
* URL encode the workspace ID when listing variables (#207)
* Revert Enforcement type changes (#211). A regression was introduced in the form of backwards
* incompatible type changes in 0.13.1. Note that this change was also included in a backported release, [v0.13.3](https://github.com/hashicorp/go-tfe/releases/tag/v0.13.3). 
```
> Update go-tfe to v0.14.0

- tfe/resource_tfe_team.go
- tfe/resource_tfe_team_test.go
- website/docs/r/team.html.markdown
A new permission, `Manage Policy Overrides` is being added to the `Organization Access` for teams. This PR adds the field as required.
- [go-tfe PR](https://github.com/hashicorp/go-tfe/pull/198)
- [go-tfe documentation](https://pkg.go.dev/github.com/hashicorp/go-tfe#OrganizationAccess)
- [API documentation PR](https://github.com/hashicorp/terraform-website/pull/1667)
- [API documentation](https://www.terraform.io/docs/cloud/users-teams-organizations/permissions.html#organization-permissions)
> Add Manage Policy Overrides permission

- CHANGELOG.md
- tfe/data_source_workspace.go
- tfe/data_source_workspace_ids.go
- tfe/data_source_workspace_ids_test.go
- tfe/data_source_workspace_test.go
- tfe/resource_tfe_workspace.go
- website/docs/d/workspace_ids.html.markdown
This PR removes the deprecated `external_id` attribute from resource `tfe_workspace`, the `external_id` attribute from data source `tfe_workspace`, and the `external_ids` attribute from data source `tfe_workspace_ids`.  
**This is a breaking change. Please change your config to use `id`/`ids` before upgrading.** 
* `tfe_workspace` - The deprecated `external_id` attribute has been removed. If you are still using this attribute, you will get errors. You should use `id` instead.
* `tfe_workspace_ids` - The deprecated `external_ids` attribute has been removed. If you are still using this attribute, you will get errors. You should use `ids` instead.
* `tfe_workspace` - The deprecated `external_id` attribute has been removed. If you are still using this attribute, you will get errors. You …
> Remove deprecated external_id/external_ids attributes

- tfe/resource_tfe_workspace_test.go
In a unfortunate twist of fate and unbelievable timing, the attribute in state that this test function was depending on was just ripped out from underneath it in the deprecation removals of #295  😆 Use `id`, not `external_id`, which is now removed.
CI should pass.
> Fix remote state consumer tests

- tfe/resource_tfe_organization.go
- tfe/resource_tfe_organization_test.go
The TFE API ignores case when specifying a `tfe_organization`'s `name` attribute. This configures the provider to suppress the diff when the `name` has changed but the value is equal when case is ignored.
See #299
1.  Declare a `tfe_organization`
1.  `terraform apply`
1.  Update the case of the `tfe_organization`'s name
1.  `terraform plan`
The plan will include the replace of the `tfe_organization`.
* [API docs](https://www.terraform.io/docs/cloud/api/organizations.html): these don't mention case handling
_Please run the full suite of acceptance tests locally and include the output here._
```
$ make testacc TESTARGS='-run TestAccTFEOrganization_'
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v -run TestAccTFEOrganization_ …
```
> organization: ignore diffs in name case

- CHANGELOG.md
The addition of remote state consumer functionality makes version r/tfe_workspace and d/tfe_workspace in version 0.25.0 incompatible with TFE versions older than v202104-1. We will be releasing a patch fix soon to pin the provider to specific TFE versions but in the meantime, this is helpful context to have in the changelog.
1. Make sure the changelog entries make sense and the doc updates make sense.
- [Related PR](https://github.com/hashicorp/terraform-provider-tfe/pull/292)
Didn't run these since I didn't make changes to code covered by these tests.
> Update CHANGELOG.md to note incompatibility with older TFE versions

- CHANGELOG.md
- tfe/client_mock.go
- tfe/resource_tfe_team_access_migrate_test.go
- tfe/resource_tfe_variable_migrate_test.go
- tfe/resource_tfe_workspace.go
- tfe/testing.go
- tfe/workspace_helpers.go
- tfe/workspace_helpers_test.go
- website/docs/d/workspace.html.markdown
- website/docs/r/workspace.html.markdown
In v0.25.0, a regression was introduced when adding the new remote state consumers feature. Unlike other relationships in the provider - which are serialized in the same original resource document - remote state consumers on a workspace only exist at a separate endpoint which must be read. When the endpoint can't be read in the case of a preexisting Terraform Enterprise installation without the feature, it causes a failure when doing anything with the tfe_workspace resource.
An ideal scenario would be for a version check to determine whether a call should be made - but the current tooling here is minimal. Instead, we apply the following heuristic to make it backwards compatible for TFE:
If a call to the remote state consumers endpoint fails and is a 404 Not Found, assume that the only …
> Fix remote state consumers compatibility for Terraform Enterprise

- website/docs/r/workspace.html.markdown
The argument is [supported](https://github.com/hashicorp/terraform-provider-tfe/blob/1a85ccb03625b26e7711015ecbb39519b4766d03/tfe/resource_tfe_workspace.go#L381) but not documented.
N/A
- [Existing support for the argument in the code](https://github.com/hashicorp/terraform-provider-tfe/blob/1a85ccb03625b26e7711015ecbb39519b4766d03/tfe/resource_tfe_workspace.go#L381)
- [API documentation](https://www.terraform.io/docs/cloud/api/workspaces.html#request-body)
N/A
> Add description argument to tfe_workspace

- CHANGELOG.md
- tfe/data_source_workspace.go
Fixes an issue where the `tfe_workspace` data source would error when used with a version of Terraform Enterprise older than v20210401-1.
- [PR that added the remote state consumer functionality](https://github.com/hashicorp/terraform-provider-tfe/pull/292)
- [PR that added a fix for the `tfe_workspace` resource](https://github.com/hashicorp/terraform-provider-tfe/pull/303)
> Handle remote state consumer 404s for workspace data source

- TESTS.md
- tfe/data_source_agent_pool_test.go
- tfe/data_source_ip_ranges_test.go
- tfe/resource_tfe_agent_pool_test.go
- tfe/resource_tfe_agent_token_test.go
- tfe/resource_tfe_team_member_test.go
- tfe/resource_tfe_workspace_test.go
- tfe/testing.go
When running tests against TFE to prep for a release, it's easy to miss genuine failures amid the flurry of tests that _always_ fail for TFE (because they're testing Terraform-Cloud-only features).
This adds a `ENABLE_TFE` environment variable (to echo the go-tfe env var) that, when set to 1, will skip tests known to fail in TFE.
1. Run the tests against the most recent TFE release and confirm that they pass.
> add ability to skip tests for TFE

- go.mod
- go.sum
Changelog: https://github.com/hashicorp/go-tfe/releases/tag/v0.15.0
Closes #315
> Bump go-tfe to v0.15.0

- website/docs/r/workspace.html.markdown
Update description of vcs_repo argument for workspace resource to make it clearer when using Azure DevOps repos.
> [DOCS] Update description of vcs_repo argument for workspace resource

- .github/CODE_OF_CONDUCT.md
- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/pull_request_template.md
Adds the usual HashiCorp Community Guidelines CoC + an overhaul of issue templates. The issue templates are [similar to Terraform CLI's](https://github.com/hashicorp/terraform/tree/main/.github/ISSUE_TEMPLATE).
> Issue/PR templates adjustments, CoC

- tfe/data_source_organizations.go
- website/docs/d/organizations.html.markdown
In #320, two a data source for listing all organizations was added. That data source returns the organizations that the user (token) has access to. 
This PR augments that data source. We add a boolean field `admin` that determines if we should retrieve the organizations from using the [Admin Organizations endpoint](https://www.terraform.io/docs/cloud/api/admin/organizations.html#list-all-organizations) or the [Organizationsendpoint](https://www.terraform.io/docs/cloud/api/organizations.html#list-organizations) will be used.
Added docs.
This can only be properly tested with access to Site Admin on your Terraform Enterprise instance. 
The testing plan is as follows:
Create a terraform config using the `tfe` provider, and add this bit:
```
data "tfe_organizations" "orgs" {
admin = true 
} …
```
> Add Admin Organizations to data source organizations

- go.mod
- go.sum
- tfe/client_mock.go
- tfe/data_source_workspace.go
- tfe/data_source_workspace_test.go
- tfe/resource_tfe_workspace.go
- tfe/resource_tfe_workspace_test.go
- website/docs/d/workspace.html.markdown
- website/docs/r/workspace.html.markdown
Add support for enabling the new redesigned apply UI for a workspace (`structured_run_output_enabled`). See #327 and https://github.com/hashicorp/go-tfe/pull/233.
1. Ensure that toggling `structured_run_output_enabled` on a workspace changes the setting appropriately.
[blog post](https://www.hashicorp.com/blog/new-apply-user-interface-for-terraform-cloud)
> tfe_workspace: add structured_run_output_enabled

- go.mod
[Golang 1.17 is out](https://blog.golang.org/go1.17). Ran `go mod tidy` after updating the version.
All tests pass
- [Go 1.17 announcement](https://blog.golang.org/go1.17)
- [Go 1.17 release notes](https://golang.org/doc/go1.17)
> Update Golang from 1.16 to 1.17

- website/docs/d/outputs.html.markdown
Oop! The last commit in #344 changed this resource type name to an example one, but the intention here was to use the real resource of [`random_id`](https://registry.terraform.io/providers/hashicorp/random/latest/docs/resources/id), a common one used.
> Outputs example doc typo

- CHANGELOG.md
- README.md
- go.mod
- go.sum
- website/docs/index.html.markdown
This updates the changelog in preparation for v0.26.0. 
All changes since last release: https://github.com/hashicorp/terraform-provider-tfe/compare/v0.25.3...main
There was a go mod prompt because some packages should not be `indirect` (probably a mistake from a previous PR), so ran `go mod tidy` and included changes here.
> Update changelog for v0.26.0

- .circleci/config.yml
- GNUmakefile
- tfe/data_source_outputs_test.go
- tfe/resource_tfe_policy_set_test.go
- tfe/testing.go
For all of our existing tests, we rely on the [terraform-plug-sdk/helpers](https://github.com/hashicorp/terraform-plugin-sdk/blob/fa81bfcad90ed4e2b688d0070390fd311a5449df/helper/resource/testing.go#L523) to test the provider. Any test that has this is skipped if `TF_ACC=1` is not set. 
These tests are run as `make testacc` which ensures that `TF_ACC` is set, and therefore the tests run using this make target. 
But in our release process, we run `make test`, which does not set `TF_ACC`. A previous PR introduced a few tests that had to rely on some environment variables set as part of acceptance set.
This PR introduces a `skipIfUnitTest` to ensure that these tests are not run unless it is an acceptance test. 
I also added a step in CI to run `make test` so we can catch these things before …
> Fix make test and skipIFUnitTest

- tfe/plugin_provider.go
- tfe/plugin_provider_test.go
- tfe/provider.go
- tfe/provider_test.go
Closes #353 
The 0.26.0 release introduced features with #344 that required muxing the existing provider built with [terraform-plugin-sdk](https://github.com/hashicorp/terraform-plugin-sdk) and another one built with a lower level provider package, [terraform-plugin-go](https://github.com/hashicorp/terraform-plugin-go). What this means is that there are two providers which must interpret the same configuration/settings, in one. 
The SDK schema [usually provides a default hostname value with DefaultFunc](https://github.com/hashicorp/terraform-provider-tfe/blob/7bb6b0f0b1717c5bcd722d14940ca6c93f0c8874/tfe/provider.go#L54), and unfortunately this behavior was not translated to an equivalent in new lower level provider now muxed in, causing a regression where unless a hostname is explicitly …
> Fix 0.26.0 configuration regressions

- .circleci/config.yml
- tfe/data_source_outputs_test.go
- tfe/data_source_workspace_ids.go
- tfe/data_source_workspace_ids_test.go
In the recent [v0.26.0 release](https://github.com/hashicorp/terraform-provider-tfe/blob/main/CHANGELOG.md#0260-september-02-2021), there was a regression regarding the `names` attribute in the data source `workspace_ids`. 
Prior to v0.26.0, `names` was required at the schema level. But this was changed with the addition of `tag_names` and neither was required **at the schema level** but the user was presented [with an error](https://github.com/hashicorp/terraform-provider-tfe/blob/main/tfe/data_source_workspace_ids.go#L54-L56) when the read function `dataSourceTFEWorkspaceIDs` was called. 
This PR changes the `names` field to be optional but uses the [AtLeastOneOf](https://pkg.go.dev/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema#Schema.AtLeastOneOf) schema helper which …
> d/workspace_ids use AtLeastOneOf to ensure names/tag_names is present

- go.mod
- go.sum
- tfe/data_source_organization.go
- tfe/data_source_organization_test.go
- tfe/resource_tfe_organization.go
- tfe/resource_tfe_organization_test.go
- website/docs/d/organization.html.markdown
- website/docs/r/organization.html.markdown
New API feature parity
Given the org resource:
```
resource "tfe_organization" "foo" {
name                    = "foo"
email                    = "bcroft@hashicorp.com"
send_passing_statuses_for_untriggered_speculative_plans = false
}
```
`send_passing_statuses_for_untriggered_speculative_plans` is true by default so this resource should change that to false
- [API documentation](https://github.com/hashicorp/terraform-website/pull/1919)
```
$ TESTARGS="-v -run TestAccTFEOrganizationDataSource" make testacc
==> Checking that …
```
> new org attribute: send_passing_statuses_for_untriggered_speculative_plans

- website/docs/r/workspace.html.markdown
To update documentation on clarify on the character restrictions when adding a new tag to a workspace.
When creating tags like 
```
tag_names = [
"category:x-force",
"book_title:x-force"
]
```
I get the error `Error adding tags to workspace ws-xxx: invalid attribute Tags must only contain letters, numbers or colons`
To make clear to future users, it might be better to clarify that tags must conform with the character restrictions
> Clarify on character requirements of tag names.

- tfe/resource_tfe_workspace.go
- tfe/resource_tfe_workspace_test.go
- website/docs/r/workspace.html.markdown
This PR adds support for importing workspaces using a `<ORGANIZATION NAME>/<WORKSPACE NAME>` nested combo. You can still pass a workspace external id.
An example import command looks as follows:
```sh
terraform import tfe_workspace.test my-org-name/my-wkspace-name
```
**To run acceptance tests**:
```sh
TESTARGS="-run TestAccTFEWorkspace_import" make testacc
```
**To smoke test**:
1. Create a Terraform configuration file, setting the tfe provider and the workspace resource we'll import to.
```hcl
hostname = "my-tfe-host"
token = "my-tfe-token
}
resource "tfe_workspace" "test" {}
```
Ensure you have the dev overrides set to the compiled binary of this PR in your `go/bin`. 
2. Create an organization in your TFE host and workspace.
3. Import!
```sh
terraform import …
```
> Allow Importing workspaces using workspace name

- tfe/resource_tfe_terraform_version.go
- tfe/resource_tfe_terraform_version_test.go
- tfe/tool_helpers.go
- website/docs/r/policy_set.html.markdown
- website/docs/r/terraform_version.html.markdown
This is a very simple PR that introduces the ability to use a Terraform version number as an alternative import ID when importing Terraform versions. I'm not particularly proud of the implementation to search for a tool version that matches the version specified, but it's currently an API limitation that doesn't allow querying/filtering Terraform versions by version. It effectively loops through the [List Terraform Versions](https://www.terraform.io/cloud-docs/api-docs/admin/terraform-versions#list-all-terraform-versions) endpoint until it finds a match. If no match is found, the import will fail.
1.  Ensure you have a `.tfrc` file that overrides the Terraform provider to your locally compiled binary. It should look something like this:
```
provider_installation {
dev_overrides { …
```
> Import Terraform Versions using version number

- website/docs/r/oauth_client.html.markdown
Documentation is lacking BitBucket Providers this change adds in missing Service Providers for bitbucket.
Documentation Only 
Provider: https://github.com/hashicorp/terraform-provider-tfe/blob/main/tfe/resource_tfe_oauth_client.go#L87
Library: https://github.com/hashicorp/go-tfe/blob/main/oauth_client.go#L48
> Add in Service Providers for BitBucket in Documentation

- tfe/resource_tfe_workspace_test.go
Test fixes only: These names were used as proxies for a successful applies, I think, so I just moved the strings to the description field
> fix can't rename workspace while run is being performed

- go.mod
- go.sum
- tfe/tool_helpers.go
This is a simple PR that makes use of the newly added query params to filter a Terraform version when importing a Terraform version by version number. This will drastically reduce the calls needed to find the tool version ID. 
This PR also bumps the go-tfe version to `0.24` which includes the query params as list opts. 
- [Related PR](https://github.com/hashicorp/terraform-provider-tfe/pull/408)
> Optimize Terraform Version Importer func

- tfe/resource_tfe_terraform_version.go
- tfe/resource_tfe_terraform_version_test.go
- website/docs/r/terraform_version.html.markdown
This PR adds two new arguments supported by the [Admin Terraform Versions API](https://www.terraform.io/cloud-docs/api-docs/admin/terraform-versions):
- `deprecated`: (Optional) Whether or not this version of Terraform is deprecated. Defaults to "false".
- `deprecated_reason`: (Optional) Additional context about why a version of Terraform is deprecated. Defaults to "null" unless `deprecated` is true.
```sh
TESTARGS="-run TestAccTFETerraformVersion" make testacc
```
1. Pull the changes from this PR locally and compile the provider into `$GOPATH/bin`.
2. Create a [development overrides file](https://www.terraform.io/language/files/override) and override the official tfe provider to point to the compiled binary in `$GOPATH/bin`
3. Create a new Terraform configuration using the newly added …
> Add deprecated arguments to Terraform version resource

- tfe/data_source_workspace.go
- tfe/data_source_workspace_test.go
The memory leak described in #407 is actually a workspace data source bug where we always fetch all remote_state_consumer_ids, even if the workspace data source is global. The API happily enumerates all other workspaces in this case. If you have many pages of workspaces, this could take a very long time to plan.
```
$ TFE_TOKEN="$(tfc_local_token)" TFE_HOSTNAME="$(tfc_local_hostname)" TF_ACC=1 go test ./... -v -tags=integration -run TestAccTFEWorkspaceDataSource …
```
> fix: don't populate data.remote_state_consumer_ids if global

- tfe/resource_tfe_team.go
This PR resolves [Issue 171](https://github.com/hashicorp/terraform-provider-tfe/issues/171). Previously when a User on the Free Tier tried to create a team using the tfe provider, the CLI would return an error message like : `Error: Error creating team my-team-name for organization raoul-staging: resource not found`. This error does not explain to the user that they cannot create a team because the Free tier does not have the proper entitlements. 
These changes check entitlements after the `ErrResourceNotFound` error and if there is an error surfaces an error message like: `Error creating team my-team-name for organization raoul-staging: missing entitlements to create teams` 
1.  Run tfe provider locally against staging.
1.  Create an Organization and set the Feature Set to Free tier.
1. …
> adds entitlment error message for creating Teams

- tfe/data_source_workspace_ids.go
- tfe/data_source_workspace_ids_test.go
This is a really simple fix that closes #409 by preventing the user to set the `names` argument for `tfe_data_source_workspace_ids` to an array of empty strings or an array that contains empty strings. The reason for this is the plugin sdk fetches empty strings as `nil` values, causing any type casting operations to panic. 
There is an alternative up for discussion, let's say the user provides `["wkspace1", "", "wkspace2"]`, should the plugin read this as `["wkspace1", "wkspace2"]` omitting any entries that are `nil`? This might be a better alternative as `[]` is a valid assignment and therefore omitting entries that are nil (in a case where all entries are nil) would effectively be the same as `[]`.
**Update**: Decided to go with the alternative solution
1.  In order to test ensure you …
> Fixing plugin crash when providing empty strings to argument

- tfe/resource_tfe_workspace.go
- tfe/resource_tfe_workspace_test.go
Previously, these attributes would not be added to the state but be defaulted by the API, which would be displayed as a drift
1. Use this config to create a new workspace:
```
hostname = "HOSTNAME"
}
terraform {
required_providers {
tfe = {
version = "~> 0.27.0"
}
}
}
resource "tfe_workspace" "test" {
name               = "my-cool-workspace"
organization       = "hashicorp"
global_remote_state = false
}
```
After applying this, change the name of the workspace and plan the change.
Previously, you'd see this warning:
```
Terraform detected the following changes made outside of Terraform since the last "terraform apply":
~ resource "tfe_workspace" "test" {
id                            = "ws-RGzPjmdTVvADZpdb"
name                          = "my-cool-workspace"
+ …
```
> fix: mark these attributes as computed because they are defaulted as lists

- tfe/tool_helpers.go
Older TFE installations don't support the `filter[version]` query param. This commit updates
the importer function to fallback to looping through versions to find a match should the API
not support the filter query param.
> Backwards compatibility fix for importing TF versions by number

- .circleci/config.yml
Update CI docker image to `cimg/go:X.X.XX` from `circleci/docker`
For more on this topic:
https://circleci.com/developer/images/image/cimg/go
https://discuss.circleci.com/t/legacy-convenience-image-deprecation/41034
> Update docker image to use cimg namespace

- go.mod
- go.sum
- tfe/resource_tfe_ssh_key.go
- tfe/resource_tfe_ssh_key_test.go
- tfe/resource_tfe_team.go
- tfe/resource_tfe_team_test.go
- website/docs/r/team.html.markdown
Re-opening #431 with breaking changes fixed
> registry permissions + upgrade breaking changes

- CHANGELOG.md
- website/docs/r/variable_set.html.markdown
The argument is named workspace_ids, not workspaces
https://github.com/hashicorp/terraform-provider-tfe/blob/main/tfe/resource_tfe_variable_set.go#L48-L53
> Docs: Fix example for tfe_variable_set with workspace_ids

- website/docs/r/variable_set.html.markdown
The argument is named `variable_set_id` not `variable_set`
https://github.com/kaefferlein/terraform-provider-tfe/blob/main/tfe/resource_tfe_variable.go#L88
> [Docs] Fix example for tfe_variable_set with variable_set_id

- website/docs/r/variable_set.html.markdown
The provider will raise an error if you have both `global` and `workspace_ids` arguments set, regardless if `global` is set to `false` as coded here in the provider itself: `https://github.com/hashicorp/terraform-provider-tfe/blob/main/tfe/resource_tfe_variable_set.go#L39`
Locally we did this
```
data "tfe_workspace_ids" "test" {
names = ["*"]
organization = data.tfe_organization.this.name
}
resource "tfe_variable_set" "test" {
name         = "Test Variable Set"
description  = "Test variable set applied to all workspaces."
global       = false
organization = data.tfe_organization.this.name
workspace_ids = values(data.tfe_workspace_ids.test.ids)
}
```
Resulting in this error
```
│ Error: Conflicting configuration arguments
│ 
│   with tfe_variable_set.test,
│   on variable-set-test.tf line …
```
> Update Variable Sets doc about argument conflicts

- website/docs/r/variable_set.html.markdown
Fix example creating a variable set that applies workspace_ids data
`data.tfe_workspace_ids.this.ids`  returns a `map[WS name] = ws-id` 
so to use that as input for `tfe_variable_set.workspace_ids` only values are needed 
documentation update
Documentation website should be updated and new example showed
> Fix example creating variable set that applies workspace_ids data

- tfe/logging.go
- tfe/provider.go
Replaces the SDK logging transport with a similar logger that redacts certain headers ("authorization:", "proxy-authorization:") from logging output.
While we wait for the plugin SDK to implement a more robust or configurable solution for the issue of logging sensitive tokens in TRACE and DEBUG levels, we can implement a quick solution in this provider.
1.  Plan any configuration that uses TFE resources using the TF_LOG=TRACE variable
2. Notice that authorization tokens are now redacted from log output made by terraform:
Example output:
```
2022-04-21T12:42:13.983-0600 [DEBUG] provider.terraform-provider-tfe: 2022/04/21 12:42:13 [DEBUG] TFE API Request Details:
2022-04-21T12:42:13.983-0600 [DEBUG] provider.terraform-provider-tfe: ---[ REQUEST ]--------------------------------------- …
```
> fix(provider): redact sensitive headers from HTTP logging

- tfe/credentials.go
- tfe/plugin_provider_test.go
- tfe/provider.go
- tfe/provider_test.go
- website/docs/index.html.markdown
This is a companion PR to a change to terraform that adds host specific env svc creds. It should be possible for tfe to use the same method when specifying credentials for a particular tfc host.
0. Build this code `go build -o terraform-provider-tfe` and update your CLI config to override it (see below)
1. Don't specify a token in your tfe provider configuration block
2. Remove or modify your CLI configuration credentials for the test host
3. Run terraform using an env var  with the correct token value (see below)
4. This should work on Terraform 1.1 with local state. It would also work in latest Terraform built from source
I used this config:
```
hostname = "YOURHOST.com"
}
resource "tfe_organization" "test-organization" {
name  = "my-org-name"
email = …
```
> allow TF_TOKEN_... variables to specify host-specific credentials

- website/docs/r/variable.html.markdown
- website/docs/r/variable_set.html.markdown
Hello! I'm not sure that it's possible to have the same resource name for the same resource types _[in the same module?]_.
```
terraform plan
╷
│ Error: Duplicate resource "tfe_variable" configuration
│
│   on variable_set.tf line 16:
│   16: resource "tfe_variable" "test" {
│
│ A tfe_variable resource named "test" was already declared at variable_set.tf:8,1-31. Resource names must be unique per type in each module.
╵
```
Copy paste the snippet, substitute the necessary values and try `terraform plan`.
```terraform
Terraform …
```
> Fix resource name in variable_set examples

- .github/pull_request_template.md
Some of the information for contributing to this project is somewhat buried at
the end of the README which makes it easy to forget and difficult to discover
for new people.  This commit adds a simple task list with links to further
instructions for updating the changelog and documentation.
> Add helpful tasks to PR template

- .github/workflows/lint.yml
- .golangci.yml
- README.md
TFE-CHANGELOG: no-impact <msg>
Currently our CI pipeline for the provider does not run any form of linters. This PR adds linters and configuration settings.
A Github action that runs `golangci-lint` is also added.
New linters added are:
-       errorlint #https://github.com/polyfloyd/go-errorlint
-       gosec #https://github.com/securego/gosec
-       predeclared #https://github.com/nishanths/predeclared
-       unconvert #https://github.com/mdempsky/unconvert
-       wrapcheck #https://github.com/tomarrell/wrapcheck
**Note:** Some lint warnings have been listed under `issues` tag because fixing them in one PR would be too large. This way, each issue can be discussed and fixed transparently on it's own ticket. This dependent PR, …
> Add linter workflow and config

- CHANGELOG.md
- tfe/resource_tfe_team.go
- tfe/resource_tfe_team_test.go
- website/docs/r/team.html.markdown
Run Tasks added a new Organizational access type called `manage_run_tasks`.
This commit updates the organization_access of Teams to include this new
access type.
Acceptance tests are updated in the PR
- [go-tfe documentation](https://github.com/hashicorp/go-tfe/blob/main/team.go#L67)
N/A - Run as part of CI
> Add manage_run_tasks to Org. Team Access

- website/docs/r/workspace.html.markdown
this note was for when agents were TFC only. now that agents exist on TFE this note can be removed
DOC only
https://www.terraform.io/enterprise/admin/agents-on-tfe
> Removing note "TFC Only" - doc only

- CHANGELOG.md
- tfe/resource_tfe_workspace_migrate.go
- website/docs/r/workspace.html.markdown
Change default for `file_triggers_enabled` to false.
Why?
Current default is wrong and we're having a clause on the TFC side to account for this behavior.
New trigger types, e.g. tag based triggering, will depend on this field being set to `false`. We'll introduce the conflict between the new fields and `file_triggers_enabled`.
_Remember to:_
1. Define a new workspace without `file_triggers_enabled`
2. Newly created workspace should have the field set to `false`
> Change default for `file_triggers_enabled` to false

- CHANGELOG.md
- tfe/resource_tfe_workspace.go
This is a fix that closes #513, where a panic was occurring during an unhandled type conversion error. This is a similar problem to a fix I had done a while back (#421). To reiterate: the culprit is `[""]`. The SDK casts this value as `[nil]`, which then induces the panic whenever you try to typecast `nil` to `string`. 
For this particular issue you'll notice that initially setting `trigger_prefixes = [""]` **will work**. This is because the Create method will handle type conversion errors, as seen here:
https://github.com/hashicorp/terraform-provider-tfe/blob/59a346f8cd271712bbf22a2c508c5dc4fc940621/tfe/resource_tfe_workspace.go#L253-L259
The problem was the Update function _did not_ handle type conversion errors:
https://github.com/hashicorp/terraform-provider-tfe/blob/59a346f8cd271712bb …
> Fix panic interface conversion

- CHANGELOG.md
- tfe/data_source_team_access.go
- tfe/data_source_team_access_test.go
- tfe/resource_tfe_team_access.go
- tfe/resource_tfe_team_access_test.go
- website/docs/d/team_access.html.markdown
- website/docs/r/team_access.html.markdown
Run Tasks has added a new `run_tasks` custom permission to Team
Workspace access.  This commit adds this new permission to the
Team Access object (both resource and data) and adds acceptance
tests for both objects.
N/A  Added acceptance tests
- [go-tfe documentation](https://github.com/hashicorp/go-tfe/blob/main/team_access.go#L101)
N/A It'll be in the CI tests
> Add run_tasks permission to Team Access

- CHANGELOG.md
- tfe/data_source_outputs_test.go
- tfe/data_source_team.go
This fallback method for selecting a team by name will pick the wrong team when doing a linear search
Fixes https://github.com/hashicorp/terraform-provider-tfe/issues/528 - see issue details for example config
> fix(d/team): the wrong team can be picked within the "filter by name" fallback

- .gitignore
Update the `.gitignore` to ignore the `terraform-provider-tfe` binary so we don't accidentally check it in.
_Remember to:_
> Ignore the terraform-provider-tfe binary

- .github/workflows/lint.yml
Fixes #504. Adds a new flag to `golangci-lint`, `--out-${NO_FUTURE}format`, so that the lint output can play nicely with the Github actions output.
> Show file name and line numbers for linter error output on Github

- CHANGELOG.md
- tfe/data_source_workspace_ids.go
- tfe/data_source_workspace_ids_test.go
- website/docs/d/workspace_ids.html.markdown
Currently the list of Workspaces within an Organization can be filtered with `tag_names` to include. This PR adds the ability to exclude workspaces by tags using the`exclude_tags` parameter.
See usecase here: https://github.com/hashicorp/terraform-provider-tfe/issues/393
_Remember to:_
1. Create an organization
1.  Create workspaces with tags within the organization
1.  Filtering workspaces using the `exclude_tags` options, should list all matching workspaces excluding those with the excluded tags.
1.  See example block below:
``` …
```
> Add exclude_tags to data_source_workspace_ids

- CHANGELOG.md
- go.mod
- go.sum
- tfe/data_source_agent_pool.go
Once agent pool filtering is enabled (currently off in production behind the `remove-agent-pool-limit` feature flag) we can filter agent pool list requests by agent pool name. This improves performance of the agent pool data source when the organization has >20 agent pools by reducing the number of API calls we need to make in order to loop through all of the pages of agent pools
1.  Set up a TFC organization with >20 agent pools, and a terraform config with a data source matching one of those agent pools
1.  Verify that with the `remove-agent-pool-limit` feature flag off, the data source resolves the agent pool
2. Verify that with the `remove-agent-pool-limit` feature flag on, the data source resolves the agent pool even faster
-  The difference for me, against an org with ~1100 agent …
> Use filtering to improve performance of agent pool data source

- CHANGELOG.md
- tfe/logging.go
This PR stems from API behaviors returning a 404 when a token is invalid. In this case, the customer was reporting a "successful" deletion of a registry module when using an organization token. Even though Terraform recognizes a successful apply, the module was not deleted.  The culprit?
https://github.com/hashicorp/terraform-provider-tfe/blob/3804563b40eac5cec533fff11058227eebfc900d/tfe/resource_tfe_registry_module.go#L170-L175
The error check `if err == ErrResourceNotFound { return nil }` is quite common throughout the provider, the assumption being the 404 explicitly states the resource no longer exists. This is not the case because if we look at the [API Docs](https://www.terraform.io/cloud-docs/api-docs/private-registry/modules#delete-a-module), we find we can receive a 404 if I am …
> Log warnings on 404 responses

- CHANGELOG.md
- tfe/resource_tfe_organization.go
- tfe/resource_tfe_organization_test.go
- website/docs/r/organization.html.markdown
Supporting the new feature that was released in the July TFE release.
Here's [a link to the slack thread](https://hashicorp.slack.com/archives/C01BR9FR8KZ/p1652808925041049) where this feature was discussed.
1.  Spin up instance of TFE
2. Attempt to set `workspace_limit` via the organization resource.
3. Attempt to unset `workspace_limit` via the organization resource.
Ran with the following ENV variables:
```
GITHUB_POLICY_SET_IDENTIFIER=hashicorp/test-policy-set
TF_ACC=1
ENABLE_TFE=1
TFE_HOSTNAME=<redacted>
TFE_TOKEN=<redacted>
```
```
=== RUN   TestAccTFEOrganization_update_workspaceLimit
--- PASS: TestAccTFEOrganization_update_workspaceLimit (86.91s)
```
> add workspace limit admin setting

- website/docs/r/variable_set.html.markdown
This [issue](https://github.com/hashicorp/terraform-provider-tfe/issues/559) reported the non-working example.
One workaround is to create workspaces in one pass, and then assign variable sets based on tags in a second terraform config. But this example could potentially be used to work around the security model of variable sets, so that does not seem ideal to include.
> Remove example because it does not work

- CHANGELOG.md
- go.mod
- go.sum
- tfe/resource_tfe_registry_module.go
- tfe/resource_tfe_registry_module_test.go
- website/docs/r/registry_module.html.markdown
_This PR adds changes that support creating `both private and public registry modules` without using a VCS. It also extends the ability to `import` both private and public registry module by including the `namespace` and `registry-name` in the import id._
_Remember to:_
1.  _With existing code a registry module can only be created via the required VCS block_
1.  _After code changes, both private and public modules can be added without the vcs block_
1.  _The import identifier includes the namespace and registry_name and should be able to …
> add support for registry modules without vcs

- CHANGELOG.md
- tfe/resource_tfe_team.go
The issue was reported [here](https://github.com/hashicorp/terraform-provider-tfe/issues/439).
Effectively, the `ForceNew` modifier was set in the `name` attribute of the `r/tfe_team` schema causing the recreation of the team resource whenever the name was updated.
This PR removes this as there isn't any API specific behavior that requires the team to be recreated upon a name change. 
In order to smoke test this, we'll need a simple configuration that provisions a team (ensure your organization is not on the free tier):
```hcl
resource "tfe_team" "foo" {
name = "the-foo-fighters"
organization = "rocknroll"
}
```
Create the team first using `terraform apply` and then simply modify the name, running `terraform apply` again. Overriding the provider to a local build including my changes, you …
> Remove force new modifier on name attribute

- CHANGELOG.md
- tfe/resource_tfe_registry_module.go
- tfe/resource_tfe_registry_module_test.go
After a registry module is created and consecutive apply is run, the registry modules get recreated even though there is no change in the params. This PR adds changes to prevent unnecessary tfe_registry_modules replacement.
_Remember to:_
1.  _Create config with resource "tfe_registry_module"_
1.  _Run an apply, it should be successful_
1.  _Run another apply. Before this PR, new changes will be applied even though the params did not change_
1.  _After this PR, no changes should be applied unless …
> Changes to prevent unnecessary tfe_registry_modules replacement

- CHANGELOG.md
- tfe/resource_tfe_organization.go
- tfe/resource_tfe_organization_test.go
- website/docs/r/organization.html.markdown
This PR stems from #570 where a user with lower privileges would encounter a `404` error when managing a `tfe_organization` resource. 
The reason for this error is that `tfe_organization` makes a call to the [Admin Organization API](https://www.terraform.io/cloud-docs/api-docs/admin/organizations) to read the admin settings without accounting for the possibility the client `token` has lower privileges. Regardless, it's generally a bad idea to manage two different APIs that require different privileges within one resource.
This attribute will be removed in favor of creating a new resource `r/tfe_admin_organization` which will solely manage the admin settings for a given organization. Thus separating the concerns between a site admin and a regular user.
> Remove `admin_settings` from `tfe_organization`

- CHANGELOG.md
- tfe/agent_pool_helpers.go
- tfe/data_source_agent_pool.go
- tfe/resource_tfe_agent_pool.go
- tfe/resource_tfe_agent_pool_test.go
- website/docs/r/agent_pool.html.markdown
Allow agent pools to be imported by `org name/agent pool name`
1.  Check that agent pool data sources still works
2. Check that agent pools can still be imported by ID
3. 2. Check that agent pools can  be imported by org/name
4. Check that invalid import ID formats fail (eg a/b/c)
5. Check for error if org name is not found
6. Check for error if pool name is not found
- [Related Earlier PR](https://github.com/hashicorp/terraform-provider-tfe/pull/508)
- [JIRA](https://hashicorp.atlassian.net/browse/TF-414)
```
❯ go test github.com/hashicorp/terraform-provider-tfe/tfe  -run TestAccTFEAgentPool_import -v
=== RUN   TestAccTFEAgentPool_import
--- PASS: TestAccTFEAgentPool_import (104.15s)
PASS
ok
...
```
> Allow agent pools to be imported by name

- CHANGELOG.md
- tfe/data_source_organization_run_task.go
- tfe/data_source_organization_run_task_test.go
- tfe/resource_tfe_organization_run_task.go
- tfe/resource_tfe_organization_run_task_test.go
- website/docs/d/organization_run_task.html.markdown
- website/docs/r/organization_run_task.html.markdown
Organization level run tasks were recently updated to include an optional
description field.  This commit updates the Org. Run Tasks resource and
data source to read and modify the new attribute.
N/A Acceptance tests were updated.
- [go-tfe documentation](https://github.com/hashicorp/go-tfe/pull/447)
- [API documentation](https://www.terraform.io/cloud-docs/api-docs/run-tasks/run-tasks#create-a-run-task)
In CI
> Add Organization run task description field

- CHANGELOG.md
- tfe/data_source_outputs.go
- tfe/data_source_outputs_test.go
- tfe/test-fixtures/state-versions/terraform.tfstate
It was [reported](https://github.com/hashicorp/terraform-provider-tfe/issues/557) (thank you!) that a sensitive value in an output was not being read via tfe_outputs. Investigating the issue, we were originally getting state version outputs via reading a workspace and including outputs. This [API](https://www.terraform.io/cloud-docs/api-docs/workspaces#show-workspace) call does not include sensitive values.
The fix is to instead read the outputs from the state version itself.
🤔 Question for reviewers: I noticed that in the go-tfe test for StateVersion.ListOutputs, we have a [call](https://github.com/hashicorp/go-tfe/blob/ce0f146febc7a8ad6aef26d56a0d0ebc9f242991/state_version_integration_test.go#L484) to wait for the state version outputs. I'm wondering if we need to do something similar …
> Fix: read workspace state version outputs for sensitive values

- GNUmakefile
- tfe/data_source_outputs_test.go
- tfe/testing.go
Lately we have had a few recurrent flaky tests in CircleCi. For example these three:
=== Failed
=== FAIL: tfe TestAccTFEOutputs (2.44s)
data_source_outputs_****.go:31: Step 1/1 error: Error running pre-apply refresh: exit status 1
=== FAIL: tfe TestAccTFEVariableSetsDataSource_full (3.18s)
data_source_variable_set_****.go:42: Step 1/1 error: Check failed: 1 error occurred:
* Check 4/4 error: data.tfe_variable_set.foobar: Attribute 'variable_ids.#' expected "1", got "0"
=== Failed
=== RUN   TestAccTFEOrganizationRunTask_create
resource_tfe_organization_run_task_test.go:44: Step 2/3 error: Error running apply: exit status 1
For this PR, I have focused on investigating just the first one because it has been failing consistently, much more than others, to the point where, these days, we are …
> Small adjustment for flaky CI test

- CHANGELOG.md
- tfe/resource_tfe_workspace.go
- tfe/resource_tfe_workspace_test.go
Fix for the scenario of removing `vcs_repo` configuration from a workspace resource when previously setup the workspace to be triggered by tagged release via `tags_regex` 
* Configure tfe_workspace resource with `vcs_repo` & `tags_regex`
* Apply the terraform configuration
* Remove vcs_repo configuration
* Attempt a terraform apply, should succeed and remove the vcs_repo setting from the workspace
Without this fix, last step would result in an error.
- [API documentation](https://www.terraform.io/cloud-docs/workspaces/settings/vcs#trigger-runs-when-a-git-tag-is-published)
- [Related PR](https://github.com/hashicorp/terraform-provider-tfe/pull/549)
_Please run …
> Fix issue with removing vcs_repo config from workspace with tags_regex

- CHANGELOG.md
- tfe/data_source_workspace_run_task.go
- tfe/data_source_workspace_run_task_test.go
- tfe/resource_tfe_workspace_run_task.go
- tfe/resource_tfe_workspace_run_task_test.go
- tfe/testing.go
- website/docs/d/workspace_run_task.html.markdown
- website/docs/r/workspace_run_task.html.markdown
This commit adds the stage attribute to the Workspace Run Task
Resource and Data Source. Note that this is in beta for the
Resource.  This commit adds acceptance tests, and optionally
test the Beta features.
This commit also adds descriptions for the Workspace Run Task
attributes.
1. Acceptance tests cover the testing plan.  Beta features require a feature flag to be enabled on TFC.
- [go-tfe documentation](https://github.com/hashicorp/go-tfe/pull/469x)
- [API documentation](https://github.com/hashicorp/go-tfe/pull/469)
With beta tests enabled
```text
=== RUN …
```
> Add workspace run task stage property

- CHANGELOG.md
- go.mod
- go.sum
- tfe/provider.go
- tfe/resource_tfe_policy_set.go
- tfe/resource_tfe_workspace_policy_set.go
- tfe/resource_tfe_workspace_policy_set_test.go
- website/docs/r/workspace_policy_set.html.markdown
Currently the lifecycle of the tfe_policy_set requires that all tfe_workspace resources are created first and then assigned in one call to the tfe_policy_set during creation of the policy. For example:
```
resource "tfe_workspace" "test_ws" {
name         = "test_ws"
organization = "my-org"
tag_names    = ["test", "app"]
}
resource "tfe_policy_set" "test_policy_set" {
name          = "my-policy-set"
description   = "A new policy set"
organization  = "my-org"
workspace_ids = [tfe_workspace.test_ws.id]
}
```
Consider the case where `tfe_workspace` resources are spread across multiple repositories. Where each team or repo wants to be able to create & attach workspaces to existing policy sets. For example,
`team-security` is in charge of creating policies and own security-repo having:
``` …
```
> Add ability to attach a workspace to an existing policy set

- TESTS.md
- tfe/data_source_agent_pool_test.go
- tfe/data_source_organization_run_task_test.go
- tfe/data_source_outputs_test.go
- tfe/data_source_policy_set_test.go
- tfe/data_source_team_access_test.go
- tfe/data_source_team_test.go
- tfe/data_source_workspace_run_task_test.go
- tfe/provider_test.go
- tfe/resource_tfe_agent_pool_test.go
- tfe/resource_tfe_agent_token_test.go
- tfe/resource_tfe_organization_module_sharing_test.go
- tfe/resource_tfe_organization_run_task_test.go
- tfe/resource_tfe_organization_test.go
- tfe/resource_tfe_policy_set_parameter_test.go
- tfe/resource_tfe_policy_set_test.go
- tfe/resource_tfe_terraform_version_test.go
- tfe/resource_tfe_workspace_run_task_test.go
- tfe/resource_tfe_workspace_test.go
- tfe/testing.go
Adds a test helper `upgradeOrganizationSubscription()` that attempts to upgrade an organization's feature set if `TFE_HOSTNAME` is not enterprise. The helper will skip the test if it is running against an enterprise instance since all features are available in TFE unless otherwise specified. This PR also removes the `skipIfFree()` test helper for paid feature tests that were previously blocked from running in CI.
> Add upgrade organization test helper, remove `SKIP_PAID` flag. 

- go.mod
- go.sum
This PR was created to upgrade `github.com/hashicorp/terraform-plugin-go v0.5.0` to `v0.6.0`. A bug was reported, and after investigating the issue, it has been determined that an upgrade resolve the issue.
_Remember to:_
```
terraform {
required_providers {
tfe = {
version = "0.33.0"    <---- toggle between "0.31.0"
}
}
}
hostname = "tfcdev-xxxxxx.ngrok.io"
}
data "tfe_outputs" "workspace" {
organization = "hashicorp"
workspace    = "test-apply-command"
}
output "output_this" {
value = …
```
> bump terraform-plugin-go

- CONTRIBUTING.md
- main.go
Enable provider to initialize in debug mode, allowing devs to start debuggers via terraform commands as explained [here](https://www.terraform.io/plugin/debugging)
e.g.
```
TF_REATTACH_PROVIDERS='{"registry.terraform.io/my-org/my-provider":{"Protocol":"grpc","Pid":3382870,"Test":true,"Addr":{"Network":"unix","String":"/tmp/plugin713096927"}}}' terraform apply
```
Looks like a newer release of tf5server, offers a simpler implementation with [WithManagedDebug](https://pkg.go.dev/github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server#WithManagedDebug). But this could be a workaround until we upgrade the tf5server package version.
_Remember to:_
- _Update the …
> Enable debug mode on provider, via `TF_REATTACH_PROVIDERS`

- CHANGELOG.md
- tfe/resource_tfe_workspace.go
- tfe/resource_tfe_workspace_test.go
Workspaces can be created using the `resource "tfe_workspace"` with fields including `execution_mode` and `agent_pool_id`. After creation, if the config is updated by removing the `execution_mode` and `agent_pool_id` fields, the changes are not detected during an apply and plan fails with error: `Error: agent_pool_id must be provided when execution_mode is 'agent'`.
See issue: https://github.com/hashicorp/terraform-provider-tfe/issues/544
With this fix, changes in `execution_mode` and `agent_pool_id` fields are now detected and plans/applies are successful.
_Remember to:_
- _Update the [Documentation](https://github.com/hashicorp/terraform-provider-tfe/blob/main …
> Fix ability to detect and apply agent_pool_id and execution_mode changes

- tfe/resource_tfe_workspace_run_task.go
- website/docs/r/workspace_run_task.html.markdown
This commit updates the go-tfe library to 1.10.0 which is necessary to add
the new task stage (pre-apply).
I did not add a changelog entry as this is too minor a change, and not worth noting.
N/A
- [API documentation](https://www.terraform.io/cloud-docs/api-docs/run-tasks/run-tasks#associate-a-run-task-to-a-workspace)
> Add additional value to Workspace Task Stage

- CHANGELOG.md
- tfe/resource_tfe_variable_set.go
This PR fixes a panic that occurs when setting the `workspace_ids` attribute to `[""]`, thus causing `tfeClient.VariableSets.UpdateWorkspaces()` to return an error. That error message in turn would reference a `nil` variable:
https://github.com/hashicorp/terraform-provider-tfe/blob/2a1b060e828ed33d2ab81f35ab81240284e4331e/tfe/resource_tfe_variable_set.go#L90-L94
See the issue? If that method returns an error, `variableSet.ID` in L93 will cause a panic. 
**Furthermore**, I noticed some weird behavior where the variable set would be created successfully, applying to a workspace would fail, and Terraform would then try to recreate the resource since it thinks it doesn't exist (both operations occur during the creation phase). I updated the provider to write to state when the variable set is …
> Fix panic when applying variable set to workspaces fails

- CHANGELOG.md
- tfe/data_source_organization.go
- tfe/data_source_workspace.go
- tfe/data_source_workspace_test.go
- tfe/resource_tfe_organization.go
- tfe/resource_tfe_organization_test.go
- tfe/resource_tfe_workspace.go
- tfe/resource_tfe_workspace_migrate.go
- tfe/resource_tfe_workspace_test.go
- website/docs/d/organization.html.markdown
- website/docs/d/workspace.html.markdown
- website/docs/r/organization.html.markdown
- website/docs/r/workspace.html.markdown
This Change is to allow operators to manage the drift detection setting for workspaces.
- [go-tfe documentation]() <= not available until the go-tfe PR lands.
- [API documentation](https://www.terraform.io/cloud-docs/api-docs/workspaces#request-body)
Relies on:
- [Related PR](https://github.com/hashicorp/go-tfe/pull/462)
```
$ TESTARGS="-run TestAccTFEWorkspace_basicDriftDetection" make testacc
==> …
```
> Add support for managing health assessment (drift detection) settings on workspaces and organizations

- tfe/data_source_outputs_test.go
- tfe/logging.go
- tfe/provider.go
- tfe/resource_tfe_policy_set_test.go
"io/ioutil" has been [deprecated](https://pkg.go.dev/io/ioutil) since Go 1.16.
1.  See referenced documentation
N/A
```
...
```
> io/ioutil is deprecated, removed

- CHANGELOG.md
- CONTRIBUTING.md
- tfe/resource_tfe_workspace.go
We neglected to add this argument to the list of changes to probe for when updating a workspace. If assessments_enabled is the only change in a workspace, the workspace will not be updated at all.
Change assessments_enabled on a tfe_workspace resource (and no other argument) and apply the change. It should now be updated.
> Workspace not updated when assessments_enabled is the only change

- .circleci/config.yml
Other 3rd party libraries are using 1.18 so let's get our build system also using 1.18.
1. The circle ci tests should still run.
N/A
N/A
> ⬆️ Use go 1.18 when building/testing in circle ci

- .github/workflows/lint.yml
I'm seeing these 2 issues with the older version of the linter:
- https://github.com/golangci/golangci-lint/issues/2374
- https://github.com/golangci/golangci-lint/issues/2649
So bumping the version to the latest (1.50.0) to resolve issues with go1.18.
1. Linting passes
> Use golangci-lint 1.50.0 (latest)

- go.mod
- go.sum
Bump the go-cty dependency to the latest available.
1. Confirm all of the tests pass.
This PR needs the golang image to be 1.18.
- [Related PR](https://github.com/hashicorp/terraform-provider-tfe/pull/643)
~## Output from acceptance tests~
> ⬆️ Bump github.com/zclconf/go-cty to 1.11.0

- tfe/data_source_variable_set_test.go
This PR adds the [depends_on](https://www.terraform.io/language/meta-arguments/depends_on) meta-argument to ensure `variable_ids` is processed before the resource is read.
1. Run the test 100 times.
N/A
```
...
```
> fix flaky test by adding depends_on meta-arg

- tfe/data_source_outputs_test.go
@laurenolivia noticed the [waitForOutputs()](https://github.com/hashicorp/terraform-provider-tfe/blob/main/tfe/data_source_outputs_test.go#L31) is producing a [flaky](https://app.circleci.com/pipelines/github/hashicorp/terraform-provider-tfe/1617/workflows/5eecafd7-d9af-4389-a6b2-e7aafdeac5b0/jobs/1671) test at TestAccTFEOutputs
This PR attempts to address the flake by increasing the max retries and the seconds in between retries.
_Remember to:_
1.  Run the test `TestAccTFEOutputs` a large number of times.
_Please run …
> ✅ Increase number of retries and wait time when populating outputs in test

- CHANGELOG.md
- tfe/data_source_organization_members.go
- tfe/data_source_organization_members_test.go
- tfe/organization_members_helpers.go
- tfe/organization_members_helpers_test.go
- tfe/provider.go
- tfe/testing.go
- website/docs/d/organization_members.html.markdown
Add datasource `tfe_organization_members` which returns a list of active members and members with pending invite in an organization.
1.  _Use config with:_
``` 
resource "tfe_organization" "bar" {
name = "org-bar"
email = "user@hashicorp.com"
}
data "tfe_organization_members" "foo" {
organization = tfe_organization.bar.name
}
```
1.  _a list of members and members_waiting in the org should be returned_
```
{
"id" = "my-org"
"members" = tolist([
{
"organization_membership_id" = "ou-id"
"user_id" = "user-id"
},
])
"members_waiting" = tolist([
{
"organization_membership_id" = "ou-id"
"user_id" = "user-id"
}
])
"organization" = "my-org"
}
```
- [go-tfe …
> add datasource tfe_organization_members

- website/docs/index.html.markdown
Adds documentation that a `credentials_helper` in the user's Terraform configuration is not a supported authentication mechanism. While it's supported by the package used for fetching authn (`terraform-svchost`), only static tokens are implemented currently by this provider.
https://github.com/hashicorp/terraform-svchost/blob/master/auth/helper_program.go
Adding support for credentials helpers is non-trivial. The package handles the protocol for calling these helpers (args) but not things like the directory where helper executables are found. Given the effort involved in implementing this and the fact that it would only work in workspaces in local execution mode, documenting the limitation rather than addressing it seems like the best course.
* #637 
* …
> docs: mention non-support for `credential_helper`

- tflocal/main.tf
- tflocal/variables.tf
PR says it all, the latest version of tflocal-cloud is v0.8. I've also removed the token/password variables to let the module seed these values.
> Update tflocal module to v0.8, remove token/password vars

- GNUmakefile
- TESTS.md
The reason for this change stems from the lack of clarity behind why we make the distinction between `make test` and `make testacc`. At the surface level, the singular difference between the two targets is whether `TF_ACC` is set or not. This PR adds a a description to our `Run the tests` section explaining in a bit more detail as to why that is, as well as attempting to provide a simple definition for what sort of test is classified as an acceptance test and which are classified as unit tests. I've also reversed the ordering to display how to run acceptance tests **first**, since they are most common type on test people will write for the provider.
> Update test docs to mention distinction between Makefile test targets

- CHANGELOG.md
- tfe/resource_tfe_workspace_run_task.go
- website/docs/r/terraform_version.html.markdown
- website/docs/r/workspace_run_task.html.markdown
Pre-plan and Pre-Apply Run Tasks are now generally available. This commit removes the beta notices. Note that the tests cannot be modified yet as the integration environment has been updated.
Not applicable
> Remove Run Task beta notes

- website/docs/r/workspace.html.markdown
Fixing markdown syntax to fix ADO `identifier` example
> Fixing markdown syntax to fix ADO identifier example

- CHANGELOG.md
- tfe/resource_tfe_agent_pool.go
- tfe/resource_tfe_notification_configuration.go
- tfe/resource_tfe_organization.go
- tfe/resource_tfe_organization_membership.go
- tfe/resource_tfe_organization_run_task.go
- tfe/resource_tfe_organization_token.go
- tfe/resource_tfe_policy_set.go
- tfe/resource_tfe_policy_set_parameter.go
- tfe/resource_tfe_registry_module.go
- tfe/resource_tfe_run_trigger.go
- tfe/resource_tfe_sentinel_policy.go
- tfe/resource_tfe_team.go
- tfe/resource_tfe_team_access.go
- tfe/resource_tfe_team_member.go
- tfe/resource_tfe_team_members.go
- tfe/resource_tfe_team_organization_member.go
- tfe/resource_tfe_team_token.go
- tfe/resource_tfe_terraform_version.go
- tfe/resource_tfe_variable.go
- tfe/resource_tfe_variable_set.go
- tfe/resource_tfe_workspace.go
- tfe/resource_tfe_workspace_policy_set.go
- tfe/resource_tfe_workspace_run_task.go
- tfe/resource_tfe_workspace_variable_set.go
`ResourceImporter.State` has deprecated functions.
N/A
See docs on [ImportStatePassthrough](https://pkg.go.dev/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema#ImportStatePassthrough)
```
...
```
> ResourceImporter.State has deprecated funcs

- CHANGELOG.md
- go.mod
- go.sum
- tfe/client_mock_workspaces.go
- tfe/resource_tfe_organization.go
- tfe/resource_tfe_organization_test.go
- website/docs/r/organization.html.markdown
This change adds the `allow_force_delete_workspaces` setting to the TFE provider.
- [Related PR](https://github.com/hashicorp/atlas/pull/13244)
```
/opt/homebrew/Cellar/go/1.19.2/libexec/bin/go tool test2json -t /private/var/folders/2z/33zp571x44v_ndv_hk8cyy1w0000gp/T/GoLand/___1TestAccTFEOrganization_basic_in_github_com_hashicorp_terraform_provider_tfe_tfe.test -test.v -test.paniconexit0 -test.run …
```
> [#TF-720] Add allow_force_delete_workspaces organization setting to the tfe provider

- CHANGELOG.md
- tfe/client_mock_workspaces.go
- tfe/resource_tfe_workspace.go
- tfe/resource_tfe_workspace_test.go
- website/docs/r/workspace.html.markdown
Adds the `force_delete` attribute to a workspace provider resource. 
- [Related PR](https://github.com/hashicorp/terraform-provider-tfe/pull/661)
```
/opt/homebrew/Cellar/go/1.19.2/libexec/bin/go tool test2json -t /private/var/folders/2z/33zp571x44v_ndv_hk8cyy1w0000gp/T/GoLand/___TestTFEWorkspace_delete_withoutCanForceDeletePermission_in_github_com_hashicorp_terraform_provider_tfe_tfe.test -test.v -test.paniconexit0 -test.run ^\QTestTFEWorkspace_delete_withoutCanForceDeletePermission\E$
=== RUN …
```
> [#TF-722] Allow safe and force delete through the tfe provider

- CHANGELOG.md
- tfe/resource_tfe_notification_configuration.go
- website/docs/r/notification_configuration.html.markdown
See https://github.com/hashicorp/go-tfe/pull/542
Add new assessment triggers for notification
_Remember to:_
1. `terraform apply`
_Please run applicable acceptance …
> Add assessment triggers to notifications

- docs/testing.md
- website/docs/d/policy_set.html.markdown
- website/docs/r/policy.html.markdown
- website/docs/r/policy_set.html.markdown
- website/tfe.erb
Add docs for OPA support to the tfe-provider for policies and policy sets. OPA is still in beta phase.
Screenshots:
`r/tfe_policy`
`r/tfe_policy_set`
`d/tfe_policy_set`
Related PRs
https://github.com/hashicorp/terraform-provider-tfe/pull/690
https://github.com/hashicorp/terraform-provider-tfe/pull/691
NA
[go-tfe Policy Set documentation](https://github.com/hashicorp/go-tfe/blob/main/policy_set.go)
[go-tfe Policy documentation](https://github.com/hashicorp/go-tfe/blob/main/policy.go)
[API Policy Set documentation](https://developer.hashicorp.com/terraform/cloud-docs/api-docs/policy-sets)
[API Policy documentation](https://developer.hashicorp.com/terraform/cloud-docs/api-docs/policies)
[JIRA](https://hashicorp.atlassian.net/browse/TF-1451)
Related PRs: …
> Add Documentation : OPA support for policies and policy sets

- CHANGELOG.md
- website/docs/r/policy.html.markdown
- website/docs/r/sentinel_policy.html.markdown
Fix documentation to say the enforce_mode is not required while creating policies
> fix doc to remove enforce_mode is required

- CHANGELOG.md
- tfe/data_source_workspace_ids.go
- tfe/data_source_workspace_ids_test.go
- website/docs/d/workspace_ids.html.markdown
There was a [feature request](https://github.com/hashicorp/terraform-provider-tfe/issues/274) to pass partial matching to `names` arg using the `*` char.
_Remember to:_
1.  See [docs](https://registry.terraform.io/providers/hashicorp/tfe/latest/docs/data-sources/workspace_ids) on how to use `names` arg
_If you are an external contributor, your contribution(s) will first be reviewed before running …
> refactor how workspace names resource arg filters for matches

- .github/workflows/nightly-tfe-test.yml
- tfe/resource_tfe_registry_module_test.go
This is breaking the nightly. I checked with the registry team and this is the new expected behavior.
> Disable the no_code registry module test in TFE

- CHANGELOG.md
- tfe/data_source_outputs.go
- tfe/data_source_outputs_test.go
- tfe/plugin_provider.go
- website/docs/d/outputs.html.markdown
Added `nonsensitive_values` attribute to `tfe_outputs` datasource to allow retrieving the current non-sensitive outputs of a given workspace. 
_Remember to:_
1.  _Create a workspace that has both sensitive and non-sensitive outputs_
2.  _Use tfe_outputs datasource like below to attempt to retrieve outputs_
```
data "tfe_outputs" "example" {
organization = "org"
workspace = "prod-app"
}
output "example" {
value = data.tfe_outputs.example.values.foo
}
```
3.  _Retrieval should error unless you use the `nonsensitive` function_
4. …
> add nonsensitive_values field to tfe_outputs

- CHANGELOG.md
- tfe/resource_tfe_workspace.go
- tfe/resource_tfe_workspace_test.go
- website/docs/r/workspace.html.markdown
This PR exposes the `resource_count` attribute on the `tfe_workspace` resource. This is to make it easier for users writing a Sentinel policy to prevent workspaces from being deleted prior to deleting all of the resources that belong to the given workspace. This attribute is already exposed as part of the data source call.
Below is a screenshot of the documentation update on the `tfe_workspace` resource:
1. Create a new workspace using the configuration below
```hcl
resource "tfe_organization" "test-organization" {
name  = "my-org-name"
}
resource "tfe_workspace" "test" {
name         = "my-workspace-name"
organization = tfe_organization.test-organization.name
tag_names    = ["test", "app"]
}
output "workspace_resource_count" {
value = …
```
> Adding support for the resource_count attribute on tfe_workspace 

- go.mod
- go.sum
- tfe/resource_tfe_project_test.go
The title is a concise summary :book: and this PR closes #714 
The fix was actually implemented in our go-tfe dependency [here]( https://github.com/hashicorp/go-tfe/pull/608
) (released in v1.16).
The go-tfe library was validating project names as external IDs, of which inner spaces would result in a validation error.  `go-tfe` was upgraded [here](https://github.com/hashicorp/terraform-provider-tfe/commit/49a77efcc05d1fe6de475c373a530f80b9e109c4).  
I've updated the `tfe_project` resource `Update` test and changed the `name` attribute to include an inner space to reflect the fix :smile: 
```sh
ENABLE_BETA=1 TESTARGS="-run TestAccTFEProject_update" make testacc
```
1. Apply this config:
```hcl
resource "tfe_project" "foo" {
name = "a project name with spaces"
organization = "<my_org_name>" …
```
> Update acceptance test to reflect Project rename bugfix with go-tfe v1.16.0 upgrade

- .github/scripts/fetch_outputs/main.go
- .github/workflows/nightly-tfe-test.yml
Fetch outputs steps within the nightly TFE tests is failing from time to time with the same `unauthorized` error: https://github.com/hashicorp/terraform-provider-tfe/actions/runs/3661717920/jobs/6190255505
We are not completely sure what is causing it, though there is some speculations. Please read the latest slack conversation on this for more information.
Changes that we are making to either fix the issue or help with the troubleshooting of the issue:
1)We are removing the name field `name: Summarize Tests` in case is conflicting with the job id called `tests-summarize`.
2)We are also adding some additional context to some errors in the go program for fetch outputs to help debug in the future.
3)Finally, adding some additional options to the workflow bash that runs with only -e option …
> Debug step failure

- website/docs/index.html.markdown
The tfe hostname needs to have a clear description that needs to be setup for the Terraform Enterprise, otherwise it sends the request to the Terraform Cloud hostname
> tfe hostname clarification for users

- .github/dependabot.yml
Currently dependabot is being used to check for updates for any go related packages which this project uses in order to keep it up-to-date, but dependabot is currently not being used to do the same for github actions which should also arguably be kept up-to-date.
_Remember to:_
_Include any links here that might be helpful for …
> Check for github action updates daily

- GNUmakefile
- tfe/resource_tfe_workspace.go
- tfe/resource_tfe_workspace_test.go
- tfe/workspace_helpers.go
Today, we print a warning if you use upcase letters in your tfe_workspace tag_names. Trouble is, you don't see these warnings until after you've already created the offending tag name and only if you have TF_LOG level set to warn.
The API will accept uppercase tag names, but will silently downcase them, which introduces a problem for uppercase config tag names, because from that time on, the case change is detected as drift. This proactive enforcement will protect users from unexpected drift on the next apply:
```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
+ create
Terraform will perform the following actions:
+ resource "tfe_workspace" "deleteme" {
+ allow_destroy_plan            = true
+ …
```
> Validate tag_names for lowercase and other api validation rules

- CHANGELOG.md
- tfe/data_source_workspace_ids.go
- tfe/data_source_workspace_ids_test.go
There was a bug in the new d/tfe_workspace_ids wildcard logic that performed a substring match even when no wildcards were present
Closes #747 
```
$ TESTARGS="-run TestAccTFEWorkspaceIDsDataSource_noMatch" make testacc
TF_ACC=1 TF_LOG_SDK_PROTO=OFF go test $(go list ./... |grep -v 'vendor') -v -run TestAccTFEWorkspaceIDsDataSource_noMatch -timeout 15m
=== RUN   TestAccTFEWorkspaceIDsDataSource_noMatch
--- PASS: TestAccTFEWorkspaceIDsDataSource_noMatch (25.57s)
PASS
ok  	github.com/hashicorp/terraform-provider-tfe/tfe	26.388s
```
> d/workspace_ids: Require exact match when no wildcard

- website/docs/d/workspace.html.markdown
- website/docs/r/workspace.html.markdown
This change updates the website documentation for the `tfe_workspace` data source and resource to remove the following outdated note from the `trigger_patterns` argument/attribute:
> Only available for Terraform Cloud.
N/A
N/A
N/A
> docs: remove outdated "Only available for Terraform Cloud" reference

- .gitignore
- docs/beta.md
- docs/index.md
- docs/test-infrastructure.md
- mkdocs.yml
The test infrastructure and skip helpers, as well as a general overview of how we release less-than-generally-available features, seem to be missing from our contributor guide.
> Add beta policy and test infra information to contributor guide

- CHANGELOG.md
- tfe/resource_tfe_team_members.go
- tfe/resource_tfe_team_organization_members.go
- website/docs/r/team_members.html.markdown
- website/docs/r/team_organization_members.html.markdown
Related Issue: [761](https://github.com/hashicorp/terraform-provider-tfe/issues/761)
Terraform creates an instance for each member of a given set, when `for_each` is used to configure a resource block. 
If `for_each` is used with resources that do bulk management like the `tfe_team_organization_members` and `tfe_team_members`, it results in the creation of multiple instances managing the same set of resources. See the example config below:
```
locals {
all_users = toset([
"user1@hashicorp.com",
"user2@hashicorp.com",
])
}
resource "tfe_team" "test" {
name         = "my-team-name"
organization = "my-org-name"
}
resource "tfe_organization_membership" "all_membership" {
organization = "my-org-name"
for_each     = local.all_users
email        = each.key
}
resource …
```
> update website doc to depict the use of sets in members resource

- CHANGELOG.md
- tfe/data_source_workspace.go
- tfe/data_source_workspace_test.go
- website/docs/d/workspace.html.markdown
This PR adds `execution_mode` field to `tfe_workspace` datasource
1.  _Create workspaces with different execution modes i.e, local, remote, agent. For backward compatibility, create some with `operations` field set as well_
2.  _Read the workspace using tfe_workspace datasource for example:_
```
data tfe_workspace "read_workspace_local_ex_mode" {
name         = tfe_workspace.workspace_local_ex_mode.name
organization = "my-org"
}
data tfe_workspace "read_workspace_remote_ex_mode" {
name         = tfe_workspace.workspace_remote_ex_mode.name
organization = "my-org"
}
data tfe_workspace "read_workspace_agent_ex" {
name         = tfe_workspace.workspace_agent_ex_mode.name
organization = "my-org"
}
data tfe_workspace "read_workspace_operation_true" {
name         = …
```
> Add execution_mode to datasource tfe_workspace

- CHANGELOG.md
- tfe/data_source_team_project_access.go
- tfe/data_source_team_project_access_test.go
- tfe/provider.go
- tfe/resource_tfe_project.go
- tfe/resource_tfe_team.go
- tfe/resource_tfe_team_project_access.go
- tfe/resource_tfe_team_project_access_test.go
- tfe/resource_tfe_team_test.go
- tfe/testing.go
- website/docs/d/team_project_access.html.markdown
- website/docs/r/team.html.markdown
- website/docs/r/team_project_access.html.markdown
This adds support for managing a team's project permissions. It introduces a new resource called `tfe_team_project_access` to grant a team read or admin permission on a specific project, and adds a new `manage_projects` attribute on the `tfe_team` resource to allow giving a team access to all projects in an org.
1.  Ensure new tests pass
2. Try importing existing resources
3. Ensure existing configs still apply cleanly
4. Manually test with various configurations similar to:
```
resource "tfe_organization" "test-organization" {
name  = "my-org-name"
}
resource "tfe_project" "test" {
organization = tfe_organization.test-organization.name
name = "projectname"
}
resource "tfe_team" "manage-proj" {
organization = tfe_organization.test-organization.name
name = …
```
> Allow managing project permissions

- .github/workflows/lint.yml
- .github/workflows/release.yml
Reference: https://github.com/hashicorp/ghaction-terraform-provider-release/releases/tag/v2.2.0
Reference: https://github.com/hashicorp/ghaction-terraform-provider-release/blob/7e53d9adb57f05cb16c227ef0bfd030060fae82e/.github/workflows/hashicorp.yml#L26-L29
The actions/setup-go action now accepts a `go-version-file` input, which can point to `go.mod` or a file such as the existing `.go-version`. If you are not using `.go-version` for its `goenv` functionality, it might be worth switching these to `go.mod` instead.
_Remember to:_
- _Update the [Documentation](https://github.com/hashicorp/terraform-provider-tfe/blob/main/CONTRIBUTING.md#updating-the-documentation) …
> .github/workflows: Use actions/setup-go go-version-file input

- CHANGELOG.md
- README.md
- website/docs/index.html.markdown
Hello! It's time again for a release of the tfe provider. Here's the changelog update and the version number bumps. 
As you can see in the Actions tab, the nightly TFE tests are currently **passing.**
> Prepare 0.42.0 release

- CHANGELOG.md
- tfe/resource_tfe_organization_membership.go
- tfe/resource_tfe_organization_membership_test.go
- website/docs/r/organization_membership.html.markdown
Allow tfe_organization_membership resource to also be imported by org-name/user-email
Presently, the resource can only be imported through its ID, which is not presented to the user in the TFE UI. This makes it very difficult to import.
1.  Test that import by ID still works
1.  Test that importing by org/email works
2. Test that importing by an invalid format errors
3. Test that importing a non existent org name or email errors
- [internal JIRA](https://hashicorp.atlassian.net/browse/TF-3336)
- [resource documentation](https://registry.terraform.io/providers/hashicorp/tfe/latest/docs/resources/organization_membership)
```
❯ TF_ACC=1 go test ./...  -run TestAccTFEOrganizationMembership -tags=integration -v
=== RUN …
```
> Allow tfe_organization_membership import by org name and user email

- .github/workflows/ci.yml
The GH action to check copywrite is failing right now with an API rate limit exceeded.
Since that's blocking our builds, I'm disabling the check until the issue is resolved.
- [Issue](https://github.com/hashicorp/copywrite/issues/28)
> Disable copyright checking temporarily

- tfe/provider.go
Fixes style issue. No nil was returned or checked.
Closes https://github.com/hashicorp/terraform-provider-tfe/issues/790
```
$ TESTARGS="-run TestProvider" make testacc
TF_ACC=1 TF_LOG_SDK_PROTO=OFF go test $(go list ./... |grep -v 'vendor') -v -run TestProvider -timeout 15m
=== RUN   TestProvider
--- PASS: TestProvider (0.00s)
=== RUN   TestProvider_impl
--- PASS: TestProvider_impl (0.00s)
=== RUN   TestProvider_versionConstraints
--- PASS: TestProvider_versionConstraints (0.00s)
=== RUN   TestProvider_locateConfigFile
--- PASS: TestProvider_locateConfigFile (0.00s)
=== RUN   TestProvider_cliConfig
2023/02/06 07:18:15 [ERROR] Error reading CLI config or credentials file …
```
> Change CLI config functions to use values instead of pointers

- CHANGELOG.md
- website/docs/d/policy_set.html.markdown
- website/docs/d/workspace.html.markdown
- website/docs/r/policy_set.html.markdown
- website/docs/r/workspace.html.markdown
We should be try to differentiate between VCS organization from TFC organization more distinctly.
Closes #789
> Clarify <organization> usage in vcs_repo config blocks

- CHANGELOG.md
- tfe/data_source_workspace.go
- tfe/data_source_workspace_test.go
- tfe/resource_tfe_workspace.go
- tfe/resource_tfe_workspace_test.go
- website/docs/d/workspace.html.markdown
- website/docs/r/workspace.html.markdown
Adds html_url attribute to workspace resource & data source which is the URL to the browsable terraform cloud workspace overview as reported by the API
```
$ TESTARGS="-run TestAccTFEWorkspace_basic" make testacc
TF_ACC=1 TF_LOG_SDK_PROTO=OFF go test $(go list ./... |grep -v 'vendor') -v -run TestAccTFEWorkspace_basic -timeout 15m
=== RUN   TestAccTFEWorkspace_basic
--- PASS: TestAccTFEWorkspace_basic (38.37s)
=== RUN   TestAccTFEWorkspace_basicReadProjectId
testing.go:186: Skipping test related to a Terraform Cloud/Enterprise beta feature. Set ENABLE_BETA=1 to run.
--- SKIP: TestAccTFEWorkspace_basicReadProjectId (0.00s)
=== RUN   TestAccTFEWorkspace_basicAssessmentsEnabled
--- PASS: …
```
> Adds html_url attribute to d/tfe_workspace and r/tfe_workspace

- tfe/data_source_organization_test.go
- tfe/data_source_workspace_test.go
- tfe/resource_tfe_organization_test.go
- tfe/resource_tfe_project_test.go
- tfe/resource_tfe_team_project_access_test.go
- tfe/resource_tfe_team_test.go
- tfe/resource_tfe_workspace_test.go
- tfe/testing.go
- website/docs/r/project.html.markdown
[Projects](https://developer.hashicorp.com/terraform/cloud-docs/api-docs/projects) are now generally available. This PR removes all the related beta flags and notices. 
Covered by integration tests
- [Related PR](https://github.com/hashicorp/terraform-provider-tfe/pull/704)
- [Related PR](https://github.com/hashicorp/terraform-provider-tfe/pull/768)
> Remove beta flags for Projects feature

- CHANGELOG.md
- tfe/resource_tfe_workspace.go
- tfe/resource_tfe_workspace_test.go
Update failure message when attempting to safe delete a workspace on a version of TFE which does not support safe delete, to clarify why the force_delete flag is needed
1. Verify that the updated error message is shown
```
go test ./...  -run TestTFEWorkspace -tags=integration -v
=== RUN   TestTFEWorkspace_delete_withoutCanForceDeletePermission
2023/02/16 09:52:49 [DEBUG] Delete workspace ws-testing
2023/02/16 09:52:49 [DEBUG] Delete workspace ws-testing
2023/02/16 09:52:49 [DEBUG] Delete workspace ws-testing
--- PASS: TestTFEWorkspace_delete_withoutCanForceDeletePermission (0.46s)
PASS
ok      github.com/hashicorp/terraform-provider-tfe/tfe 0.639s
...
```
> Clarify why force_delete is requires with old TFE versions

- CHANGELOG.md
- go.mod
- go.sum
- tfe/data_source_team_project_access_test.go
- tfe/resource_tfe_team_project_access.go
- tfe/resource_tfe_team_project_access_test.go
- website/docs/r/team_project_access.html.markdown
This adds new "maintain" and "write" access levels to the `tfe_team_project_access` resource.
Sample config:
```
variable "organization" {
type = string
}
resource "tfe_project" "this" {
organization = var.organization
name         = "test project"
}
resource "tfe_team" "maintain" {
organization = var.organization
name         = "maintain-team"
}
resource "tfe_team" "write" {
organization = var.organization
name         = "write-team"
}
resource "tfe_team_project_access" "maintain" {
access     = "maintain"
team_id    = tfe_team.maintain.id
project_id = tfe_project.this.id
}
resource "tfe_team_project_access" "write" {
access     = "write"
team_id    = tfe_team.write.id
project_id = tfe_project.this.id
}
```
- [API documentation](https://developer.hashicorp.com/terraform/cloud-docs/api-doc …
> Update team project access to include additional project roles

- CHANGELOG.md
- tfe/resource_tfe_workspace.go
fixes #834
Address #834 - only set `oauth_token_id` and `github_app_installation_id` if configured. Before this change, they'd be set to an empty string.
1.  Make a new `tfe_workspace` with `vcs_repo.oauth_token_id` explicitly set to `null`
1.  Run terraform apply in trace mode
1.  Observe apply operation fail
1.  Observe JSON POST request containing `"oauth-token-id": "",`, instead of the expected `"oauth-token-id": null,`
- Related PR where this feature was first introduced: [808](https://github.com/hashicorp/terraform-provider-tfe/pull/808)
_If you are an external contributor, …
> Only set `oauth_token_id` and `github_app_installation_id` if configured

- tfe/data_source_ip_ranges_test.go
- tfe/testing.go
This reverts commit eb3a464b15e1579f11cd49055fd89a77b860c554.
> Revert "temporarily skip ipranges test"

- CHANGELOG.md
- tfe/provider.go
- tfe/resource_tfe_project_variable_set.go
- tfe/resource_tfe_project_variable_set_test.go
- tfe/testing.go
- website/docs/r/project_variable_set.html.markdown
- website/docs/r/variable_set.html.markdown
DO NOT MERGE UNTIL PROJECT VARSETS GA
This pr adds a new tfe_project_variable_set resource. The resource applies a variable set to a project. This means that all existing and future workspaces within that project will have the variable set applied.
We would like to have this approved before and released on April 19th when the feature goes GA in TFC.
1. Write terraform config that looks like:
```
resource "tfe_variable_set" "this" {
name         = "my variable set"
organization = "my organization"
}
resource "tfe_project" "this" {
name         = "a project"
organization = "my organization"
}
resource "tfe_project_variable_set" "this" {
project_id      = tfe_project.this.id
variable_set_id = tfe_variable_set.this.id
}
```
3. `terraform apply`
4. Check that the variable set has been created …
> Add project varset resource

- tfe/data_source_project_test.go
This new test is flaky, because it tests the effect of the workspace resource on the project data source, but doesn't ensure that the workspace resource is processed first. Simple enough: just do that. 
1.  Test passes.
```
TF_ACC=1 TF_LOG_SDK_PROTO=OFF go test $(go list ./... |grep -v 'vendor') -v -run TestAccTFEProjectDataSource_basic -timeout 15m
=== RUN   TestAccTFEProjectDataSource_basic
--- PASS: TestAccTFEProjectDataSource_basic (18.16s)
PASS
ok  	github.com/hashicorp/terraform-provider-tfe/tfe	18.409s
?   	github.com/hashicorp/terraform-provider-tfe/version	[no test files]
```
> Fix flaky TestAccTFEProjectDataSource_basic

- CHANGELOG.md
- tfe/resource_tfe_team.go
- tfe/resource_tfe_team_test.go
- website/docs/r/team.html.markdown
Allow the manage membership organization access setting to be set on teams by the provider
1.  New teams should have manage_membership as false
2. If manage membership is omitted, it is set to false
1. Manage membership can be set or unset via the provider
- [go-tfe PR](https://github.com/hashicorp/go-tfe/pull/652 )
- [API docs](https://developer.hashicorp.com/terraform/cloud-docs/api-docs/teams#create-a-team)
- [Permission docs](https://developer.hashicorp.com/terraform/cloud-docs/users-teams-organizations/permissions#manage-membership)
```
TF_ACC=1 go test github.com/hashicorp/terraform-provider-tfe/tfe  -run TestAccTFETeam_ -tags=integration -v
=== RUN   TestAccTFETeam_basic
--- PASS: TestAccTFETeam_basic (6.43s)
=== RUN   TestAccTFETeam_full
--- PASS: TestAccTFETeam_full (6.27s)
=== …
```
> Add Manage Membership to team organization access

- CHANGELOG.md
- tfe/resource_tfe_project_variable_set_test.go
Remove beta flag from tfe_project_variable_set test.
I think that this is actually reliant on the feature flag being removed from Atlas first in this pr: https://github.com/hashicorp/atlas/pull/15420
I will run the tests again, once that is merged.
1. Only test change; tests should pass.
> TF-5353 Remove beta flag from project varsets tests

- .github/actions/lint-provider-tfe/action.yml
- .golangci.yml
At some point, the custom action stopped leaving annotations on the PR and also doesn't offer log output in the action output.
> Use `make lint` instead of custom action

- .golangci.yml
- CHANGELOG.md
- tfe/provider.go
- tfe/resource_tfe_workspace_run.go
- tfe/resource_tfe_workspace_run_test.go
- tfe/test-fixtures/basic-config/main.tf
- tfe/test-fixtures/config-with-error-during-plan/main.tf
- tfe/testing.go
- tfe/workspace_run_helpers.go
- tfe/workspace_run_helpers_test.go
- website/docs/r/workspace_run.html.markdown
Resource format:
```
resource "tfe_workspace_run" "root_A" {
workspace_id    = "ws_root_A_ID"
apply {
wait_for_run = true
manual_confirm = true
retry = true
retry_attempts = 2
retry_backoff_min = 2
retry_backoff_max = 15
}
destroy { 
wait_for_run = true
manual_confirm = true
retry = true
retry_attempts = 2
retry_backoff_min = 2
retry_backoff_max = 15
}
}
```
1.  _Sample test config (Be sure that the org and workspaces exist)_
```
resource "tfe_workspace_run" "root_A" {
workspace_id    = "ws_root_A_ID"
apply {
manual_confirm = true
retry = true
retry_attempts = 2
retry_backoff_min = 2
retry_backoff_max = 15
}
destroy { 
manual_confirm = true
retry = true
retry_attempts = 2
retry_backoff_min = 2
retry_backoff_max = 15
}
}
resource "tfe_workspace_run" "B_depends_on_A" {
workspace_id    = …
```
> Add tfe_workspace_run resource

- tfe/resource_tfe_variable.go
Per a lint (that I didn't notice in the initial tfe_variable PR somehow), plain (in)equality comparison of error values can give inaccurate results with go ≥ 1.13 "wrapped" errors. I don't think there's any likely code path for these go-tfe errors to arrive wrapped, but handling errors more resiliently sounds like a good habit to get into.
1.  Manage a tfe_variable with an apply.
2. Delete it manually in the TFC UI.
3. Do a terraform refresh or a terraform destroy. The run shouldn't error, because it should (deliberately) eat the 404. 
Alternately, just trust the go documentation that errors.Is does what it says it does. 
- [go errors.Is() …
> Replace some error comparisons with `errors.Is()`

- tfe/workspace_run_helpers.go
We're seeing periodic flappy test failures with a "run errored while applying run run-xxxxxxxxxxxxxxxx: transition not allowed" error. This commit adds some additional context logging to the site of that error, so we can investigate these failures more methodically the next time we see one.
This is a logging-only PR, whose effects can only be observed during an error that ought not to be happening. You cannot test it; only the universe can test it.
- [A representative test failure](https://github.com/hashicorp/terraform-provider-tfe/actions/runs/4961833602/jobs/8879123960?pr=881)
- [(dj khaled voice) ANOTHER ONE](https://github.com/hashicorp/terraform-provider-tfe/actions/runs/4941756232/jobs/8834683874?pr=878)
> Attach more info about tfe_workspace_run status when apply is rejected

- CHANGELOG.md
- tfe/resource_tfe_variable.go
- tfe/resource_tfe_variable_test.go
- website/docs/r/variable.html.markdown
Add a readable_value attribute to the tfe_variable resource. This aims to solve the usability problem where variable values, and all values which depend on them, are redacted from plan outputs regardless of if the variable is sensitive.
This new computed property would only be set if the variable is non-sensitive, and would not be redacted from outputs. Any other resource attribute depending on it (instead of on `value` directly) would also not be redacted from plan outputs.
1. Changing the value of a non-sensitive variable should update the readable_value
1. Changing the value of a sensitive variable should leave the readable_value blank
2. Changing a variable from sensitive to non-sensitive should set the readable_value
1. Changing a variable from non-sensitive to sensitive should clear …
> Add a readable_value attribute to tfe_variables

- CHANGELOG.md
- go.mod
- go.sum
- tfe/resource_tfe_workspace.go
* `r/tfe_workspace`: Retry during workspace safe delete if resources are still being processed.
Fixes #876 
- [Related PR](https://github.com/hashicorp/go-tfe/pull/703)
> Retry on workspace delete if still processing

- .github/actions/lint-provider-tfe/action.yml
- .github/actions/test-provider-tfe/action.yml
- .github/workflows/ci.yml
- .github/workflows/jira-issue-sync.yml
- .github/workflows/jira-pr-transition.yml
- .github/workflows/mkdocs.yml
- .github/workflows/nightly-tfe-test.yml
- .github/workflows/release.yml
Commit is the result of running HashiCorp's internal pinning tool, for all GitHub Actions workflows in the repo.
https://github.blog/changelog/2023-05-04-github-actions-all-actions-will-run-on-node16-instead-of-node12/
Note, this unsolicited PR is a courtesy and has not been tested before submission.  The PR should be evaluated and merged by its responsible team.
> Bump all GitHub Actions and pin; avoid deprecated Node 12

- website/docs/r/workspace_run.html.markdown
Issue #876 is fixed, so this workaround is no longer required.
Issue #876 is fixed, so this workaround is no longer required.
1.  Docs-only PR. 
- Issue #876 
- PR #881 
n/a
> Docs: tfe_workspace_run doesn't require workspace force_delete anymore

- CHANGELOG.md
- tfe/resource_tfe_organization_token.go
- tfe/resource_tfe_organization_token_test.go
- tfe/resource_tfe_team_token.go
- tfe/resource_tfe_team_token_test.go
- website/docs/r/organization_token.html.markdown
- website/docs/r/team_token.html.markdown
Allow an optional `expired_at` to be set on authentication API tokens via the provider.
- Ensure that organization and team API tokens that omit the optional `expired_at` field still work as expected.
- Ensure that an `expired_at` can be set on organization and team API tokens and that once set, the expiration date displays in the UI (`/app/org-name/authentication-tokens`) with the expiration date that was provided.
- Ensure that an invalid `expired_at` cannot be set on organization and team API tokens and that if attempted to be set, an error is returned.
- [Related go-tfe PR](https://github.com/hashicorp/go-tfe/pull/672)
- [API documentation](https://github.com/hashicorp/terraform-docs-common/pull/321)
```
=== RUN   TestAccTFEOrganizationToken_basic
--- PASS: …
```
> Add Optional Expiry to Auth Tokens

- CHANGELOG.md
- tfe/workspace_run_helpers.go
- website/docs/r/workspace_run.html.markdown
Fix for https://github.com/hashicorp/terraform-provider-tfe/issues/908
Replacement PR for https://github.com/hashicorp/terraform-provider-tfe/pull/910
_Remember to:_
```
$ TESTARGS="-run TestAccTFEWorkspaceRun" make testacc
TF_ACC=1 TF_LOG_SDK_PROTO=OFF go test $(go list ./... |grep -v 'vendor') -v -run TestAccTFEWorkspaceRun -timeout 15m
? …
```
> r/tfe_workspace_run: Ensure wait_for_run=false results in a fire-and-forget Run

- .github/actions/test-provider-tfe/action.yml
- .github/workflows/ci.yml
- .github/workflows/nightly-tfe-test.yml
* Set the TFC Admin API role tokens from the environment
* Bump the version of `hashicorp-forge/terraform-cloud-action/` to the version that includes a fix to outputting nested sensitive values.
The tokens should be set when CI is run (e.g., https://github.com/hashicorp/terraform-provider-tfe/actions/runs/5192171587/jobs/9360961243?pr=909#step:4:14)
> Set admin role tokens from the env

- website/docs/r/no_code_module.html.markdown
- website/docs/r/registry_module.html.markdown
Remove beta note for no_code modules from the docs.
```
$ TESTARGS="-run …
```
> remove no_code beta note in docs

- website/docs/d/workspace.html.markdown
Due to a formatting issue in the docs of _datasource_ `tfe_workspace`
https://github.com/hashicorp/terraform-provider-tfe/blob/9057f219ff967385dccdc1a7aa6ababa57269fbd/website/docs/d/workspace.html.markdown?plain=1#L37
the attribute `assessments_enabled` became part of the description for `auto_apply` .
n/a
- see: https://registry.terraform.io/providers/hashicorp/tfe/latest/docs/data-sources/workspace#auto_apply
n/a
...
```
> docs: Fixing issue for datasource tfe_workspace.assessments_enabled

- CHANGELOG.md
- go.mod
- go.sum
- tfe/resource_tfe_workspace_run.go
- tfe/workspace_run_helpers.go
- tfe/workspace_run_helpers_test.go
The changes in this PR checks potential terminal post plan statuses to ensure that a plan has been completely processed before proceeding to confirm the associated run. The terminal status changes depending on the post plan lifecycle that a run has. For example a plan can terminate at `planned` status or `cost_estimated` or `policy_checked`.
See issue for more details: https://github.com/hashicorp/terraform-provider-tfe/issues/898
[This PR depends on go-tfe PR#712](https://github.com/hashicorp/go-tfe/pull/712)
1.  _Workspace_run resource should create run as usual, the only way to produce the issue consistently is to force a run to remain in a status, e.g `policy_checked`, for a longer period of time such that workspace_run receives that status while polling the run. I achieved this by …
> Incorporate missing post plan terminal statuses to ensure plan is completely processed before attempting to confirm run

- CHANGELOG.md
- tfe/data_source_saml_settings.go
- tfe/data_source_saml_settings_test.go
- tfe/provider_next.go
- website/docs/d/saml_settings.html.markdown
This PR adds the datasource `tfe_saml_settings`. This change is required in order to add SAML settings support to the provider ([documentation](https://developer.hashicorp.com/terraform/enterprise/saml/configuration)). Follow up PR will be to add a resource for `tfe_saml_settings`.
- [List SAML settings API](https://developer.hashicorp.com/terraform/enterprise/api-docs/admin/settings#list-saml-settings)
- [Additions to go-tfe PR](https://github.com/hashicorp/go-tfe/pull/731)
```
$ TESTARGS="-run TestAccTFESAMLSettingsDataSource_basic" make testacc
TF_ACC=1 TF_LOG_SDK_PROTO=OFF go test $(go list ./... |grep -v 'vendor') -v -run TestAccTFESAMLSettingsDataSource_basic -timeout 15m
=== RUN …
```
> feat: add tfe_saml_settings data source

- CHANGELOG.md
- tfe/data_source_project.go
- tfe/data_source_project_test.go
Fixes https://github.com/hashicorp/terraform-provider-tfe/issues/882.
This PR performs case-insensitive matching when reading the list of projects from the [Projects List API](https://developer.hashicorp.com/terraform/cloud-docs/api-docs/projects#list-projects) for the `tfe_project` data source.
There was a potential issue where a project would not be found in the API response when the name attribute didn't match the case of the existing project exactly. For example, given an organization with a project 'Hello There', this data source would fail to read a matching project, despite its presence in the API response:
```
data "tfe_project" "foo" {
organization = "jbonhag"
name         = "hello there"
}
...
╷
│ Error: could not find project jbonhag/hello there
│ 
│   with …
```
> `d/tfe_project`: Ignore case when matching project name

- CHANGELOG.md
- tfe/data_source_policy_set.go
- tfe/data_source_policy_set_test.go
- tfe/resource_tfe_policy_set.go
- website/docs/d/policy_set.html.markdown
Project ids needs to be added to the policy set data source. 
- [Related PR](https://hashicorp.atlassian.net/jira/software/c/projects/TF/boards/593?modal=detail&selectedIssue=TF-6351&assignee=626ff58e2db308007023a9d8)
```
=== RUN   TestAccTFEPolicySetDataSource_basic
2023/07/26 11:13:33 [DEBUG] Configuring client for host "app.staging.terraform.io"
2023/07/26 11:13:33 [ERROR] Error reading CLI config or credentials file …
```
> Add project ids to policy sets data source

- CHANGELOG.md
- tfe/resource_tfe_admin_organization_settings.go
- tfe/resource_tfe_admin_organization_settings_test.go
This PR allows the admin org settings resource to provision properly in the case that its parent org has been manually deleted.
To reproduce the error reported above (and test that it has been resolved), follow these steps:
1. Provision an org and admin org settings with the following config:
**main.tf**
```hcl
resource "tfe_organization" "a-module-producer" {
name  = "my-org-116681"
}
resource "tfe_admin_organization_settings" "test-settings" {
organization                          = tfe_organization.a-module-producer.name
workspace_limit                       = 15
access_beta_tools                     = false
global_module_sharing                 = false
}
```
2. Delete the org manually
3. Run another plan and apply
I was unable to run the updated test …
> fix: handle deleted org when provisioning admin org settings

- CHANGELOG.md
- go.mod
- go.sum
- tfe/data_source_team_project_access.go
- tfe/data_source_team_project_access_test.go
- tfe/resource_tfe_team_project_access.go
- tfe/resource_tfe_team_project_access_test.go
- website/docs/r/team_project_access.html.markdown
With the release of customizable project permissions in TFC, we want people to be able to do use the new permissions in their terraform configs as well. There are two types of customizable permissions that can be set on team_projects, `project_access` which control access to certain abilities on the project itself as well as `workspace_access` permissions which effect all workspaces inside of the project.
This pr:
* Adds a new access level Custom option
* Adds the ability to read/write/update/import the new access levels and the corresponding `workspace_access` and `project_access` permissions.
* Makes it impossible to write config that has both an non-custom access level AND `workspace_access` and `project_access` permissions. This is done by using a [CustomizeDiff …
> TF-5569 add support for custom project permissions

- CHANGELOG.md
- tfe/data_source_variable_set.go
- tfe/data_source_variable_set_test.go
- website/docs/d/variable_set.html.markdown
The [variable set](https://registry.terraform.io/providers/hashicorp/tfe/latest/docs/data-sources/variable_set#attributes-reference) data source exports a workspace_ids attribute containing the set of workspace ids that a varset is assigned to. For completeness, we should update the TFE provider to export a list of project_ids as well.
- [Jira Ticket](https://hashicorp.atlassian.net/jira/software/c/projects/TF/boards/593?modal=detail&selectedIssue=TF-5323&assignee=626ff58e2db308007023a9d8)
```
/Users/netra.mali/go/go1.19.11/bin/go tool test2json -t /Users/netra.mali/Library/Caches/JetBrains/GoLand2023.1/tmp/GoLand/___TestAccTFEVariableSetsDataSource_full_in_github_com_hashicorp_terraform_provider_tfe_tfe.test -test.v -test.paniconexit0 -test.run ^\QTestAccTFEVariableSetsDataSource_full\E$ …
```
> Add project_ids to variable set data source

- CHANGELOG.md
- tfe/data_source_teams.go
- tfe/data_source_teams_test.go
- tfe/provider.go
- website/docs/d/teams.html.markdown
This PR adds a new data source ```tfe_teams``` which returns a list of all Team names in an Organization and a map of Team names to their respective IDs.
Closes [#913]
1. Using the config below:
```hcl
provider "tfe" {}
resource "tfe_team" "foo" {
name         = "foo"
organization = "test-org"
}
resource "tfe_team" "bar" {
name         = "bar"
organization = "test-org"
}
data "tfe_teams" "teams" {
organization = "test-org"
}
```
2. Should yield the following results:
```hcl
names = tolist([
"foo",
"bar",
])
ids = tomap({
"foo" = "foo-id"
"bar" = "bar-id"
})
```
```
...
```
> Add tfe_teams data source

- .github/pull_request_template.md
- .github/workflows/ci.yml
- CHANGELOG.md
- tfe/data_source_organization_membership.go
- tfe/data_source_organization_membership_test.go
- tfe/organization_members_helpers.go
- website/docs/d/organization_membership.html.markdown
This PR adds the `organization_membership_id` to the `tfe_organization_membership` data source. The original feature request wanted the data source to also allow the `user_id` arg, however the Organization Membership API doesn't accept `user_id` as a query param.
_Remember to:_
1.  Use the `d/tfe_organization_membership` with the following arguments:
```
data "tfe_organization_membership" "test" {
organization  = "my-org-name"
organization_membership_id = "ou-xxxxxxxxxxx"
}
```
- [go-tfe documentation](https://github.com/hashicorp/go-tfe/blob/main/organization_membership.go)
- [Organization Membership API](https://developer.hashicorp.com/terraform/cloud-docs/api …
> [TF-6330] add org membership ID attr to tfe_organization_membership

- website/docs/r/team_project_access.html.markdown
This addresses the docs issue reported in #1008
> Project Access field names should be underscored

- CHANGELOG.md
- docs/backwards-compatibility.md
- go.mod
- go.sum
- mkdocs.yml
- tfe/resource_tfe_team_project_access.go
Add docs related to TFE backwards compatibility. 
Fixes #996 
_Remember to:_
_Please run applicable acceptance tests locally and include the output here. See [testing.md](https://github.com/hashicorp/terraform-provider-tfe/blob/main/docs/testing.md) to learn how …
> Add TFE Backwards Compatibility contrib documentation

- go.mod
- go.sum
This PR uses the latest go-tfe `v1.33.0` release.
_Remember to:_
N/A
```
$ …
```
> [TF-9111] get go-tfe v1.33.0

- CHANGELOG.md
- internal/provider/data_source_policy_set.go
- internal/provider/data_source_policy_set_test.go
- website/docs/d/policy_set.html.markdown
excluded_workspace_ids needs to be added to the policy sets data source to accompany the workspace_policy_set_exclusion resource.
_Remember to:_
- [Related PR](https://github.com/hashicorp/terraform-provider-tfe/pull/1033)
```
--- PASS: TestAccTFEPolicySetDataSource_basic (6.74s)
PASS
--- PASS: …
```
> Add excluded_workspace_ids to policy sets data source

- website/docs/cdktf/csharp/r/registry_module.html.markdown
- website/docs/cdktf/go/r/registry_module.html.markdown
- website/docs/cdktf/java/r/registry_module.html.markdown
- website/docs/cdktf/python/r/registry_module.html.markdown
- website/docs/cdktf/typescript/r/registry_module.html.markdown
- website/docs/r/registry_module.html.markdown
This is a copy of this PR open by @sebhcp : https://github.com/hashicorp/terraform-provider-tfe/pull/1019
Missing backticks in the docs for `tfe_registry_module` result in `//_git/` once rendered by a browser. The expected string is `<ado organization>/<ado project>/_git/<ado repository>` instead.
https://registry.terraform.io/providers/hashicorp/tfe/latest/docs/resources/registry_module#identifier
Additionally, this PR adds Azure DevOps to the list of exceptions for VCS providers where `identifier` and `display_identifier` do not match.
> Docs: Fix missing backticks in 'tfe_registry_module' docs

- CHANGELOG.md
- README.md
- internal/provider/plugin_provider.go
- website/docs/index.html.markdown
Fixes #1088 
Providers implemented using the `terraform-plugin-go` library above version 0.19 or so must implement GetMetadata(), as part of supporting an optional memory usage improvement. See
https://github.com/hashicorp/terraform-plugin-sdk/issues/1234 for the start of a breadcrumb trail with more details about this whole effort.
Almost nobody actually implements providers using terraform-plugin-go, but we do! It's one of our THREE muxed-together providers, because we once needed to do something that was impossible in the SDK before the new framework existed. It's used for ONE data source, `tfe_outputs`.
This function was added (with a blank return value) in https://github.com/hashicorp/terraform-provider-tfe/pull/1046 and no one noticed a problem, presumably because acceptance tests …
> Fix Terraform 1.6 compat by finishing GetMetadata implementation

- website/docs/r/agent_pool.html.markdown
- website/docs/r/agent_pool_allowed_workspaces.html.markdown
In order to show a realistic example of using `tfe_agent_pool_allowed_workspaces`, `organization_scoped` should be set to `false`. I also updated a couple of references in that example to make it apply-able.
_Remember to:_
1.  Copy example from agent_pool_allowed_workspaces page
1.  Run `terraform apply`
1.  Config should not error
Example copied here for easy testing:
```hcl
resource "tfe_organization" "test-organization" {
name  = "my-org-name"
}
resource "tfe_workspace" "test-workspace" {
name         = "my-workspace-name"
organization = tfe_organization.test-organization.name
}
resource "tfe_agent_pool" "test-agent-pool" {
name                = "my-agent-pool-name"
organization        = tfe_organization.test-organization.name
organization_scoped = false
} …
```
> docs: organization_scoped should be set to false when using tfe_agent_pool_allowed_workspaces

- internal/provider/resource_tfe_project.go
- internal/provider/resource_tfe_project_test.go
Added TFE Project name validation to check for length and allowed characters at plan stage. The API docs specify a Project name can only include letters, numbers, spaces, -, and _. It must be at least 3 characters long and no more than 36 characters long.
Closes #1043 
```TESTARGS="-run TestAccTFEProject_invalidName" make testacc```
```
% TESTARGS="-run TestAccTFEProject_invalidName" make testacc 
TF_ACC=1 TF_LOG_SDK_PROTO=OFF go test $(go list ./... |grep -v 'vendor') -v -run TestAccTFEProject_invalidName -timeout 15m
=== RUN   TestAccTFEProject_invalidName
--- PASS: TestAccTFEProject_invalidName (1.08s)
PASS
ok      github.com/hashicorp/terraform-provider-tfe/internal/provider   3.375s
? …
```
> Add ValidateFunc to resc TFE_Project name

- internal/provider/data_source_saml_settings_test.go
- internal/provider/resource_tfe_saml_settings_test.go
These tests flake violently, because they're competing for control of global singleton state. The flakes show a distinctive pattern: they only flake when at least two of the resource test funcs end up on separate test runner partitions in CI, and re-running a single one failed partition alone always succeeds (because there's no concurrent competition anymore).
The fix is to make sure all of these tests ALWAYS run in serial on a single test runner partition. Smooshing into a single outer func and calling t.Run without t.Parallel seems like it should fit the bill.
changelog N/A, docs N/A (aside from code comments) 
1.  It doesn't flake in CI. 
N/A (problem only occurs in parallelized CI)
> Fix flaky TFESAMLSettings resource tests, add comments

- internal/provider/data_source_variable_set_test.go
This test was checking that the varset was connected to the project, but that connection is managed by a separate resource that was not a declared or inferred dependency of the data source. So, random chance determined whether the varset had been connected to the project yet by the time the data source was read.
The fix is to declare the dependency.
Changelog / docs updates are N/A.
1.  Test passes reliably in CI. 
A representative failure, from last night's nightlies: 
- [How not to flake](https://hashicorp.atlassian.net/wiki/spaces/TFENG/pages/2453340359/How+To+Avoid+Test+Flakiness) (confluence link, internal users only, sorry community friends)
see CI
> Fix flaky `TestAccTFEVariableSetsDataSource_full`

- .github/actions/test-provider-tfe/action.yml
- .github/workflows/ci.yml
- internal/provider/resource_tfe_saml_settings_test.go
Skip `tfe_saml_settings` resource tests in CI workflow.
_Remember to:_
1. Invoke CI test suite
2. Verify that `TestAccTFESAMLSettings_omnibus` does not appear in logs
3. OR run `go test ./... -list` in terminal and list of tests that output should not include `TestAccTFESAMLSettings_omnibus` …
> [TF-10363] skip SAML resource tests when CI runs

- CHANGELOG.md
- go.mod
- go.sum
Fixes release workflow build error. See go-tfe [release notes](https://github.com/hashicorp/go-tfe/releases/tag/v1.39.2).
> Upgrade go-tfe to v1.39.2

- CHANGELOG.md
- internal/provider/resource_tfe_registry_module.go
- internal/provider/resource_tfe_registry_module_test.go
- website/docs/r/registry_module.html.markdown
Add the following attributes to `RegistryModule` to support testing
- `publishing_mechanism`
- `vcs_repo.branch`
- `vcs_repo.tags`
- `test_config.tests_enabled`
_Remember to:_
1. Create a `RegistryModule`
1. Confirm the `publishing_mechanism` is `git_tag`
1. Set `vcs_repo.branch` to a branch on the git repository
1. Set `vcs_repo.tags` to `false`
1. Set `test_config.tests_enabled` to `true`
1. Perform changes
1. Confirm the `publishing_mechanism` is `branch`
1. Enjoy your registry module with tests enabled
- [go-tfe documentation](https://pkg.go.dev/github.com/hashicorp/go-tfe#TestConfig)
- [API documentation](https://developer.hashicorp.com/terraform/cloud-docs …
> [TF-9605] Add Private Registry Module Testing

- CHANGELOG.md
- internal/provider/data_source_organization.go
- internal/provider/data_source_organization_test.go
- website/docs/d/organization.html.markdown
This PR is a rebased copy of #1133 by @tmatilai, with an added test written by me. 
> The `organization` argument of all (?) other resources and data sources is already optional if defined in the provider configuration. This PR makes the `tfe_organization` data source to behave the same with the `name` argument.
>
> It actually already fetched the "current" organization with `name = ""`, but the `name` attribute was not written back to the data source.
_Remember to:_
```terraform
organization = "example"
}
data "tfe_organization" "current" {}
```
> [d/tfe_organization] Make name argument optional if configured for the provider [COMBINED]

- .golangci.yml
- CHANGELOG.md
- internal/provider/provider_custom_diffs.go
- internal/provider/resource_tfe_admin_organization_settings.go
- internal/provider/resource_tfe_agent_pool.go
- internal/provider/resource_tfe_no_code_module.go
- internal/provider/resource_tfe_oauth_client.go
- internal/provider/resource_tfe_organization_default_execution_mode.go
- internal/provider/resource_tfe_organization_membership.go
- internal/provider/resource_tfe_organization_module_sharing.go
- internal/provider/resource_tfe_organization_run_task.go
- internal/provider/resource_tfe_organization_token.go
- internal/provider/resource_tfe_policy.go
- internal/provider/resource_tfe_policy_set.go
- internal/provider/resource_tfe_project.go
- internal/provider/resource_tfe_registry_module.go
- internal/provider/resource_tfe_registry_module_test.go
- internal/provider/resource_tfe_sentinel_policy.go
- internal/provider/resource_tfe_ssh_key.go
- internal/provider/resource_tfe_variable_set.go
- internal/provider/resource_tfe_workspace.go
- internal/provider/resource_tfe_workspace_test.go
Closes #1152 
_Remember to:_
1. Create a workspace or any other resource that has an "organization" argument using a default org from the provider
2. Change the organization string in the provider config
3. Resources will now will be replaced. Previously, no change would be detected.
I couldn't think of a way to automate the testing of this customized diff. Ideas?
> Fix 'no changes detected' when provider default organization changes

- CHANGELOG.md
- internal/provider/attribute_helpers.go
- internal/provider/data_source_registry_gpg_key.go
- internal/provider/data_source_registry_gpg_key_test.go
- internal/provider/data_source_registry_gpg_keys.go
- internal/provider/data_source_registry_gpg_keys_test.go
- internal/provider/gpg_key.go
- internal/provider/provider_custom_diffs.go
- internal/provider/provider_next.go
- internal/provider/resource_tfe_registry_gpg_key.go
- internal/provider/resource_tfe_registry_gpg_key_test.go
- internal/provider/resource_tfe_variable.go
- website/docs/d/registry_gpg_key.html.markdown
- website/docs/d/registry_gpg_keys.html.markdown
- website/docs/r/registry_gpg_key.html.markdown
> Add resource and data sources for private registry GPG keys

- internal/provider/resource_tfe_workspace.go
- website/docs/d/workspace.html.markdown
- website/docs/r/organization_default_settings.html.markdown
- website/docs/r/workspace.html.markdown
- website/docs/r/workspace_settings.markdown
Updating several things I found unclear as a user, plus one thing I found unclear as a fellow maintainer.
Also, an important adjustment to some messaging: `r/tfe_workspace_settings` _cannot_ safely be used as a data source, because it interprets absence of each optional argument to explicitly set the workspace's corresponding overwrite to false. This makes me believe we need an overwrites object attribute added to `d/workspace`, but this PR defers that for later.
This is a follow-on from some post-merge comments I left in #1159. 
1.  n/a
- [Related PR](https://github.com/hashicorp/terraform-provider-tfe/pull/1159)
> Docs tweaks for tfe_workspace_settings and friends

- CHANGELOG.md
- internal/provider/resource_tfe_admin_organization_settings.go
- website/docs/r/admin_organization_settings.markdown
Fixes #1182 -- all other resources are marked computed except for this one
_Remember to:_
```
organization = "hashicorp"
}
resource "tfe_admin_organization_settings" "test-company" {
workspace_limit       = 0
access_beta_tools     = false
global_module_sharing = false
}
```
This config should work when applied. Also supports changing the provider default, which forced re-create
> 'organization' resource schema should always be computed

- website/docs/d/github_installation.html.markdown
Correctly specify what each argument is and where that data might be found on Github.
> Clarify GHA installation arguments

- CHANGELOG.md
- internal/provider/resource_tfe_workspace_settings.go
I made a mistake with `tfe_workspace_settings` compatibility. The "unknownIfExecutionModeUnset" plan modifier was supposed to actually check for unsetting before changing the planned value of execution_mode when it had no overwrites to consult.
Tested on TFC and TFE v202308-1
_Remember to:_
1. Use this config. Run terraform apply twice. It works fine on the last couple of TFE releases (this is why there are no acceptance tests) but on v202308-1 the second plan fails
<details><summary>Sample Config</summary>
<pre>
terraform {
required_providers {
tfe = {
source = "hashicorp/tfe"
version = "0.51.0"
}
}
}
}
resource tfe_organization "org" {
name = "test-IPL5516-tfe"
email = "bcroft@hashicorp.com"
}
// 1
resource "tfe_agent_pool" "pool" {
name         = "pool"
organization = …
> Fixes older TFE, tfe_workspace_settings always unsets execution_mode

- CHANGELOG.md
- internal/provider/provider_custom_diffs.go
- internal/provider/provider_custom_diffs_test.go
- internal/provider/resource_tfe_registry_gpg_key.go
Fixes #1189 
See issue for reproduction steps. #1185 will need to be rebased on top of this.
> Fix plan modification error when updating tfe_registry_gpg_key

- internal/provider/resource_tfe_workspace.go
The message "agent_pool_id must be provided when execution_mode is 'agent'" was displayed when the execution mode was remote, and the agent pool ID was set, which was confusing.
Fixes: #1203
> fix: Swap error messages in validateAgentExecution

- CHANGELOG.md
- internal/provider/resource_tfe_workspace.go
A customer reported this panic via support. Sebastian clued me in that this is an extremely cursed known behavior in sdkv2, where it munges a list of strings containing one empty string into a list containing a single nil, so you must do a type assert on the inner elements.
Note that the Update function already did exactly this (around line 655 or so)! So there was no panic if you changed trigger_prefixes to the fatal value after the resource already existed.
_Remember to:_
Config:
```terraform
hostname = <YOURS>
}
resource "tfe_workspace" "ex-splodo" {
auto_apply                    = true
file_triggers_enabled         = true
name                          = "jan24-trigger-prefixes-panic-repro"
organization                  = <YOURS>
queue_all_runs                = true …
```
> r/tfe_workspace: Fix panic when `trigger_prefixes = [""]`

- website/docs/cdktf/csharp/r/team_project_access.html.markdown
- website/docs/cdktf/go/r/team_project_access.html.markdown
- website/docs/cdktf/java/r/team_project_access.html.markdown
- website/docs/cdktf/python/r/team_project_access.html.markdown
- website/docs/cdktf/typescript/r/team_project_access.html.markdown
- website/docs/r/team_project_access.html.markdown
Docs for `tfe_team_project_access` contain the following typo:
>The following permissions apply to all _workpsaces_
_Remember to:_ …
> Docs: Fix typo in 'tfe_team_project_access'

- CHANGELOG.md
- internal/provider/data_source_no_code_module.go
- internal/provider/data_source_no_code_module_test.go
- internal/provider/provider_next.go
- website/docs/d/no_code_module.html.markdown
This PR adds a new data source `tfe_no_code_module` for getting basic info on a single no-code module.
_Remember to:_
1.  Have an existing no-code provisioning module
1.  Get it's ID (either with the API or visiting the no-code module's settings on app.terraform.io)
1.  Use the ID in the data sources' ID field
1.  Enjoy?
API Docs:
- https://developer.hashicorp.com/terraform/cloud-docs/api-docs/no-code-provisioning#read-a-no-code-module-s-properties
```
$ ENABLE_BETA=1 TESTARGS="-run=TestAccTFENoCodeModuleDataSource_public -v" make testacc
TF_ACC=1 TF_LOG_SDK_PROTO=OFF go test $(go list ./... |grep -v 'vendor') -v -run=TestAccTFENoCodeModuleDataSource_public -v -timeout 15m
testing: warning: no tests to run
PASS
ok …
```
> Data source no-code module

- CHANGELOG.md
- internal/provider/resource_tfe_workspace.go
- internal/provider/resource_tfe_workspace_test.go
- website/docs/r/workspace.html.markdown
A boolean value that, when set to true, allows additional unmanaged tags to be applied to this workspace outside of terraform without being overwritten by `tag_names` config. This creates exceptional behavior in terraform with respect to `tag_names` and is generally not recommended. But given that the alternative is to ignore all updates to tags after they are created, or not be able to mix unmanaged and managed tags at all, it seems like a reasonable feature until we separate the tag resource altogether
> Adds `ignore_additional_tag_names` to tfe_workspace resource

- CHANGELOG.md
- internal/provider/resource_tfe_registry_module.go
This fixes a bug that always forced a registry module to always be recreated when a default organization is not provided..
_Remember to:_
1. Perform 
````
terraform apply
````
with the below code (fill out your values for identifiers and oauth_token_id):
````
terraform {
required_providers {
tfe = {
source = "hashicorp/tfe"
version = "0.49.0"
}
}
}
resource "tfe_registry_module" "test-registry-module" {
vcs_repo {
display_identifier = "your/display-identifier"
identifier         = "your/identifier"
oauth_token_id     = "ot-oauth-token-id"
}
}
````
2. Change the version of the provider to 0.51.0
3. Perform 
````
terraform init -upgrade
````
4. Perform
````
terraform plan
````
*Expected behavior*
Since the resource is not changed but only the …
> [IPL-5689] Revert the fix for no changes detected when provider default org changes on Registry Modules

- CHANGELOG.md
- internal/provider/resource_tfe_registry_module.go
- internal/provider/resource_tfe_registry_module_test.go
The Registry Module `Delete` API deprecated and replaced three endpoints (see [docs](https://developer.hashicorp.com/terraform/enterprise/api-docs/private-registry/modules#delete-a-module)). This ticket is a follow-on, after refactoring the API calls in go-tfe ([PR](https://github.com/hashicorp/go-tfe/pull/847)) and releasing those changes in [v1.45.0](https://github.com/hashicorp/go-tfe/releases/tag/v1.45.0).
_Remember to:_
1. Create two registry module resources
2.  Make `Name` attr for both resources identical
3.  Make `Provider` attr for both resources different
4.  Delete one registry module
5. Verify the resource was deleted
- [go-tfe …
> [TF-13376] Refactor registry module delete method

- internal/provider/data_source_organization_run_task_test.go
- internal/provider/data_source_workspace_run_task_test.go
- internal/provider/provider.go
- internal/provider/provider_next.go
- internal/provider/resource_tfe_organization_run_task.go
- internal/provider/resource_tfe_organization_run_task_test.go
- internal/provider/resource_tfe_workspace_run_task_test.go
- internal/provider/validators/is_url_https.go
Requires #1291 to be merged first
This commit migrates the tfe_organization_run_task resource to the newer
plugin model. It uses a schema v0 as there is no difference in schema.
Later changes will migrate the other resource and data source objects.
As this is a no-op as far as customer changes go, no changelog is required.
1. This should be a noop. so all acceptance and unit tests will pass.
* Create a `tfe_resource_run_task` resource with the existing provider
* Then re-run terraform plan using the newer version, which includes this PR
* Note that no state changes will be present. Again, this should be a noop
N/A
Local testing...
```
?   	github.com/hashicorp/terraform-provider-tfe/internal/provider/validators	[no test files]
=== RUN   TestAccTFEOrganizationRunTaskDataSource_basic …
```
> Migrate tfe_organization_run_task to plugin model 

- .github/workflows/nightly-tfe-test.yml
Timeouts are resulting workflow failures since runs are taking longer than 10m to complete.
> Bump nightly instance job timeout to 20m

- internal/provider/provider.go
- internal/provider/provider_next.go
- internal/provider/resource_tfe_workspace_run_task.go
- internal/provider/resource_tfe_workspace_run_task_test.go
This commit migrates the tfe_workspace_run_task resource to the newer
plugin model. It uses a schema v0 as there is no difference in schema.
Later changes will migrate the other data source objects.
As this is a no-op as far as customer changes go, no changelog is required.
1. This should be a noop. so all acceptance and unit tests will pass.
* Create a `tfe_workspace_run_task` resource with the existing provider
* Then re-run terraform plan using the newer version, which includes this PR
* Note that no state changes will be present. Again, this should be a noop
N/A as this is an internal refactor
```
?   	github.com/hashicorp/terraform-provider-tfe/internal/provider/validators	[no test files]
=== RUN   TestAccTFEWorkspaceRunTaskDataSource_basic
2024/03/27 11:38:59 [DEBUG] Configuring …
```
> Migrate tfe_workspace_run_task to plugin model

- website/docs/r/organization_default_settings.html.markdown
correct resource name typo in `tfe_organization_default_settings` import doc
Issue https://github.com/hashicorp/terraform-provider-tfe/issues/1220
> correct resource name in import doc

- .golangci.yml
This PR adds a rule to prevent CI linters from blocking a merge where WorkspaceRunTask.Stage is used. The `Stage` field was only recently deprecated. 
See how it is currently used [here](https://github.com/hashicorp/terraform-provider-tfe/blob/main/internal/provider/resource_tfe_workspace_run_task.go#L84).
_Remember to:_
- [Related …
> [TF-14896] Add rule to ignore linter

- .goreleaser.yml
Update in accordance with: [[Memo] TF-034: Adding LICENSE File to Terraform Provider Release Archives](https://go.hashi.co/memo/tf-034)
> Adding LICENSE File to TF Provider Release Archives

- internal/provider/resource_tfe_policy.go
- internal/provider/resource_tfe_policy_test.go
- internal/provider/resource_tfe_sentinel_policy.go
- internal/provider/resource_tfe_sentinel_policy_test.go
(cherry picked from commit 32c3d86dce16e5d38f7bb6f39d5820d5b2ed4733)
Because of the changes made to the go-tfe policy.Enforce, we're getting linter errors on this deprecated array. We've created a ticket with the compliance team to look at how we can make this backwards compatible with older versions of TFE, in the meantime we're going to ignore these errors
_Remember to:_
N/A~Update the [Change Log](https://github.com/hashicorp/terraform-provider-tfe/blob/main/docs/changelog-process.md)~
N/A~Update the [Documentation](https://github.com/hashicorp/terraform-provider-tfe/blob/main/docs/changelog-process.md#updating-the-documentation)~
- [Compliance ticket](https://hashicorp.atlassian.net/browse/TF-15241)
> chore: ignore linter complaints for deprecated policy.Enforce

- CHANGELOG.md
- internal/provider/resource_tfe_project.go
- internal/provider/resource_tfe_project_test.go
This PR increases the project name character length from 36 to 40 character.
_Remember to:_
Covered by integration tests
- [Related PR](https://hashicorp.atlassian.net/browse/TF-11739)
> Updated project name limit from 36 to 40 characters

- .github/actions/lint-provider-tfe/action.yml
- .github/actions/test-provider-tfe/action.yml
- .github/workflows/ci.yml
- .github/workflows/create-release-pr.yml
- .github/workflows/nightly-tfe-test.yml
- internal/provider/helper_test.go
- internal/provider/provider_test.go
- internal/provider/resource_tfe_policy_set_test.go
- internal/provider/resource_tfe_registry_module_test.go
- internal/provider/resource_tfe_test_variable_test.go
- internal/provider/resource_tfe_workspace_run_test.go
We are temporarily enabling CI to test against an enterprise-configured instance (TFE). These do not suffer from the same concurrency issues as our cloud-configured test instances. What this means for the time being is that cloud-only tests must be run manually and the results added to the PR description/comment. 
_Remember to:_
- …
> Temporarily enable CI to test against enterprise instance

- CHANGELOG.md
- internal/provider/resource_tfe_registry_module.go
- internal/provider/resource_tfe_registry_module_test.go
- website/docs/r/registry_module.html.markdown
Support for specifying a branch based modules `initialVersion` is missing from the tfe provider - if it is missing, we default to a version of `0.0.0`. This PR addresses that by adding support for an `initial_version` string. This PR also removes the `skipUnlessBeta` flag from the tf test and branch based modules tests.
_Remember to:_
```
resource "tfe_organization" "foobar" {
name  = "tst-terraform-%d"
}
resource "tfe_oauth_client" "foobar" {
organization     = tfe_organization.foobar.name
api_url          = "https://api.github.com"
http_url         = "https://github.com"
oauth_token      = "%s"
service_provider = "github"
}
resource "tfe_registry_module" "foobar" {
organization     = tfe_organization.foobar.name
vcs_repo {
display_identifier = "%s"
identifier …
```
> Support initial_version for creating branch based modules

- CHANGELOG.md
- internal/provider/resource_tfe_registry_module.go
- internal/provider/resource_tfe_registry_module_test.go
This PR prevents constant diff even after a successful apply of `resource_tfe_registry_module` resource. It also fixes the following cases:
- when `tags` is set to true and `branch` is specified, the API ignores `tags` value and uses the specified `branch`. This leads to a constant diff attempt. Solution added is to match the API by verifying that either `branch` or `tags` is set but not both
- previously, the `tags` value was never sent during the Create request, this PR ensures that the specified `tags` value is always sent in the request
- `test_config` was only updated into state when the test config response is non-empty leading to never unsetting the value in state. Added fix to always update the test_config state to reflect api response.
- adds some tests to catch previously …
> prevent constant diff even after a successful apply of resource_tfe_registry_module resource

- CHANGELOG.md
- internal/provider/resource_tfe_team.go
- internal/provider/resource_tfe_team_test.go
- website/docs/r/team.html.markdown
This PR adds support that will allow the manage_agent_pools organization access setting to be set on teams via the provider.
_Remember to:_
1. `manage_agent_pools` should default to false for new teams.
2. If `manage_agent_pools` is omitted, they should default to false.
3. `manage_agent_pools` should be able to be set or unset via the provider.
- [go-tfe PR](https://github.com/hashicorp/go-tfe/pull/901)
- [JIRA](https://hashicorp.atlassian.net/browse/TF-15257)
_Please run applicable acceptance tests locally and include the output here. See [testing.md](https://github.com/hashicorp/terraform-provider-tfe/blob/main/docs/testing.md) to learn how to run acceptance …
> [#TF-15257] add manage-agent-pools to team organization access

- CHANGELOG.md
- internal/provider/data_source_organization_run_task_global_settings.go
- internal/provider/data_source_workspace_run_task.go
- internal/provider/data_source_workspace_run_task_test.go
- internal/provider/helper_test.go
- internal/provider/provider_next.go
- internal/provider/resource_tfe_organization_run_task_global_settings.go
- internal/provider/resource_tfe_organization_run_task_global_settings_test.go
- internal/provider/resource_tfe_workspace_run_task.go
- internal/provider/resource_tfe_workspace_run_task_schemas.go
- website/docs/d/organization_run_task_global_settings.html.markdown
- website/docs/d/workspace_run_task.html.markdown
- website/docs/r/organization_run_task_global_settings.html.markdown
- website/docs/r/workspace_run_task.html.markdown
This PR;
* Updates the workspace run task resource and datasource to deprecate the `stage` attribute
in favour of the new `stages` attribute. This also includes a state version update
* Adds a new organization_run_task_global_settings resource and datasource for managing the
global settings of a Run task. This does require the HCP Terraform/TFE instance to support
global run tasks. The provider does attempt to error gracefully if a user is trying to use
this feature if it's unsupported.
_Remember to:_
Handled by acceptance tests
- [go-tfe documentation](https://github.com/hashicorp/go-tfe/pull/865)
- [API documentation](https://developer.hashicorp.com/terraform/cloud-docs/api-docs/run-tasks/run-tasks)
In this PR.
> Add Global Run Task support 

- internal/provider/provider_test.go
- internal/provider/resource_tfe_registry_module_test.go
Removes instances of `skipUnlessAfterDate` related to previously broken github token
> Bump date for instances of `skipUnlessAfterDate` related to GH Token Issue

- .gitignore
- go.mod
- go.sum
- internal/provider/provider_next.go
- internal/provider/resource_tfe_stack.go
- internal/provider/resource_tfe_stack_test.go
- internal/provider/stack.go
- website/docs/r/stack.html.markdown.md
Adds BETA support for Stacks as tfe_stack
See documentation for details.
NOTE: This should not be merged until the linked go-tfe PR is released.
_Remember to:_
<details><summary>Details</summary>
<p>
<code>
}
resource "tfe_project" "example" {
name = "example-project"
organization = "example-org"
}
resource "tfe_oauth_client" "gh" {
organization = "example-org"
name = "gh-example"
api_url          = "https://api.github.com"
http_url         = "https://github.com"
oauth_token      = "ghp_SECRET_TOKEN"
service_provider = "github"
organization_scoped = true
}
resource "tfe_stack" "example" {
name = "example-renamed"
description = "the worst stack ever"
project_id = tfe_project.example.id
vcs_repo {
identifier = "hashicorp-guides/pet-nulls-stack"
oauth_token_id = …
> New resource: tfe_stack

- CHANGELOG.md
- internal/provider/provider_next.go
- internal/provider/resource_tfe_project.go
- internal/provider/resource_tfe_team_project_access.go
- internal/provider/resource_tfe_workspace_settings.go
TFC/E is making changes to ID formats and as the API does its own ID validation the validations here were superfluous.
Removing in favor of letting the API return errors.
_Remember to:_
1. There should be no validations on project/workspace/agent pool IDs, arbitrary strings should be accepted
```
...
```
> Remove resource ID validations

- CHANGELOG.md
- internal/provider/resource_tfe_workspace.go
- internal/provider/resource_tfe_workspace_test.go
tfe_workspace html_url attribute is not planned to be recomputed when the name changes, causing the attribute to lag behind the name update apply.
_Remember to:_
Example config:
```
provider "tfe" {}
resource "tfe_workspace" "a_new_workspace" {
organization = "bcroft"
name                = "ws-1"
queue_all_runs      = false
assessments_enabled = false
}
output "workspace-url" {
value = tfe_workspace.a_new_workspace.html_url
}
```
To test, change the name of the workspace and re-apply. The output would not be modified until the next apply.
Closes #1422 
_If you are an external …
> Plan to recompute html_url when name changes

- internal/provider/provider_test.go
- internal/provider/resource_tfe_registry_module_test.go
The remedy for this problem requires intervention from IT, which is an ongoing process. This PR will at least unblock CI until that comes through.
[Related Jira Ticket tracking the fix](https://hashicorp.atlassian.net/browse/TF-18315?atlOrigin=eyJpIjoiNmMwYWEyNGQ3MjJlNGY4MjliMGRiYzgxYTY0ZjA0MmQiLCJwIjoiaiJ9)
> Bump date for skipping failing tests related to GH webhook limit

- CHANGELOG.md
- internal/provider/data_source_project.go
- internal/provider/data_source_project_test.go
- website/docs/d/project.html.markdown
This PR is to emit the names of all the workspaces within a project. My use case is is follows:
- I have a known project name and want to act on certain workspaces within it (based on a workspace name suffix)
- I can use tfe_project to look up the IDs of all the workspaces in that project
- I don't have a clean way to look up those workspaces by ID to get their names
So, this allows me to capture the workspace names within a project and act on them. If there is a better alternative, let me know!
_Remember to:_
1. Create a project called `foo`
2. Create a `tfe_project` data source with name `foo`, e.g.:
``` 
data "tfe_project" "foo" {
organization = "my-org"
name = "foo"
}
output "project" {
value = data.tfe_project.foo
}
```
3. Run `terraform plan`/`terraform apply`
4. Output should …
> d/tfe_project: Output workspace names

- CHANGELOG.md
- go.mod
- go.sum
- internal/provider/resource_tfe_team.go
- internal/provider/resource_tfe_team_test.go
- website/docs/r/team.html.markdown
This PR adds a new team permission - `AllowMemberTokenManagement` - to the `Team` block. `AllowMemberTokenManagement` is `true` by default and can only be managed by Owners or users with "Manage Teams" permissions. Additionally, this PR adds tests and documentation for the new permission.
_Remember to:_
1. `allow_member_token_management` should default to `true` for new teams.
2. If `allow_member_token_management` is omitted, it should default to`true`.
3. `allow_member_token_management` should be able to be set or unset via the provider.
- [go-tfe PR](https://github.com/hashicorp/go-tfe/pull/922)
- [API documentation](https://developer.hashicorp.com/terraform/cloud-docs/users-teams-organizations/permissions#allow-member-token-management)
```
$ TESTARGS="-run TestAccTFEWorkspace" make …
```
> Add AllowMemberTokenManagement to Team

- CHANGELOG.md
- internal/provider/resource_tfe_team.go
- website/docs/r/team.html.markdown
Interacting with secret teams was recently changed to require explicit access or owner access. This default, when used in conjunction with an unprivileged token, conflicts with the computed default. In that scenario, the default would continuously conflict with the platform on each plan.
_Remember to:_
1. Ensure you cannot interact with secret teams (no owner token, no explicit access to secret teams)
2. Apply this config
3. Without this change, each subsequent plan shows an update that is never applied
```
resource "tfe_team" "admin" {
name        = "TF-project-admins"
}
```
> Remove 'secret' default from `tfe_team` because it requires explicit or owner access

- CHANGELOG.md
- internal/provider/client_capabilites.go
- internal/provider/client_capabilites_test.go
- internal/provider/resource_tfe_workspace_run_task.go
- internal/provider/resource_tfe_workspace_run_task_schemas.go
- internal/provider/resource_tfe_workspace_run_task_test.go
Fixes #1456
Previously the schema for workspace run tasks was updated for the new stages
property however it wasn't actually used. This commit updates the Workspace
Run Task resource to aware of the stages attributes. In particular;
* Attempts to detect if the remote service supports the stages property. Stages
is available in HCP Terraform and TFE v202404-1 onwards.
* Munges the Stages and Stage attribtue depending on the remote capability.
* Emits a warning about the remove server capability.
* Adds some automated tests. Unfortunately we can't test older TFE versions,
to ensure the munging is correct, however manual testing was performed in
a local development enivronment to confirm the behaviour.
* Removes the default value for the Stage property in the Schema. This will
not cause …
> Use the stages attribute for the Workspace Run Task resource

- .github/workflows/ci.yml
- internal/provider/resource_tfe_notification_configuration_test.go
Follow-up work to [this PR](https://github.com/hashicorp/terraform-provider-tfe/pull/1467) that migrated away from using `example.com` for the testing run task url.
Standardized use of `http://testing-mocks.tfe:22180/runtasks/pass` between CI and Nightly tests, as well as fixes for the failing tests that popped up from using this new URL. Turns out we were just incorrectly formatting certain query params.
Fixed failing tests
> Standardize use of testing-mocks.tfe for `run_tasks_url` between CI and Nightly tests

- .github/workflows/ci.yml
Removing test runner concurrency due to multiple test failures around invoking runs against our CI instance. 
_Remember to:_ …
> Remove test runner concurrency

- CHANGELOG.md
- internal/provider/helper_test.go
- internal/provider/resource_tfe_organization_run_task.go
- internal/provider/resource_tfe_organization_run_task_global_settings_test.go
- internal/provider/resource_tfe_organization_run_task_test.go
- internal/provider/resource_tfe_workspace_run_task.go
- internal/provider/resource_tfe_workspace_run_task_test.go
Previously if Workspace Run Tasks, Organiaztion Run Tasks or global settings
were managed by TF and deleted server-side, the TF apply/plan  would error.
However this stopped resources being removed or ignored.
This commit modifies the Read methods to remove the previous resource state
when the object no longer exists (a 404 response). The Read methods still
raise if another error type is received (e.g. 500 or Network error).
_Remember to:_
Handled by acceptance tests
Fixes issue #1497
> Do not error when reading workspace tasks when that no longer exists

- CHANGELOG.md
- internal/provider/resource_tfe_policy.go
- internal/provider/resource_tfe_policy_test.go
Fixes #1407
Previously the tfe_policy resource could only set policies to advisory. This commit updates the update function to properly switch path for the policy enforcement name based on the kind. This was due to the previous comparison not comparing the same types so it always failed.
_Remember to:_
Handled by additional acceptance test
> Update enforcement mode for OPA policy resources

- CHANGELOG.md
- internal/provider/resource_tfe_workspace.go
- internal/provider/resource_tfe_workspace_settings.go
- internal/provider/resource_tfe_workspace_settings_test.go
- internal/provider/workspace_helpers.go
- website/docs/r/workspace.html.markdown
- website/docs/r/workspace_settings.markdown
Moving this attribute to the auxiliary workspace resource removes possible mutual dependence when adding workspace IDs to tfe_workspace resources.
_Remember to:_
This is the most 👍  open issue on the repo.
Try this config:
```terraform
provider "tfe" {}
resource "tfe_organization" "example" {
name  = "example-remote-state"
email = "you@example.com"
}
resource "tfe_workspace" "test" {
for_each     = toset(["qa","production"])
name         = "${each.value}-test"
organization = tfe_organization.example.name
}
resource "tfe_workspace_settings" "test-settings" {
for_each                  = toset(["qa","production"])
workspace_id              = tfe_workspace.test[each.value].id
global_remote_state       = false
remote_state_consumer_ids = toset(compact([each.value == "production" ? …
```
> Adds remote state consumers to tfe_workspace_settings

- CHANGELOG.md
- internal/provider/data_source_variable_set.go
- internal/provider/data_source_variable_set_test.go
- internal/provider/resource_tfe_variable_set.go
- internal/provider/resource_tfe_variable_set_test.go
- website/docs/d/variable_set.html.markdown
- website/docs/r/project_variable_set.html.markdown
- website/docs/r/variable_set.html.markdown
- website/docs/r/workspace_variable_set.html.markdown
This PR adds `parent_project_id` to the variable sets resource and data source, which specifies the ID of the project that should own the varset. Project-owned varsets cannot also be global varsets, and if the varset is updated to have a different parent project, then the varset under the old project should be deleted and then recreated under the new project.
_Remember to:_
1. Create a project-owned varset and an org-owned varset.
1. Validate that the project-owned varset has the expected project ID set and the org-owned does not.
1. Get the project-owned varset as a data source and output it.
1. Validate that the outputted data source has the expected project ID set.
```
resource "tfe_project" "test_project" {
name         = "ProjectOwnedVarSetProviderProject"
organization = …
```
> Add support for project-owned variable sets

- .github/actions/test-provider-tfe/action.yml
Test suites have been timing out because it takes longer than 30m to complete. This PR will bump it up to 60m. 
```
...
```
> Bump the test suite timeout to 60m

- internal/provider/resource_tfe_workspace_settings.go
- internal/provider/resource_tfe_workspace_settings_test.go
When workspace ID is unknown, we validate during planning that it's not listed twice in remote state consumers. This is problematic when creating more than one workspace in a plan.
_Remember to:_
See #1568 for sample config
```
$ TESTARGS="-run TestAccTFEWorkspaceWithSettings" make testacc
=== RUN   TestAccTFEWorkspaceWithSettings
2025/01/21 13:46:16 [DEBUG] Configuring client for host "tfcdev-4483a00f.ngrok.app"
2025/01/21 13:46:16 [DEBUG] Service discovery for tfcdev-4483a00f.ngrok.app at https://tfcdev-4483a00f.ngrok.app/.well-known/terraform.json
--- PASS: TestAccTFEWorkspaceWithSettings (7.86s)
PASS
ok      github.com/hashicorp/terraform-provider-tfe/internal/provider   8.524s
```
> Don't ensure workspace ID is in collection when it is unknown

- CHANGELOG.md
- README.md
- website/docs/index.html.markdown
Changelog and doc updates for v0.63.0
> Update latest version to v0.63.0

- CHANGELOG.md
- go.mod
- go.sum
- internal/provider/resource_tfe_stack.go
Fixes an issue with the experimental stack resource's vcs_repo block when using GitHub App installation. Updates the go-tfe dependency to resolve a serialization issue with JSONAPI annotated struct fields.
_Remember to:_
1. Obtain github_app_installation_id static value or obtain with data block (requires user authorization of github app).
1. Provision a stack with vcs_repo block using github_app_installation_id attribute.
2. Apply changes, verify a stack was provisioned correctly with github app integration.
- [Related go-tfe PR#1029](https://github.com/hashicorp/go-tfe/pull/1029)
- [Related go-tfe PR#1039](https://github.com/hashicorp/go-tfe/pull/1039)
- …
> fix(stacks/vcs): update stack create/update options to use new json annotated VCSRepoOptions struct

- CHANGELOG.md
- internal/provider/data_source_team_project_access.go
- internal/provider/data_source_team_project_access_test.go
- internal/provider/resource_tfe_team_project_access.go
- internal/provider/resource_tfe_team_project_access_test.go
- website/docs/r/team_project_access.html.markdown
This PR adds `variable_sets` to the `project_access` of `tfe_team_project_access`, allowing users to set the project variable set permission of a team when access is set to `custom`.
This feature has not been released to GA yet, so I've labeled it as do not merge for now.
_Remember to:_
1.  Create a team and a project.
1. Assign the team custom access and set `variable_sets`.
1. Get the team project access as a data source and output it.
1. Validate for the expected outputted value for `variable_sets`
1. Validate in the UI or API that `variable_sets` is set to the expected value.
```
resource "tfe_project" "test" {
name         = "TeamProjectVarSetProvider"
organization = data.tfe_organization.test.name
}
resource "tfe_team" "custom" {
name         = …
```
> Add support for the custom project variable set permission 

- CHANGELOG.md
- internal/provider/resource_tfe_workspace_settings.go
Previously,  remote state consumers was always fetched regardless of the global remote state setting. This means that, when `global_remote_state` was true, the provider fetches all the workspaces within that org as its remote state consumers. For users with large number of workspaces, this resulted in significant fetch time.
With this PR, remote state consumers are only fetched when state is shared with a subset of existing workspaces, i.e when the `global_remote_state` is false.
Caveat: Note that if the list of remote state consumers is large, say >100s, then the fetch time will also increase.
_Remember to:_
1.  Create multiple `tfe_workspace` and `tfe_workspace_settings` resources
1.  Set the `global_remote_state` to false, add some workspaces to the `remote_state_consumer_ids`, only …
> Only fetch remote state consumers when global remote state is false

- internal/provider/data_source_team_project_access_test.go
- internal/provider/resource_tfe_team_project_access_test.go
Now that the feature is GA and the feature flag is removed from atlas, we can remove the beta flags from test.
_Remember to:_
Tests all pass.
- [Jira](https://hashicorp.atlassian.net/browse/TF-23829)
> Remove beta flag for custom project variable set permission

- CHANGELOG.md
- internal/provider/ephemeral_resource_team_token.go
- internal/provider/ephemeral_resource_team_token_test.go
- internal/provider/provider_next.go
- website/docs/ephemeral-resources/team_token.html.markdown
Allow users to [create an ephemeral resource](https://developer.hashicorp.com/terraform/plugin/framework/ephemeral-resources) for `tfe_team_token`, so that the org token is not stored in the Terraform state file and can be handled securely and temporarily during Terraform operations.
_Remember to:_
1. Create a terraform configuration that has child module
1. In that module, try out a config similar to this:
```
resource "tfe_team" "example" {
organization = "my-org-name"
name = "team-test"
}
ephemeral "tfe_team_token" "example" {
team_id = tfe_team.example.id
}
output "my-team-token" {
value       = ephemeral.tfe_team_token.this.token
ephemeral   = true
}
```
Then init and apply the configuration.
The state file should not include the ephemeral resource.
_Please run applicable acceptance …
> feat: add tfe_team_token ephemeral resource

- CHANGELOG.md
- GNUmakefile
- internal/provider/ephemeral_resource_organization_token.go
- internal/provider/ephemeral_resource_organization_token_test.go
- internal/provider/ephemeral_resource_team_token_test.go
- internal/provider/provider_next.go
- website/docs/ephemeral-resources/organization_token.html.markdown
Allow users to [create an ephemeral resource](https://developer.hashicorp.com/terraform/plugin/framework/ephemeral-resources) for `tfe_organization_token`, so that the org token is not stored in the Terraform state file and can be handled securely and temporarily during Terraform operations.
_Remember to:_
1. Create a terraform configuration that has child module
1. In that module, try out a config similar to this:
```
ephemeral "tfe_organization_token" "example" {
name   = "my-org-name"
}
output "my-org-token" {
value       = ephemeral.tfe_organization_token.this.token
ephemeral   = true
}
```
Then init and apply the configuration.
The state file should not include the ephemeral resource. …
> feat: add tfe_organization_token ephemeral resource

- internal/provider/provider.go
- internal/provider/provider_next.go
- internal/provider/resource_tfe_organization_default_settings.go
- internal/provider/resource_tfe_organization_default_settings_test.go
This PR upgrades the `tfe_organization_default_settings` resource to the provider framework.
1. Acc tests
2. Use the resource in config and verify that it works as expected.
> chore: upgrade tfe_organization_default_settings to provider framework

- CHANGELOG.md
- go.mod
- go.sum
- internal/provider/attribute_helpers.go
- internal/provider/resource_tfe_test_variable.go
- internal/provider/resource_tfe_test_variable_test.go
- internal/provider/resource_tfe_variable.go
- internal/provider/resource_tfe_variable_test.go
- website/docs/r/tfe_test_variable.html.markdown
- website/docs/r/variable.html.markdown
Add a write-only attributes to `tfe_variable`, so that a user can pass sensitive data to the resource securely and temporarily without storing it in the Terraform state file or having it show up in the plan.
Write only arguments can consume ephemeral values and non ephemeral values.
More info about write-only :
https://developer.hashicorp.com/terraform/plugin/framework/resources/write-only-arguments
https://developer.hashicorp.com/terraform/language/resources/ephemeral/write-only
_Remember to:_
1. Apply a configuration that uses a tfe_variable and the new value_wo attribute:
```
variable "session_token" {
type      = string
ephemeral = true
}
resource "tfe_variable" "agent_token" {
key          = "my_agent_token_name"
value_wo = var.session_token
sensitive    = false
category     = …
```
> create a write only mode attribute to set a tfe_variable and tfe_test_variable value

- CHANGELOG.md
- internal/provider/helpers/write_only.go
- internal/provider/planmodifiers/write_only.go
- internal/provider/resource_tfe_policy_set_parameter.go
- internal/provider/resource_tfe_policy_set_parameter_test.go
- website/docs/r/policy_set_parameter.html.markdown
Add a write-only attributes to `tfe_policy_set_parameter`, so that a user can pass sensitive data to the resource securely and temporarily without storing it in the Terraform state file or having it show up in the plan.
Write only arguments can consume ephemeral values and non ephemeral values.
_Remember to:_
1. Apply a configuration that uses a `tfe_policy_set_parameter` and the new `value_wo` attribute:
```
variable "secret" {
type      = string
ephemeral = true
}
data "tfe_policy_set" "this" {
name         = "my-policy-set-name"
organization = "my-org-name"
}
resource "tfe_policy_set_parameter" "secret" {
key          = "my_secret"
value_wo = var.secret
sensitive    = false
policy_set_id = data.tfe_policy_set.this.id
}
```
The state should not include the value information:
``` …
```
> [TF-23089] implement write only values for tfe_policy_set_parameter

- CHANGELOG.md
- internal/provider/data_source_ssh_key_test.go
- internal/provider/provider.go
- internal/provider/provider_next.go
- internal/provider/resource_tfe_ssh_key.go
- internal/provider/resource_tfe_ssh_key_test.go
- internal/provider/resource_tfe_workspace_test.go
- website/docs/d/ssh_key.html.markdown
- website/docs/r/ssh_key.html.markdown
This PR migrates `tfe_ssh_key` to the provider framework and adds the write-only attribute `key_wo`, so that a user can pass sensitive private key data to the resource securely and temporarily without storing it in the Terraform state file or having it show up in the plan.
Write only arguments can consume ephemeral values and non ephemeral values.
_Remember to:_
1. Apply a configuration that uses a `tfe_policy_set_parameter` and the new `value_wo` attribute:
```
variable "private_key" {
type      = string
ephemeral = true
}
resource "tfe_ssh_key" "this" {
name            = "my_key"
organization    = "my_org"
key_wo          = var.secret
}
```
The state should not include the value information:
```
"key": null,
"key_wo": null,
```
The value that was written into HCPT will not show up in …
> feat: add write-only `key_wo` attribute to `tfe_ssh_key`

- internal/provider/data_source_project.go
- internal/provider/data_source_project_test.go
- internal/provider/data_source_projects.go
- internal/provider/provider.go
- internal/provider/provider_next.go
- internal/provider/resource_tfe_project.go
- internal/provider/resource_tfe_project_test.go
- internal/provider/resource_tfe_workspace_test.go
This PR migrates the `tfe_project` resource and data source to the provider framework:
Acceptance tests that made use of any of the above also needed to be switched to the muxed provider factory.
1.  acc tests
2. all data sources and resources should continue to function as usual
```
$ TESTARGS="-run TestAccTFEProjectDataSource_" make testacc
=== RUN   TestAccTFEProjectDataSource_basic
--- PASS: TestAccTFEProjectDataSource_basic (8.12s)
=== RUN   TestAccTFEProjectDataSource_caseInsensitive
--- PASS: TestAccTFEProjectDataSource_caseInsensitive (5.33s)
=== RUN   TestAccTFEProjectDataSource_basicWithAutoDestroy
--- PASS: TestAccTFEProjectDataSource_basicWithAutoDestroy (5.27s)
PASS
ok      github.com/hashicorp/terraform-provider-tfe/internal/provider   19.255s
$ TESTARGS="-run …
```
> chore: migrate tfe_project to the provider framework

- CHANGELOG.md
- docs/testing.md
- internal/provider/provider_test.go
- internal/provider/resource_tfe_oauth_client.go
- internal/provider/resource_tfe_oauth_client_test.go
Previously, `terraform apply` was required to run twice before the `oauth_token_id` would be persisted in the state file when the OAuth token changes even though the `oauth_token_id` was updated as expected on the server after the first run of `terraform apply`. With this change, only a single run of `terraform apply` is necessary to persist the changes for the `oauth_token_id` to the state file when the OAuth token changes..
In order for the test to run, **two** OAuth tokens need to be present in the environment. I added `GITHUB_TOKEN2` to the test environment. The same will need to be done for CI.
_Remember to:_
1.  Create a resource with an `oauth_token`.
1.  Perform `terraform plan` and verify no changes are required.
1.  Update the value of `oauth_token`.
1.  Perform `terraform plan` …
> [IPL-7245] Fix OAuth Token ID updates not registering

- CHANGELOG.md
- internal/provider/resource_tfe_workspace_run_test.go
This PR updates the changelog to use conventional formatting.
It also re-enables a flaky test and updates the changelog with a missing item.
> chore: use conventional formatting for changelog

- CHANGELOG.md
- internal/provider/data_source_registry_module.go
- internal/provider/data_source_registry_module_test.go
- internal/provider/provider_next.go
- internal/provider/resource_tfe_registry_module_test.go
- website/docs/d/registry_module.html.markdown
Closes: #1666, #1141
_Remember to:_
```shell
TESTARGS="-run TestAccTFERegistryModuleDataSource" make testacc
TF_ACC=1 TF_LOG_SDK_PROTO=OFF go test $(go list ./... |grep -v 'vendor') -v -run TestAccTFERegistryModuleDataSource -timeout 15m
testing: warning: no tests to run
PASS
ok  	github.com/hashicorp/terraform-provider-tfe/internal/client	(cached) [no tests to run]
testing: warning: no tests to run
PASS
ok  	github.com/hashicorp/terraform-provider-tfe/internal/logging	(cached) [no tests to run]
?   	github.com/hashicorp/terraform-provider-tfe/internal/provider/helpers	[no test files]
?   	github.com/hashicorp/terraform-provider-tfe/internal/provider/planmodifiers	[no test files]
? …
```
> Ds new datasource registry module

- internal/provider/provider.go
- internal/provider/provider_next.go
- internal/provider/resource_tfe_team_token.go
This PR migrates the `tfe_team_token` resource to the provider framework.
Run acceptance tests
```
$ TESTARGS="-run TestAccTFETeamToken_" make testacc
=== RUN   TestAccTFETeamToken_basic
--- PASS: TestAccTFETeamToken_basic (3.97s)
=== RUN   TestAccTFETeamToken_existsWithoutForce
--- PASS: TestAccTFETeamToken_existsWithoutForce (4.79s)
=== RUN   TestAccTFETeamToken_existsWithForce
--- PASS: TestAccTFETeamToken_existsWithForce (6.97s)
=== RUN   TestAccTFETeamToken_withBlankExpiry
--- PASS: TestAccTFETeamToken_withBlankExpiry (4.01s)
=== RUN   TestAccTFETeamToken_withValidExpiry
--- PASS: TestAccTFETeamToken_withValidExpiry (3.97s)
=== RUN   TestAccTFETeamToken_withInvalidExpiry
--- PASS: TestAccTFETeamToken_withInvalidExpiry (2.00s)
=== RUN   TestAccTFETeamToken_import
--- PASS: …
```
> Migrate `tfe_team_token` to the provider framework

- internal/provider/data_source_variables.go
- internal/provider/provider.go
- internal/provider/provider_next.go
This PR migrates `tfe_variables` to the provider framework.
_Remember to:_
1. Acc tests & manual/smoke testing.
```
$ TESTARGS="-run TestAccVariablesDataSource_" make testacc
=== RUN   TestAccTFEVariablesDataSource_basic
--- PASS: TestAccTFEVariablesDataSource_basic (9.58s)
PASS
ok      github.com/hashicorp/terraform-provider-tfe/internal/provider   10.361s
```
> chore: migrate tfe_variables to the provider framework

- CHANGELOG.md
- internal/provider/data_source_outputs.go
- internal/provider/data_source_outputs_next.go
- internal/provider/plugin_provider.go
- internal/provider/plugin_provider_test.go
- internal/provider/provider_next.go
- internal/provider/provider_test.go
- main.go
Addresses #1697, a regression found following the release of v0.65.0.
This PR reverts the `tfe_outputs` data source to a known prior working state, but leaves the `tfe_output` ephemeral resource intact.
The framework-upgraded `tfe_outputs` data source has been retained in `data_source_outputs_next.go`.
> Revert tfe_outputs to pre-framework state

- internal/client/config.go
Original Author: @mcsaucy 
`sha256.New().Sum(foo)` appends the SHA-256 hash for nil to foo. See https://go.dev/play/p/vSW0U3Hq4qk
I think was only used for comparisons, which meant it worked just fine but your comparisons were less efficient and the SHA256 did nothing for you.
I'm making this change as part of a cleanup of invalid hash.Hash uses across Github.
Acceptance tests in the CI should cover it.
I spent a while trying to work out how to set up a test environment and gave up after it took substantially longer than the actual fixing of the bug. Seems like I'd need to set up a Terraform instance. If this is insufficient, lemme know and I'll close the PR and flip this to an issue for someone else to take.
> Use the correct form of `sha256.Sum256`.

- internal/provider/resource_tfe_policy_set_parameter.go
- internal/provider/resource_tfe_team_token.go
The recent releases of v0.65.0 and v0.65.1 contain several regressions:
- `tfe_team_token` clears token from state after upgrade (#1700)
-  `tfe_policy_set_parameter` errors attempting to unnecessarily upgrade schema version
- `url` attribute validation doesn't work as expected for `tfe_notification_configuration` (#1696)
This PR provides resolution for the first two issues, and #1705 resolves the third.
```
resource "tfe_policy_set" "test" {
name         = "my-policy-set-name"
}
resource "tfe_policy_set_parameter" "test" {
key          = "my_key_name"
value        = "my_value_name"
policy_set_id = tfe_policy_set.test.id
}
```
1. Use v0.64 to create a policy set param with the config above
1. Re-apply the config with the provider version in this PR
1. Ensure no errors are thrown relating …
> Fix several regressions in v0.65.x

- internal/provider/resource_tfe_organization_run_task.go
- internal/provider/resource_tfe_organization_run_task_test.go
This PR fixes a regression in the `tfe_organization_run_task` resource (introduced in #1646) that effectively disabled in-place updates for the `hmac_key` attribute.
1. Visit https://webhook.site/ and copy the link from "Your unique URL". Leave the browser tab open.
2.  Provision an organization run task with the following config:
```
resource "tfe_organization_run_task" "example" {
url          = "<WEBHOOK_LINK_FROM_STEP_1>"
name         = "my_task"
enabled      = true
description  = "An example task"
hmac_key = "hmac"
}
```
3. Confirm a webhook has been received on the test site. Take note of the `x-tfc-task-signature` header value.
4. Update the `hmac_key` attribute in config to have a different value and run an apply. An in-place update should follow.
5. Confirm another webhook has …
> fix(organization_run_task): allow in-place updates to hmac_key

- CHANGELOG.md
- internal/provider/resource_tfe_workspace_settings.go
- internal/provider/resource_tfe_workspace_settings_test.go
Addresses `Error: Provider produced inconsistent result after apply` for remote_state_consumer_ids as reported in #1688 
_Remember to:_
```
$ TESTARGS="-run TestAccTFEWorkspaceSettingsRemoteState" make testacc
TF_ACC=1 TF_LOG_SDK_PROTO=OFF go test $(go list ./... |grep -v 'vendor') -v -run TestAccTFEWorkspaceSettingsRemoteState -timeout 15m
--- PASS: TestAccTFEWorkspaceSettingsRemoteState (8.57s)
PASS
ok      github.com/hashicorp/terraform-provider-tfe/internal/provider   9.195s
```
> fix: default remote_state_consumer_ids to empty set of strings, not null

- CHANGELOG.md
- go.mod
- go.sum
- internal/provider/resource_tfe_team_token.go
- internal/provider/resource_tfe_team_token_test.go
- website/docs/r/team_token.html.markdown
This PR adds support to create multiple team tokens for a single team using `tfe_team_token` by adding the `description` attribute. If no description is provided, it follows the previous behavior of `tfe_team_token`, which uses the old team token API that assumes there is only one token per team.
Some other notable differences:
- The new API for team tokens that supports multiple tokens does not support regenerating tokens with a single API request (i.e., they must be rotated via separate delete and create requests). That means `force_regenerate` cannot be used when `description` is set.
- The ID of the resource was previously the team ID since there was only ever one token per team. For tokens without descriptions, this will continue to be the team ID to preserve backwards compatibility. …
> Support multiple team tokens for a single team with `tfe_team_token`

- CHANGELOG.md
- internal/provider/resource_tfe_workspace.go
We saw an issue where planning a tfe_workspace with  tag_names (relating to single value tags) and not tags (for KV), we'd sometimes see a diff like so:
```terraform
~ tags = {
- "example-tag"  = null
- "example-tag2" = null
}
```
This occurs when a separate configuration uses the provisioned tfe_workspace , as targeted by the tags given in its cloud block.
```terraform 
cloud {
organization = "hashicorp"
hostname     = "tfcdev-2cdff5a5.ngrok.app"
workspaces {
tags = ["example-tag", "example-tag2"]
}
}
```
In the Cloud block, we're checking if the feature is available (by whether it 404s on the list tag binding endpoint), and if it is, the workspace's single value tags are added as KV tags. So now that the KV tag FF has been fully lifted, customers are hitting that code path and seeing …
> Make `tags` a computed attribute on workspace resources

- website/docs/r/agent_pool_allowed_workspaces.html.markdown
`tfe_workspace.test` is not defined, should use `tfe_workspace.test-workspace` instead
> Fix `tfe_agent_pool_allowed_workspaces` example using resources that aren't defined

- CHANGELOG.md
- internal/provider/resource_tfe_notification_configuration.go
In tfe_notification_configuration, the url argument is now marked as sensitive so that the values are masked.
_Remember to:_
- [JIRA](https://hashicorp.atlassian.net/browse/IPL-7733)
> IPL-7733 Update tfe_notification_configuration to sensitive url

- CHANGELOG.md
- website/docs/r/workspace.html.markdown
- website/docs/r/workspace_run.html.markdown
This PR fixes some incorrect usages of `tfe_workspace` and `tfe_workspce_run` in the documentation examples, originally by @StamatisChr (#1813) 
Using the documentation example as is, `terraform plan` gives the error:
```
│ Error: Incorrect attribute value type
│ 
│   on main.tf line 12, in resource "tfe_oauth_client" "test":
│   12:   organization     = tfe_organization.test-organization
│     ├────────────────
│     │ tfe_organization.test-organization is object with 14 attributes
│ 
│ Inappropriate value for attribute "organization": string required.
```
_Remember to:_
N/A
N/A
N/A
N/A
Screenshots from https://registry.terraform.io/tools/doc-preview:
> docs: fixed tfe_workspace & tfe_workspace_run examples

- CHANGELOG.md
- internal/provider/resource_tfe_oauth_client.go
- internal/provider/resource_tfe_oauth_client_test.go
Remove the `ForceNew` flag from the `oauth_token` attribute of `r/tfe_oauth_client` to allow in-place updates of the OAuth client during token rotation. This prevents the OAuth client from being replaced, avoiding re-establishment of VCS connections with workspaces and preventing runs from being triggered unnecessarily.
_Remember to:_
- Run the acceptance test command below with the required environment variables (`TFE_TOKEN`, `TFE_HOSTNAME`, `GITHUB_TOKEN` and `GITHUB_TOKEN2`).
- The acceptance test should pass.
- [JIRA](https://hashicorp.atlassian.net/browse/TF-28073) …
> Remove ForceNew from oauth_token attribute of r/tfe_oauth_client

- CHANGELOG.md
- docs/testing.md
- internal/provider/data_source_organization.go
- internal/provider/data_source_organization_test.go
- internal/provider/data_source_workspace.go
- internal/provider/data_source_workspace_test.go
- internal/provider/helper_test.go
- internal/provider/resource_tfe_aws_oidc_configuration_test.go
- internal/provider/resource_tfe_azure_oidc_configuration_test.go
- internal/provider/resource_tfe_gcp_oidc_configuration_test.go
- internal/provider/resource_tfe_hyok_configuration_test.go
- internal/provider/resource_tfe_organization.go
- internal/provider/resource_tfe_organization_test.go
- internal/provider/resource_tfe_vault_oidc_configuration_test.go
- internal/provider/resource_tfe_workspace.go
- internal/provider/resource_tfe_workspace_test.go
- internal/provider/subscription_updater_test.go
- website/docs/d/organization.html.markdown
- website/docs/d/workspace.html.markdown
- website/docs/r/organization.html.markdown
- website/docs/r/workspace.html.markdown
Updating the attributes for `Organization` and `Workspace` to support HYOK related attributes.
_Remember to:_
1. Using a version of https://github.com/hashicorp/go-tfe/pull/1201 and using an organization with access to HYOK
2. Use a terraform configuration with resources to create and update Organizations and Workspaces with HYOK options via `terraform plan`, and `terraform apply`.
```
resource "tfe_organization" "provider-tfe-hyok-test" {
name         = "provider-tfe-hyok-test"
email        = "YOUR-EMAIL"
enforce_hyok = true
}
resource "tfe_workspace" "test-workspace-hyok-enabled" {
organization = "YOUR-ORG"
name         = "test-workspace-hyok-enabled"
}
```
3. Use a terraform configuration with data sources to read Organizations and Workspaces with HYOK options via `terraform plan`, and …
> [TF-28673] Adding HYOK related attributes to Organizations and Workspaces
